.gitignore, static/js/services/build/build.service.impl.spec.ts, static/js/services/build/build.service.impl.ts, static/js/services/build/build.service.ts
Some code was removed due to an mistake in the `.gitignore`. Added it back.
Fixes https://issues.jboss.org/browse/PROJQUAY-3
=> Fix Missing TypeScript Code

README.md, docs/development-container.md
This change also removes any dangling references to github.com/quay/projectquay
=> Update documentation to reflect JBoss JIRA usage

data/database.py, data/encryption.py, data/migrations/tester.py, data/migrations/versions/34c8ef052ec9_repo_mirror_columns.py, data/migrations/versions/703298a825c2_backfill_new_encrypted_fields.py, data/migrations/versions/c059b952ed76_remove_unencrypted_fields_and_data.py, data/migrationutil.py
This change ensures there is better messaging around the encrypted token migration, including a new phase to use for new installations, and fixes an issue encountered when running database migrations for new installations
=> Fix the encrypted token migration issue encountered on HEAD

deploy/openshift/quay-app.yaml
Added environments for Quay container so user can provide a custom names for namespace and config secret.
https://issues.jboss.org/browse/PROJQUAY-23
=> PROJQUAY-23 - openshift template updated to allow custom namespace & config secret name

README.md
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
* ..
* ..
**TESTING** ->
---
=> README: pointing to the correct community list

.travis.yml
Enable travis on all branches, not just master
https://issues.jboss.org/browse/PROJQUAY-18
=> PROJQUAY-18 - .travis.yml runs all branches

data/migrations/versions/703298a825c2_backfill_new_encrypted_fields.py
This fixes the logic on the token_name lookup and only applies it to non-temporary tokens
=> Fix clearing of names on access tokens

scripts/app_sre_post_deploy_rhel7.sh
This PR adds a script that will be executed on each merge to master after the deployment is complete. The script will push the built image to a backup repository.
* Added post deploy script
https://jira.coreos.com/browse/APPSRE-1282
https://gitlab.cee.redhat.com/service/app-interface/merge_requests/2226
=> Add App SRE post deploy script

data/model/repository.py, workers/gc/gcworker.py
Fixes https://issues.jboss.org/projects/PROJQUAY/issues/PROJQUAY-37
=> Fix out of bounds on GC worker when there are no namespaces defined

requirements.txt
https://issues.jboss.org/browse/PROJQUAY-40
To reproduce, attempt to set azure storage and push image before and after this change.
=> PROJQUAY-40 - downgrade azure storage packages

static/css/directives/ui/repository-events-table.css, static/directives/repo-view/repo-panel-settings.html, static/directives/repository-events-table.html, static/js/directives/repo-view/repo-panel-settings.js, static/js/directives/ui/repo-state/repo-state.component.css, static/js/directives/ui/repo-state/repo-state.component.html, static/js/directives/ui/repo-state/repo-state.component.ts, static/js/quay.module.ts, static/js/types/custom.d.ts
(cherry picked from commit 6f21f034ca2703be1e00747723b76a7308c4b50f)
https://github.com/quay/quay/pull/34
https://issues.jboss.org/browse/PROJQUAY-43
=> PROJQUAY-43 - added repo-state UI styling and refactored to TypeScript

CHANGELOG.md
https://jira.coreos.com/browse/QUAY-2207
Placeholder to display correct version in web UI
=> QUAY-2207 - CHANGELOG.md placeholder

static/directives/repository-events-table.html, static/js/directives/ui/repository-events-table.js
(cherry picked from commit 1c9736f5cf2c05784d80512c45a11509000d7555)
https://issues.jboss.org/browse/PROJQUAY-42
=> allow creating notifications for mirrored repositories

Dockerfile.centos7.osbs, Dockerfile.osbs
This change adds the missing installation commands to the OSBS Dockerfiles that were missed in #22 .
=> dockerfile: add pushgateway to OSBS images

static/directives/repo-view/repo-panel-mirroring.html
On certain browsers (Chrome and Firefox at least, not Brave), the scrollbar would disappear on the repo view. This was due to the "Update Credentials" modal being triggered (but not shown), which applied `overflow: hidden` on the `<body>` element. The modal was being triggered by browser input autocompletion.
Fixes https://issues.redhat.com/browse/PROJQUAY-6
=> Fix Broken Scrollbar on Repository View

util/metrics/prometheus.py
breaks out host, pid, process name in the grouping key and adds logging for it
=> util/metrics: log groupkey and add more host data

workers/repomirrorworker/__init__.py, workers/repomirrorworker/test/test_repomirrorworker.py
https://issues.redhat.com/browse/PROJQUAY-53
https://jira.coreos.com/browse/QUAY-2202
When calling skopeo use decrypted robot token
=> PROJQUAY-53 - repo mirror decrypt robot token

deploy/openshift/quay-app.yaml
JIRA: https://issues.redhat.com/browse/PROJQUAY-56
=> added metrics port to clusterip service

config_app/js/core-config-setup/config-setup-tool.html
https://issues.redhat.com/browse/PROJQUAY-59
=> PROJQUAY-59 - add RHOCS to NooBaa description

config_app/js/core-config-setup/config-setup-tool.html
https://issues.redhat.com/browse/PROJQUAY-58
=> PROJQUAY-58 - remove repo mirror tech preview

workers/repomirrorworker/__init__.py, workers/repomirrorworker/test/test_repomirrorworker.py
(cherry picked from commit f2291814aa53acb32f1f9d9d0828dd8d268fef60)
https://issues.redhat.com/browse/PROJQUAY-53
https://jira.coreos.com/browse/QUAY-2202
=> PROJQUAY-53 - cherry-pick - repo mirror decrypt robot token

static/directives/repo-view/repo-panel-mirroring.html, static/js/directives/ui/entity-search.js
(cherry picked from commit 0825c0615354b53a52a1dbe2d28aafa85782f0e5)
https://issues.redhat.com/browse/PROJQUAY-57
=> PROJQUAY-57 - cherry-pick - restrict mirror robot dropdown select to just robots

config_app/js/core-config-setup/config-setup-tool.html
(cherry picked from commit 79e5e4ecd5b10a26106b9bda175ff591e308e7df)
https://issues.redhat.com/browse/PROJQUAY-59
=> PROJQUAY-59 - cherry-pick - add RHOCS to NooBaa description

config_app/js/core-config-setup/config-setup-tool.html
(cherry picked from commit 7a7e6366397350308b2cfb03ed6b78232f0e7950)
https://issues.redhat.com/browse/PROJQUAY-58
=> PROJQUAY-58 - cherry-pick - remove repo mirror tech preview

data/migrations/versions/703298a825c2_backfill_new_encrypted_fields.py
https://jira.coreos.com/browse/QUAY-2204
=> Remove AccessToken delete now that it has been run on production

config_app/js/core-config-setup/config-setup-tool.html, config_app/js/core-config-setup/core-config-setup.js
Fixes https://issues.redhat.com/browse/PROJQUAY-62
=> Mark torrent and ACI conversion as deprecated

data/fields.py, data/migrations/versions/34c8ef052ec9_repo_mirror_columns.py
Fixes https://jira.coreos.com/browse/QUAY-2225
=> Re-encrypt fields encrypted using the older key in 3.1.X

data/fields.py, data/migrations/versions/34c8ef052ec9_repo_mirror_columns.py
Fixes https://jira.coreos.com/browse/QUAY-2225
(cherry picked from commit 7ad5115fdc1723fbfe4618fc22c417408bed9aab)
=> QUAY-2225 - cherry-pick - Re-encrypt fields encrypted using the older key in 3.1.X

config_app/js/core-config-setup/config-setup-tool.html, config_app/js/core-config-setup/core-config-setup.js
Fixes https://issues.redhat.com/browse/PROJQUAY-62
(cherry picked from commit 60ab963cb791abe08e56950a3b946ddc5c67af14)
=> PROJQUAY-62 - cherry-pick - Mark torrent and ACI conversion as deprecated

CHANGELOG.md
https://issues.redhat.com/browse/PROJQUAY-66
=> PROJQUAY-66 - v3.2.0 CHANGELOG

deploy/openshift/quay-app.yaml
JIRA: https://issues.redhat.com/projects/PROJQUAY/issues/PROJQUAY-67
=> updated syslog port to string in openshift template

endpoints/api/repository_models_pre_oci.py, endpoints/api/test/test_repository.py
(cherry picked from commit c0a98084480b1c3537bdf033e808354af1625798)
https://issues.redhat.com/browse/QUAY-2213
=> QUAY-2213 - cherry-pick - fix starred application repositories API response

scripts/ci
https://issues.redhat.com/browse/PROJQUAY-92
https://github.com/psf/black/issues/1207#issuecomment-566249522
=> PROJQUAY-92 - fix 'black' regex error

data/migrations/versions/703298a825c2_backfill_new_encrypted_fields.py
https://jira.coreos.com/browse/QUAY-2204
=> QUAY-2204 - cherry-pick - avoid db connection timeouts

CHANGELOG.md
https://issues.redhat.com/browse/PROJQUAY-66
=> PROJQUAY-66 - 3.2.0 changelog update

conf/init/certs_install.sh
=> follow sym links for extra certs

deploy/openshift/quay-app.yaml
https://issues.redhat.com/browse/PROJQUAY-97
=> removed extra ca certs mount

endpoints/api/repository_models_pre_oci.py, endpoints/api/test/test_repository.py
Further fixes from #67.
Fixes https://issues.redhat.com/browse/QUAY-2213
=> Fix Starred Repositories API response

Dockerfile.rhel8, _init.py, docs/development-container.md, external_libraries.py, quay-entrypoint.sh, requirements.txt
https://issues.redhat.com/browse/PROJQUAY-96
=> PROJQUAY-96 - python3 Dockerfile and related

Dockerfile.cirun, buildman/builder.py, buildman/component/buildcomponent.py, buildman/jobutil/buildstatus.py, buildman/manager/enterprise.py, buildman/manager/ephemeral.py, buildman/manager/executor.py, buildman/orchestrator.py, buildman/server.py, buildman/test/test_buildman.py, config_app/config_endpoints/common.py, data/model/oauth.py, endpoints/appr/models_cnr.py, endpoints/appr/models_interface.py, endpoints/common.py, storage/cloud.py, test/test_endpoints.py
* Move from `trollius` to `asyncio` in the build manager
**TESTING** ->
---
=> Python3 trollius to asyncio

data/registry_model/blobuploader.py, endpoints/v2/blob.py
Fixes https://issues.redhat.com/browse/PROJQUAY-126
=> Small fixes to invalid digest calls

notifications/notificationmethod.py, static/css/directives/ui/repository-events-table.css, static/directives/create-external-notification.html, static/directives/repository-events-table.html, static/js/directives/ui/create-external-notification.js, static/js/services/external-notification-data.js, util/jsontemplate.py, util/test/test_jsontemplate.py
This will allow users to configure the body content of outgoing webhooks for notifications
Fixes https://jira.coreos.com/browse/QUAY-1322
=> Add support for custom webhook bodies

data/model/oauth.py, oauth/provider.py, oauth/utils.py, requirements.txt
* Removes oauth2lib as a dependency
* [PROJQUAY-128](https://issues.redhat.com/browse/PROJQUAY-128)
* Copied and ported to Python3 the `provider` class, which is really just a helper class to generate various `Response` objects.
**TESTING** ->
---
=> Removes oauth2lib dependency

data/database.py, data/fields.py, data/model/appspecifictoken.py, data/model/user.py, data/registry_model/blobuploader.py, requirements.txt, test/registry/registry_tests.py, test/registry_tests.py, util/registry/torrent.py, util/validation.py
* Replace resumablehaslib with rehash
* Format python files with Black
* Small Python3 specific fix + import statement fix
* ..
* ..
**TESTING** ->
---
=> Replace resumablehashlib

static/css/directives/ui/label-view.css, static/directives/label-view.html, static/js/directives/ui/label-view.js, static/js/directives/ui/manifest-label-list.js
Fixes https://issues.redhat.com/browse/PROJQUAY-129
=> Have labels with URLs in them turn into links

data/migrations/script.py.mako
Fixes https://issues.redhat.com/browse/PROJQUAY-125
=> Fix import in data migration template

app.py, config_app/config_application.py, util/config/superusermanager.py
* Convert `str` to `bytes` where expected
* ..
* ..
**TESTING** ->
---
=> Fix byte string instances

buildtrigger/gitlabhandler.py
Fixes https://issues.redhat.com/browse/QUAY-2100
=> Catch further exception type when attempting to auth to Gitlab

endpoints/verbs/__init__.py, util/registry/queuefile.py, util/registry/test/test_queuefile.py
https://issues.redhat.com/browse/PROJQUAY-132
=> Add a timeout to queuefile to ensure it doesn't block forever

data/logs_model/table_logs_model.py, data/logs_model/test/test_logs_interface.py, data/model/log.py
Adds additional testing and assertions as well
Fixes https://issues.redhat.com/browse/QUAY-2239
=> Fix the assertion in lookup of logs by namespace

data/registry_model/blobuploader.py, endpoints/metrics.py
These were named inconsistently. /shrug
=> metrics: push/pull bytes metrics named consistent

static/partials/privacy.html, static/partials/tos.html
Mentions upcoming changes to the Privacy Policy and Terms of Service for Quay.io on the respective static pages.
- https://issues.redhat.com/browse/QUAY-1748
---
=> Indicate upcoming Quay.io ToS & Privacy Policy changes.

Dockerfile, Dockerfile.rhel8, requirements-nover.txt, requirements.txt, util/security/signing.py
https://issues.redhat.com/browse/PROJQUAY-123
Updated Dockerfile.centos8 to install gpgme-devel. Also uncommented remaining aspects to build container.
=> PROJQUAY-123 - enable repo for gpgme-devel

boot.py, buildman/manager/executor.py, conf/init/certs_install.sh, data/appr_model/manifest.py, data/appr_model/manifest_list.py, data/appr_model/package.py, data/appr_model/release.py, data/appr_model/tag.py, data/logs_model/logs_producer/kinesis_stream_logs_producer.py, data/model/image.py, data/registry_model/datatypes.py, digest/checksums.py, digest/digest_tools.py, endpoints/appr/__init__.py, endpoints/appr/cnr_backend.py, endpoints/appr/models_cnr.py, endpoints/appr/registry.py, endpoints/appr/test/test_api.py, endpoints/verbs/__init__.py, features/__init__.py, image/docker/schema1.py, image/docker/schema2/manifest.py, requirements.txt, storage/fakestorage.py, util/registry/torrent.py, util/security/fingerprint.py, util/streamingjsonencoder.py
=> Dependencies updates

active_migration.py, data/migrations/versions/c059b952ed76_remove_unencrypted_fields_and_data.py, data/model/user.py
Fixes the migration ID in one of the phases, and adds an extra assertion and checks in the robot migration
Fixes https://issues.redhat.com/browse/PROJQUAY-168
=> Small fixes for the encrypted token migration

conf/gunicorn_registry.py, conf/gunicorn_secscan.py, conf/gunicorn_web.py, registry.py, secscan.py, web.py
https://issues.redhat.com/browse/PROJQUAY-169
* Monkey patch before importing other dependencies when starting a gunicorn
* ..
* ..
**TESTING** ->
---
=> Gevent monkey patch fix

requirements.txt
* Fixed urllib in quay/appr and updated the commit ref in requirements.txt
* ..
* ..
**TESTING** ->
---
=> Update appr commit ref

data/fields.py, data/model/build.py
Fixes https://issues.redhat.com/browse/PROJQUAY-186
=> Fix bitbucket trigger creation around access tokens

Dockerfile.cirun, Makefile, Makefile.ci, active_migration.py, auth/auth_context_type.py, buildman/component/buildcomponent.py, buildtrigger/basehandler.py, data/database.py, data/model/appspecifictoken.py, data/model/build.py, data/model/oauth.py, data/model/token.py, data/model/user.py, deploy/openshift/quay-app.yaml, endpoints/api/organization.py, endpoints/api/robot_models_pre_oci.py, endpoints/api/trigger.py, quay-entrypoint.sh
Fixes https://issues.redhat.com/browse/PROJQUAY-185
=> Remove the active migration for encrypted tokens now that it is complete

app.py
Found duplicate code block in `app.py`.
=> Remove Duplicate Code for Secscan Client

conf/init/nginx_conf_create.py
=> Fixed CI failure due to formatting issue

Dockerfile.cirun, Makefile, Makefile.ci, active_migration.py, auth/auth_context_type.py, buildman/component/buildcomponent.py, buildtrigger/basehandler.py, data/database.py, data/model/appspecifictoken.py, data/model/build.py, data/model/oauth.py, data/model/token.py, data/model/user.py, deploy/openshift/quay-app.yaml, endpoints/api/organization.py, endpoints/api/robot_models_pre_oci.py, endpoints/api/trigger.py, quay-entrypoint.sh
Reverts quay/quay#181
This PR was not ready and I prematurely merged it. It will be re-created in the future.
=> Revert "Remove the active migration for encrypted tokens now that it is complete"

deploy/openshift/quay-app.yaml
=> Debug needs to be passed as string and not boolean

data/model/label.py, data/model/oci/label.py, data/model/oci/manifest.py, data/registry_model/registry_pre_oci_model.py, test/registry/registry_tests.py
Fixes https://issues.redhat.com/browse/PROJQUAY-178
=> Fix label handling for empty labels

auth/basic.py, auth/test/test_basic.py, auth/test/test_credentials.py, auth/test/test_registry_jwt.py, avatars/avatars.py, data/encryption.py, data/fields.py, data/model/_basequery.py, data/model/appspecifictoken.py, data/model/user.py, data/registry_model/blobuploader.py, data/test/test_encryption.py, digest/digest_tools.py, digest/test/test_digest_tools.py, endpoints/api/tag.py, endpoints/csrf.py, endpoints/v2/v2auth.py, image/docker/schema1.py, image/docker/schema2/manifest.py, image/docker/schema2/test/test_list.py, image/docker/schema2/test/test_manifest.py, image/docker/test/test_schemautil.py, initdb.py, requirements.txt, util/bytes.py, util/registry/torrent.py, util/security/secret.py, util/security/test/test_secret.py, util/security/token.py
* Makes the conversions from str to bytes when needed.
* ..
* ..
**TESTING** ->
---
=> Bytes unicode conversion

CHANGELOG.md
https://issues.redhat.com/browse/PROJQUAY-66
=> PROJQUAY-66 - cherry pick CHANGELOG

data/test/test_userfiles.py, endpoints/v2/test/test_blob.py, endpoints/v2/test/test_manifest.py, storage/downloadproxy.py, test/specs.py, util/secscan/api.py, util/tufmetadata/api.py
* Fix various generated token when encoding them.
* ..
* ..
**TESTING** ->
---
=> fix various token encoding

data/model/oci/manifest.py, data/model/oci/retriever.py
Fixes https://issues.redhat.com/browse/PROJQUAY-219
=> Better manifest errors

data/secscan_model/test/test_secscan_v2_model.py
Should help us catch typos in the future
=> Add additional tests for the new V2 secscan wrapper

data/model/storage.py, data/secscan_model/secscan_v2_model.py
Also adds an optimization to avoid GCing specialized blobs
=> Add extra verification on storage GC to ensure we don't end up with dangling ImageStorage rows

Dockerfile, Dockerfile.rhel7
(cherry picked from commit 321a06daf067f99fe4c6f65f16014fc7acc86a5a)
https://issues.redhat.com/browse/PROJQUAY-146
=> PROJQUAY-146 - Pin setuptools version in Dockerfile.rhel7

CHANGELOG.md
https://issues.redhat.com/browse/PROJQUAY-189
=> PROJQUAY-189 - 3.2.1 changelog

data/model/gc.py
This should prevent the final deletion transaction from timing out
Fixes https://issues.redhat.com/browse/PROJQUAY-239
=> Pre-flight the cleanup of all big tables referencing a purged repo

data/users/test/test_shared.py, requirements-nover.txt, requirements-tests.txt, storage/test/test_azure.py
Addresses multiple test failures.
- See commit messages. Each include an accompanying error that they address.
- https://issues.redhat.com/browse/PROJQUAY-262 (mockldap)
- https://issues.redhat.com/browse/PROJQUAY-68 Python 3 Epic
**TESTING**
- Verify that the errors mentioned in this PR's commits are no longer present when running tests.
n/a
---
=> Fix multiple Python3 test failures.

endpoints/verbs/__init__.py
The request duration SLOs were previously missing from these routes.
=> verbs: time blueprint

data/registry_model/test/test_interface.py, static/css/directives/ui/repo-tag-history.css, static/directives/repo-tag-history.html, static/js/directives/ui/repo-tag-history.js
Fixes https://issues.redhat.com/browse/PROJQUAY-220
=> Hide all future tag expirations in the timeline, by default

package.json
Ensure we are running in Webpack development mode to fix JS errors.
=> Fix Local Config App Script

.gitignore, external_libraries.py, package.json, yarn.lock
Reverts the updates from #237 until we can deploy the TOS updates to Quay.io and fix the UI issues.
=> Revert Frontend Dependency Updates

quay-entrypoint.sh
When running quay under podman, interrupts sent at the controlling terminal and via `podman stop` don't trigger a shutdown. I think this is because of the shell not being replaced with the supervisord.
**TESTING** ->
---
=> entrypoint fixes

static/js/directives/repo-view/repo-panel-mirroring.js
https://issues.redhat.com/browse/PROJQUAY-222
Trim whitespace from entered list of tags to mirror
=> PROJQUAY-222 - mirror trim tag whitespace

static/css/directives/ui/signin-form.css, static/directives/icon-image-view.html
1) Display up to three per row, rather than two
2) Fix the display of external images to allow for local references
=> Small fixes for external login buttons

data/model/gc.py
If we have a bug that causes the GC's assumptions to be wrong (such
as an Image added after a purge began), then the purge loop can enter a
state where it will never halt. This change detects that condition and
raises an exception so we can properly investigate the bug.
Fixes https://issues.redhat.com/browse/PROJQUAY-452
=> Catch infinite loops in GC purge code and raise an exception instead

endpoints/api/mirror.py, workers/repomirrorworker/__init__.py
From the UI perspective, we simply replace the username with text
indicating it is invalid.
For the worker, we already raise an exception and mark the mirroring
as invalid, so add a `logger.exception` so we have additional debug
information.
Fixes https://issues.redhat.com/browse/PROJQUAY-238
=> Don't raise an exception when mirroring username/password cannot be decrypted

config_app/js/core-config-setup/config-setup-tool.html, data/users/__init__.py, data/users/externalldap.py, test/test_ldap.py, util/config/validators/validate_ldap.py
This allows customers to specify additional restrictions on the users
that are allowed to be used
Fixes https://issues.redhat.com/browse/PROJQUAY-226
=> Add ability to filter user lookups in LDAP user system

config_app/c_app.py, config_app/config_endpoints/api/superuser.py
The configuration application will attempt to validate any uploaded certificate if TLS is required when connecting to external services, such as RHOCS. Due to the config-app using the "default" configuration, it wasn't installing any uploaded certificates and every TLS request with a custom/self-signed certificate was failing.
This change-set seeks to fix that. It should also fix issues with LDAP and any other service which allows user-managed certificates.
* Config-App now runs the script to install certificates after they are uploaded so they can be used during the validation step.
- https://issues.redhat.com/browse/PROJQUAY-461
**TESTING**
- Create custom a custom certificate pair for RHOCS
- Start the config app
- Upload the public certificate
- Configure Quay to use the RHOCS and …
=> [PROJQUAY-461] Install uploaded certs in config-app for TLS validation.

data/model/oci/manifest.py, image/docker/schema2/manifest.py, test/registry/protocol_v2.py, test/registry/registry_tests.py
Fixes https://issues.redhat.com/browse/PROJQUAY-510
=> Fix support for empty manifests in V2_2

endpoints/v2/blob.py, endpoints/v2/manifest.py, endpoints/v2/test/test_manifest.py, test/registry/protocol_v2.py
Fixes https://issues.redhat.com/browse/PROJQUAY-509
=> Fix status response codes to conform to the OCI spec

data/registry_model/manifestbuilder.py
Instead, we now simply save all the Image information into the
in-memory session and then construct the manifest directly at the end.
Fixes https://issues.redhat.com/browse/PROJQUAY-513
=> Update the manifest builder for V1 API to not construct Image rows

CHANGELOG.md, _init.py, config_app/_init_config.py
https://issues.redhat.com/browse/PROJQUAY-524
=> PROJQUAY-524 - relax reading CHANGELOG.md

static/partials/new-repo.html, util/names.py, util/test/test_names.py
Fixes https://issues.redhat.com/browse/PROJQUAY-464
=> Further restrict repository names to match Docker

static/directives/tag-operations-dialog.html
Fixes https://issues.redhat.com/browse/PROJQUAY-450
=> Better Wording for Edit Manifest Labels Form 

data/model/test/test_repo_mirroring.py, util/repomirror/skopeomirror.py, workers/repomirrorworker/__init__.py, workers/repomirrorworker/test/test_repomirrorworker.py
https://issues.redhat.com/browse/PROJQUAY-550
=> PROJQUAY-550 - correct verify_tls mirroring

static/js/pages/manage-application.js
Fixes https://issues.redhat.com/browse/PROJQUAY-557
=> Correctly Redirect after Deleting Application

Dockerfile.rhel7
https://issues.redhat.com/browse/PROJQUAY-525
=> PROJQUAY-525 - rhel7 non-root container

deploy/openshift/quay-app.yaml
=> Use the new registry-nomigrate entrypoint.

config_app/js/core-config-setup/config-setup-tool.html
https://issues.redhat.com/browse/PROJQUAY-560
=> PROJQUAY-560 - config editing after validation

endpoints/realtime.py
Addresses https://issues.redhat.com/browse/PROJQUAY-562
=> Remove Realtime API Debug Route

deploy/openshift/quay-app.yaml
=> Accept the entrypoint from the template.

config_app/js/core-config-setup/config-setup-tool.html, data/users/externalldap.py, test/test_ldap.py, util/config/validators/validate_ldap.py
Also adds tests and fixes some issues with our existing filter
Fixes https://issues.redhat.com/browse/PROJQUAY-551
=> Ensure that all user-provided filters are wrapped in parens

static/partials/org-view.html, static/partials/user-view.html
* Change help texts
**TESTING** ->
---
=> Change the help text for changing user/org names

buildman/templates/cloudconfig.yaml
Fixes https://issues.redhat.com/browse/PROJQUAY-553
=> Change builders to no longer use a squashed pull

data/appr_model/tag.py, endpoints/api/repository_models_pre_oci.py, endpoints/api/test/test_repository.py
Fixes https://issues.redhat.com/browse/PROJQUAY-395
=> Fix Last Modified For App Repos

oauth/services/github.py
GitHub has deprecated support for passing the token via URL parameter
=> Change GitHub Login to send the auth token via header

config_app/js/core-config-setup/config-setup-tool.html, config_app/js/core-config-setup/core-config-setup.js, util/config/validator.py, util/config/validators/test/test_validate_elasticsearch.py, util/config/validators/test/test_validate_kinesis.py, util/config/validators/validate_elasticsearch.py, util/config/validators/validate_kinesis.py
* Add Elasticsearch options to the config app
**TESTING** ->
---
=> Config app logs options

endpoints/v2/blob.py, endpoints/v2/test/test_blob.py, test/registry/protocol_v2.py, test/registry/registry_tests.py
We were using the wrong header name and format
=> Fix our handling of chunked uploads to meet the OCI spec

config.py
(cherry picked from commit 0ad400fc6fadcdec6c7441cb38e8580f4eddae22)
https://issues.redhat.com/browse/PROJQUAY-455
=> PROJQUAY-455 - default branding for Red Hat Quay product

CHANGELOG.md
https://issues.redhat.com/browse/PROJQUAY-455
=> PROJQUAY-455 - v3.3.0 CHANGELOG.md

util/config/configutil.py
Addresses https://issues.redhat.com/browse/PROJQUAY-455
=> Default Branding for Red Hat Quay 3.3

config_app/js/core-config-setup/config-setup-tool.html
https://issues.redhat.com/browse/PROJQUAY-293
=> PROJQUAY-293 - update local storage wording

config_app/js/core-config-setup/config-setup-tool.html
https://issues.redhat.com/browse/PROJQUAY-455
=> PROJQUAY-455 - update v1 deprecation wording

util/secscan/v4/api.py, util/secscan/v4/clair-v4.openapi.json, util/secscan/v4/fake.py, util/secscan/v4/test/test_v4_api.py
Fixes https://issues.redhat.com/browse/PROJQUAY-610
=> Clair v4 `IndexState` Endpoint

config.py, notifications/notificationmethod.py, notifications/test/test_notificationmethod.py, util/config/schema.py
Fixes https://issues.redhat.com/browse/PROJQUAY-614
=> Add additional validation to webhook URLs to catch common mistakes

data/registry_model/datatypes.py, data/registry_model/registry_oci_model.py, data/registry_model/test/test_interface.py, image/oci/index.py, image/shared/schemas.py, image/shared/schemautil.py, test/registry/protocol_v2.py, test/registry/registry_tests.py
Fixes https://issues.redhat.com/browse/PROJQUAY-621
=> Fix handling of OCI indexes and add some tests

data/registry_model/datatypes.py, data/registry_model/registry_oci_model.py, data/registry_model/test/test_interface.py, image/oci/index.py, image/shared/schemas.py, image/shared/schemautil.py, test/registry/protocol_v2.py, test/registry/registry_tests.py
Fixes https://issues.redhat.com/browse/PROJQUAY-621
(cherry picked from commit 2921b3aad20f22da24eb14ab3c9b96343e88d097)
=> PROJQUAY-621 - (cherry-pick) Fix handling of OCI indexes and add some tests (#348)

util/secscan/v4/api.py, util/secscan/v4/clair-v4.openapi.json, util/secscan/v4/fake.py, util/secscan/v4/test/test_v4_api.py
(cherry picked from commit 516e34b961b4d732ee410b5f2afce6b49e9e957c)
https://issues.redhat.com/browse/PROJQUAY-610
=> PROJQUAY-610 - use /index_state endpoint for Clair v4 and update OpenAPI (#344)

config_app/config_util/k8saccessor.py, config_app/config_util/test/test_k8saccessor.py
(cherry picked from commit 392a7808757276acfaddfdbd548d85b0bb869440)
https://issues.redhat.com/browse/PROJQUAY-363
=> PROJQUAY-363 - (cherrypick) update config app to use apps/v1 Deployment (#353)

CHANGELOG.md
https://issues.redhat.com/browse/PROJQUAY-374
=> PROJQUAY-374 - 3.2.2 changelog

config.py, data/secscan_model/__init__.py, data/secscan_model/interface.py, data/secscan_model/secscan_v2_model.py, data/secscan_model/secscan_v4_model.py, data/secscan_model/test/test_secscan_interface.py, data/secscan_model/test/test_secscan_v4_model.py, util/config/schema.py
(cherry picked from commit 11eae32950d435db6dfbfeb7bbeecc6373d47cca)
https://issues.redhat.com/browse/PROJQUAY-656
=> PROJQUAY-656 - (cherry-pick) fix secscan model to work when only using Clair v2 (#362)

data/appr_model/tag.py, data/appr_model/test/test_appr_tag.py, data/model/oci/tag.py, data/model/oci/test/test_oci_tag.py
https://issues.redhat.com/browse/PROJQUAY-667
https://github.com/quay/quay/pull/366
https://github.com/quay/quay/pull/365
=> 667 cherrypick

config.py, data/secscan_model/__init__.py, data/secscan_model/interface.py, data/secscan_model/secscan_v2_model.py, data/secscan_model/secscan_v4_model.py, data/secscan_model/test/test_secscan_interface.py, data/secscan_model/test/test_secscan_v4_model.py, util/config/schema.py
(cherry picked from commit 11eae32950d435db6dfbfeb7bbeecc6373d47cca)
Fixes https://issues.redhat.com/browse/PROJQUAY-662
Fixes https://issues.redhat.com/browse/PROJQUAY-640
=> fix secscan model to work when only using Clair v2 (#362)

Dockerfile
Taken from https://issues.redhat.com/browse/PROJQUAY-525
=> Non-Root for Upstream Dockerfile

CHANGELOG.md
https://issues.redhat.com/browse/PROJQUAY-455
=> PROJQUAY-455 - 3.3 changelog

endpoints/api/tag.py
Fixes https://issues.redhat.com/browse/PROJQUAY-659
=> Change create/move tag API to prefer manifests over legacy images

data/secscan_model/test/test_secscan_v4_model.py
Fixes https://issues.redhat.com/browse/PROJQUAY-683
=> Fix V4SecurityScanner Tests

config.py, static/directives/build-log-error.html, static/directives/external-notification-view.html, static/directives/repository-tokens-table.html, static/directives/trigger/custom-git/credentials.html, static/js/directives/ui/build-log-error.js, static/js/directives/ui/credentials.js, static/js/directives/ui/external-notification-view.js, static/js/directives/ui/manage-trigger/manage-trigger.component.html, static/js/directives/ui/manage-trigger/manage-trigger.component.spec.ts, static/js/directives/ui/manage-trigger/manage-trigger.component.ts, static/js/directives/ui/repository-events-table.js, static/js/quay.module.ts, static/js/services/documentation/documentation.service.impl.ts, static/js/services/documentation/documentation.service.ts, static/js/services/external-notification-data.js, static/partials/guide.html, static/partials/manage-application.html, static/tutorial/done.html, templates/base.html, util/config/schema.py, util/http.py
Will allow for us to easily update links over time and add new
ones.
Fixes https://issues.redhat.com/browse/PROJQUAY-575
=> Update our documentation links to use a generated system

data/model/oci/tag.py, data/model/storage.py, workers/gc/gcworker.py, workers/gc/test/test_gcworker.py, workers/namespacegcworker.py, workers/repositorygcworker.py
Fixes https://issues.redhat.com/browse/PROJQUAY-658
=> GC query improvements

data/model/oci/tag.py, data/model/repository.py, data/registry_model/interface.py, endpoints/api/repository.py, endpoints/api/repository_models_pre_oci.py, endpoints/api/search.py, endpoints/api/test/test_search.py, static/directives/repo-list-view.html, static/js/directives/ui/repo-list-table.js, static/js/directives/ui/repo-list-view.js, static/js/pages/org-view.js, static/js/pages/repo-list.js, static/js/pages/search.js, static/js/pages/user-view.js, static/js/services/api-service.js, test/test_api_usage.py
We were accidentally looking up more data that strictly allowed
Adds some additional assertions and testing as well
Fixes https://issues.redhat.com/browse/PROJQUAY-439
=> Optimize repository lookup queries to meet the expected maximums

util/audit.py
Fixes https://issues.redhat.com/browse/PROJQUAY-687
=> Add user agent to our audit logs

data/cache/cache_key.py, data/cache/impl.py, endpoints/appr/models_cnr.py, endpoints/appr/test/test_api.py
Fixes https://issues.redhat.com/browse/PROJQUAY-670
=> Add caching for app registry listing package API

deploy/openshift/quay-app.yaml
=> added param to allow us to disable conn pooling

docs/getting_started.md
- Added command to add write permissions for Quay container uid on host
@thomasmckay
=> Updated docs to add write permissions to local storage

deploy/openshift/quay-app.yaml
=> deploy/openshift: quote template value

CHANGELOG.md
https://issues.redhat.com/browse/PROJQUAY-688
=> PROJQUAY-688 - qui-gon release

CHANGELOG.md
https://issues.redhat.com/browse/PROJQUAY-688
=> PROJQUAY-688 - set qui-gon as release

data/appr_model/package.py
Fixes https://issues.redhat.com/browse/PROJQUAY-762
=> Make sure to filter deleted repositories from app registry list queries

data/model/test/test_user.py, data/model/user.py
Fixes https://issues.redhat.com/browse/PROJQUAY-760
=> Make sure to immediately delete federated login links on user delete

Dockerfile.rhel7
https://issues.redhat.com/browse/PROJQUAY-778
=> PROJQUAY-778 - update quay-3.3 Dockerfile

deploy/openshift/quay-app.yaml
=> quay-app template - update apiVersions and remove default readOnly

deploy/openshift/quay-app.yaml
(already in master)
this PR makes the deployment run using the already added ServiceAccount.
=> run quay deployment with ServiceAccount

CHANGELOG.md
https://issues.redhat.com/browse/PROJQUAY-774
=> PROJQUAY-774 - changelog

data/model/repositoryactioncount.py, data/model/test/test_repositoryactioncount.py
Also adds a new test for this query
=> Fix the lookup query for RAC

data/cache/__init__.py
Add a config option for configuring whether to pre-disconnect from the
DB before making a memcache call
=> Adds a pre-disconnect option to memcache

data/userfiles.py
Fixes https://issues.redhat.com/browse/PROJQUAY-808
=> Fix serving of local user files

endpoints/api/test/test_trigger_analyzer.py, endpoints/api/trigger_analyzer.py
Fixes https://issues.redhat.com/browse/PROJQUAY-825
=> Fix display of robots when setting up a build trigger

CHANGELOG.md
https://issues.redhat.com/browse/PROJQUAY-849
=> PROJQUAY-849 - sprint release 'solo'

CHANGELOG.md, endpoints/api/test/test_trigger_analyzer.py, endpoints/api/trigger_analyzer.py
Fixes https://issues.redhat.com/browse/PROJQUAY-825
(cherry picked from commit eb54c545c6700378053d8e0222f2eca7361c9fdd)
=> Fix display of robots when setting up a build trigger (#470)

CHANGELOG.md
https://issues.redhat.com/browse/PROJQUAY-849
Change version back to "master"
=> PROJQUAY-849 - changelog version to master

conf/init/02_get_kube_certs.py
=> Decode b64 bytes to str when reading kube secret

.github/PULL_REQUEST_TEMPLATE.md
**Issue:** https://issues.redhat.com/browse/PROJQUAY-872
**Docs:** none
**Details:** Updating pull-request template to better reflect the required information for releases.
------
Docs: Detailed description of changes necessary to docs.projectquay.io. Examples would be addition of config.yaml, indication of UI changes and screenshot impact, and changes in …
=> PROJQUAY-872 - update pull-request template

endpoints/api/logs.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-883
**Docs:** 
**Testing:** 
**Details:**
=> PROJQUAY-883: Abort on invalid date range for logs api

config_app/config_endpoints/api/superuser.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-850
**Changelog:** Fixed: config app export's clair security.pem
**Docs:** none
**Testing:** Enable security scanner and assign new key
**Details:** python3 related
------
Docs: Detailed description of changes necessary to docs.projectquay.io. Examples would be addition of config.yaml, indication of UI changes and screenshot impact, and changes in …
=> PROJQUAY-850 - correct export of security.pem

buildman/templates/cloudconfig.json
/usr/share/pki/ca-trust-source/anchors does not have anything to copy
over to the container.
/etc/pki/ca-trust-source/anchors has the required system certs/trust.
**Docs:** 
**Testing:** 
**Details:** 
------
Docs: Detailed description of changes necessary to …
=> Update host's mounted cert directory

buildman/manager/ephemeral.py
**Docs:** 
**Testing:** 
**Details:** 
------
Testing: Detailed description …
=> Try to remove the redis key if when scheduling build it already exists

app.py, workers/repomirrorworker/repomirrorworker.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-906
**Docs:** none
**Details:** 
Update to use latest pydevd debug package (pydevd_pycharm).
------
Testing: …
=> PROJQUAY-906 - update pydevd package

endpoints/api/logs.py, endpoints/api/test/test_logs.py
**Docs:** 
**Testing:** 
**Details:** 
------
Testing: Detailed description …
=> Add missing flask import + add logs date range test

test/clients/clients_test.py
Must now be run from the quay root directory with PYTHONPATH=.
**Issue:** None
**Changelog:** None
**Docs:** None
**Testing:** This is a test suite
**Details:** Fix the clients test suite for Python 3
=> Fix clients test for Python 3

config_app/config_util/k8saccessor.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-916
**Docs:** 
**Testing:** 
**Details:** 
------
Testing: Detailed description of how to test changes manually. This section …
=> Decode secret's bytes to str before writing to file

requirements.txt
Changes include various Python3 compatibility fixes.
**Issue:** https://issues.redhat.com/browse/PROJQUAY-923
**Docs:** 
**Testing:** 
**Details:** 
Rebase boto to include changes made after the last release (2.49.0)
https://github.com/quay/boto
------
Docs: Detailed description of changes necessary to docs.projectquay.io. Examples would be addition of config.yaml, indication of UI …
=> Rebase the boto forked to include the non-released changes

data/model/oci/manifest.py
Catch IntegrityError from the other inserts as well, to ensure we handle
duplicate rows
Further addresses https://issues.redhat.com/browse/PROJQUAY-915
**Issue:** https://issues.redhat.com/browse/PROJQUAY-915
**Changelog:** None
**Docs:** None
**Testing:** Further Jib testing
=> Further fixes for duplicate manifest pushing

data/users/externalldap.py, endpoints/api/robot_models_pre_oci.py, test/test_ldap.py, util/test/test_validation.py, util/validation.py
**Issue:** 
- https://issues.redhat.com/browse/PROJQUAY-934
- https://issues.redhat.com/browse/PROJQUAY-939
**Docs:** 
**Testing:** 
**Details:** 
------
Testing: Detailed description of …
=> Fix ldap user login

storage/swift.py, storage/test/test_swift.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-941
**Docs:** 
**Testing:** 
**Details:** 
------
Testing: Detailed description of how to test changes manually. This section …
=> PROJQUAY-941 - Initialize the swift retry count correctly so that it is never None

data/secscan_model/secscan_v4_model.py, data/secscan_model/test/test_secscan_v4_model.py
If we get an invalid manifest when indexing, we now mark the manifest
as invalid for security indexing
Fixes https://issues.redhat.com/browse/PROJQUAY-949
=> Mark invalid manifests in Secscan V4

buildman/component/buildcomponent.py, buildman/manager/ephemeral.py, buildman/manager/executor.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-974
**Docs:** 
**Testing:** 
**Details:** 
------
Testing: Detailed description of how to test changes manually. This section …
=> Builder handles empty job on component

conf/init/nginx_conf_create.py, conf/nginx/nginx.conf.jnj
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1027
none
**Docs:** 
none
**Testing:** 
none
**Details:** 
Old code
=> PROJQUAY-1027 - remove nginx 'use_old_certs'

CHANGELOG.md
**Issue:** https://issues.redhat.com/browse/PROJQUAY-996
**Docs:** none
**Details:** 
Update version name in CHANGELOG.md
=> PROJQUAY-996 - vader version

docs/getting_started.md
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1109
docs/getting_started.md
**Docs:** 
**Testing:** 
**Details:** 
Added a section on how to configure mysql.
=> Updated Getting Started with mysql instructions

static/directives/robot-credentials-dialog.html
**Issue:** https://issues.redhat.com/browse/PROJQUAY-844
**Docs:** 
**Testing:** 
**Details:**
=> Rename dialog's "Robot Token" to "Robot Account"

test/test_secscan.py, util/secscan/v4/api.py, util/secscan/v4/clair-v4.openapi.json, util/secscan/v4/fake.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1108
**Changelog:** Update the Clair client for use with `4.0.0-rc.3`.
**Docs:** N/a
**Testing:** N/a
**Details:** Update the OpenAPI definitions and client API paths.
=> Update Clair Client (PROJQUAY-1108)

README.md
Removed bugbash details from README.md
**Docs:** 
**Testing:** 
**Details:**
=> Removed bugbash info from README.md

data/secscan_model/secscan_v4_model.py, data/secscan_model/test/test_secscan_v4_model.py, util/secscan/v4/api.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1079
**Docs:** 
**Testing:** 
Confirm that when quay sends manifests to clair that it cannot parse, that the row in db is updated to -2 and not rescanned further.
**Details:** 
A helm repo was being pushed to clair with an empty layer array. Clair responds w/ a 400/BadRequest. Treat this now as an indication that clair _cannot_ scan this and should not retry. A further check was added to prevent empty layers from being sent to begin with.
=> PROJQUAY-1079 - do not rescan bogus manifests

config.py, util/config/schema.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1139
**Docs:** none
**Testing:** 
Upgrade or otherwise run a new version of quay and confirm can login through browser.
**Details:** 
Token name required to be specified
=> PROJQUAY-1139 - set CSRF token name

external_libraries.py
Fix merged cherry-picked commit from f9249d8b
=> Fix merged cherrypicked commit from f9249d8b

requirements-osbs.txt
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1134
**Docs:** none
**Testing:** full regression
**Details:** 
Created requirements-osbs.txt which has requirements.txt plus dependent packages.
https://github.com/release-engineering/cachito/blob/master/docs/pip.md
=> PROJQUAY-1134 - update python requirements

buildman/orchestrator.py, buildman/test_orchestrator.py
- Various fixes to bugs/expected exceptions/orchestrator expiration/...
- Uses threads instead of asyncio to publish/watch events
- Add extra client connection options
- Add interface unit tests
**Issue:**https://issues.redhat.com/browse/PROJQUAY-1168
=> Update build orchestrator for new buildman

buildman/build_token.py, buildman/test_build_token.py
Implements generation and verification of build tokens.
Flow:
- Buildman take build from queue
- Buildman bootstrap a worker with a _registration_ token
- Worker registers build using the _registration_ token
- Buildman returns a _job_ token containing the buildpack
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1171
=> Implements JWT build tokens

quay-entrypoint.sh
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1150
**Changelog:** no
**Docs:** no
**Testing:** no
**Details:** 
Add `repomirror-nomigrate` entrypoint for use by operator.
=> PROJQUAY-1150 - add no-migrate mirror entrypoint

static/directives/set-repo-permissions.html, static/js/directives/ui/set-repo-permissions.js
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1227
**Changelog:** Show all available repository when setting permission for robot account when there's more than 100 repos available.
**Testing:** 
- Create org
- Create more than 100 repos in org
- Create org robot
- Try and set repo permission for created robot -> **all repos should be available to set**.
**Details:**
=> Show all available repository when setting permission for robot account

Dockerfile, Dockerfile.centos7.osbs, Dockerfile.osbs, Dockerfile.rhel8, app.py, buildman/builder.py, buildman/manager/executor.py, buildman/server.py, buildman/templates/cloudconfig.json, conf/init/nginx_conf_create.py, conf/nginx/nginx.conf.jnj, conf/nginx/server-base.conf.jnj
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1255
**Docs:** 
**Testing:** 
**Details:**
=> PROJQUAY-1255 grpc nginx ssl

buildman/manager/executor.py, buildman/templates/cloudconfig.json
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1255
- Missing key / syntax fixes in ignition cloud config template introduced in https://github.com/quay/quay/pull/603.
**Docs:** 
**Testing:** 
**Details:**
=> PROJQUAY-1255 - Json + jinja syntax fix in the ignition cloud config template

CHANGELOG.md, config.py, util/config/configutil.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1177
none
**Docs:** 
none
**Testing:** 
Confirm images and changelog appear in UI
**Details:** 
Downstream branding
=> PROJQUAY-1177 - add branding to 3.4.0

static/js/directives/ui/repository-events-table.js
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1344
- Angular will now sanitize `notification.title` before writing its contents to the DOM. This will prevent XSS attacks.
**Docs:** 
**Testing:** 
**Details:** 
------
=> PROJQUAY-1344

static/js/directives/ui/repository-events-table.js
(cherry picked from commit 55eafe8)
Issue: https://issues.redhat.com/browse/PROJQUAY-1344
#613
corrected merge conflict
=> PROJQUAY-1344 - cherry-pick

endpoints/api/repoemail.py
(cherry picked from commit 91c7088eddce1b469d87d24ad6168936117b8fca)
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1366
https://github.com/quay/quay/pull/614
=> PROJQUAY-1366

buildman/manager/ephemeral.py, buildman/manager/executor.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1376
Allow the build manager to requeue (if allowed) if the requests to the executors' api return a non-200 response.
**Docs:** 
**Testing:**
=> PROJQUAY-1376 - Handle non 200 api response from executors

buildman/manager/ephemeral.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1376
Correct indentation in `try` block introduced in 8da8df5
**Docs:** 
**Testing:** 
**Details:**
=> Fix mis-indentation introduced in 8da8df5

buildman/buildmanagerservicer.py, buildman/jobutil/buildjob.py, buildman/manager/ephemeral.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1382
- Correctly overwrite/update the job's expiration on heartbeat
- Log formatting fixes
- Return True/False on successful/failed append_build_log, respectively.
- Fix log number check + CachedTag grpc message field name
**Docs:** 
**Testing:** 
**Details:**
=> PROJQUAY-1382 - Various small buildman fixes

buildman/buildmanagerservicer.py, buildman/jobutil/buildjob.py, buildman/manager/ephemeral.py
- #622 
- #624 
- 
**Docs:** 
**Testing:** 
**Details:**
=> Cherrypicks #622 + #624 into Redhat 3.4 branch

.travis.yml, CHANGELOG.md
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1352
none
**Docs:** 
upcoming PR
**Testing:** 
none
**Details:** 
none
=> PROJQUAY-1352 - update changelog

storage/swift.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1391
- Cherry pick 1391 fix into redhat 3.4 branch
**Docs:** 
**Testing:** 
**Details:** 
------
=> PROJQUAY-1391 (#637) - Cherry Pick into 3.4

buildman/orchestrator.py
Cherrypick from #639 
**Docs:** 
**Testing:** 
**Details:**
=> Allow build canceller to set keys in orchestrator (#639)

requirements-nover.txt, requirements-osbs.txt, requirements.txt
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1406
- Removes autobahn from dependencies
**Docs:** 
**Testing:** 
**Details:**
=> Remove autobahn package

buildman/orchestrator.py, buildman/qemu-coreos/start.sh, buildman/templates/cloudconfig.json
Cherrypick #639  and #642 
**Docs:** 
**Testing:** 
**Details:**
=> Cherrypick bb0381f and 64df754

buildman/templates/cloudconfig.json, buildman/templates/dockersystemd.json
Cherrypick #645
**Docs:** 
**Testing:** 
**Details:**
=> Cherrypick fb88294

buildman/manager/ephemeral.py, buildman/manager/executor.py, buildman/templates/cloudconfig.json
See:
- https://docs.docker.com/engine/security/certificates/
- https://github.com/containers/image/pull/594/files
**Docs:** 
**Testing:** 
**Details:**
=> Copy the certs needed to allow the clients (docker or podman) to operate on self signed registries

buildman/manager/ephemeral.py, buildman/manager/executor.py, buildman/templates/cloudconfig.json
=> Cherrypick d4aa9d5

buildman/templates/cloudconfig.json
- Fix syntax error in template
**Docs:** 
**Testing:** 
**Details:**
=> fix-missing-comma

buildman/templates/cloudconfig.json
=> d4aa9d5 and 4819119

CHANGELOG.md
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1420
=> PROJQUAY-1420 - changelog

buildman/manager/executor.py
Fixes exception raised for referencing variable before assignment.
=> Fix Default Value for Build Manager Hostname

buildman/manager/executor.py
=> Cherry Pick e71ded9f

buildman/manager/ephemeral.py
=> Cherripick 6578618

Dockerfile.osbs
**Issue:** https://issues.redhat.com/browse/PROJQUAY-980
Update Dockerfile.osbs with downstream 3.4.0 changes
**Docs:** 
none
**Testing:** 
none
**Details:** 
This is the Dockerfile used in OSBS pipelines
=> PROJQUAY-980 - update downstream Dockerfile

buildman/manager/ephemeral.py
=> Cherrypick b28965c

notifications/notificationevent.py, static/css/directives/repo-view/repo-panel-tags.css, static/css/directives/ui/manifest-feature-view.css, static/css/directives/ui/manifest-vulnerability-view.css, static/directives/manifest-feature-view.html, static/directives/manifest-vulnerability-view.html, static/directives/repo-view/repo-panel-tags.html, static/js/directives/repo-view/repo-panel-tags.js, static/js/directives/ui/manifest-vulnerability-view.js, static/js/services/external-notification-data.js, util/secscan/__init__.py, util/secscan/v4/clair-v4.openapi.json, workers/securityscanningnotificationworker.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-586
Removed Defcon1 severity filter from the dropdown menu for notifying on package vulnerability
**Docs:** 
**Testing:** 
**Details:**
=> PROJQUAY-586 - Remove Defcon1 severity from Quay

config.py, util/config/configutil.py, workers/repomirrorworker/__init__.py
=> Cherrypick 55e11c2

tox.ini
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1549
Update the tox.ini to support the latest format changes from tox-docker v2.0.0
- Update tox.ini to support tox-docker v2.0.x
**Docs:** 
**Testing:** 
- Run CI
**Details:**
=> PROJQUAY-1549 - Update container name + specify image in tox.ini

CHANGELOG.md
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1556
3.4.1 changelog
=> PROJQUAY-1556 - 3.4.1 changelog

README.md
Updates readme with a link to the Quay Operator for visibility.
=> Add Quay Operator to Readme

config.py, util/config/configutil.py, util/config/schema.py, workers/repomirrorworker/__init__.py
=> Cherrypick 63386d9

CHANGELOG.md
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1614
3.4.2 release notes
=> PROJQUAY-1614 - 3.4.2 release notes

package-lock.json, package.json
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1655
- Update npm package-lock file. Follow up to (#681)
**Docs:** 
**Testing:** 
**Details:**
=> PROJQUAY-1655 update npm package lock

endpoints/secscan.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1613
cherry-pick
=> PROJQUAY-1613 - secscan/_backfill_status math (#688)

CHANGELOG.md
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1699
3.4.3 changelog
=> PROJQUAY-1699 - 3.4.3 changelog

health/healthcheck.py, requirements-nover.txt, requirements-osbs.txt, requirements.txt, storage/cloud.py, storage/swift.py, storage/test/test_cloud_storage.py, storage/test/test_cloudfront.py, util/config/validators/test/test_validate_storage.py, util/registry/filelike.py, workers/test/test_exportactionlogsworker.py
* Migrate storage from boto2 to boto3
- https://issues.redhat.com/browse/PROJQUAY-835
- https://issues.redhat.com/browse/PROJQUAY-922
**TESTING** ->
---
=> Update storage to boto3

requirements-osbs.txt, requirements.txt
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1754
Bump PyYAML to 5.3.1 to address CVE-2020-1747
**Docs:** 
n/a
**Testing:** 
n/a
**Details:** 
n/a
=> address CVE-2020-1747

avatars/avatars.py, config.py, util/config/schema.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1284
- Set default hash for gravatar to be sha256
- Added FEATURE_FIPS flag
**Docs:** 
**Testing:** 
**Details:** 
------
=> PROJQUAY-1284

CHANGELOG.md, config.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1489
**Details:** 
downstream branding
=> PROJQUAY-1489 - 3.5.0 downstream branding

Dockerfile
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1586
none
**Docs:** 
none
**Testing:** 
Confirm metrics going to prometheus as expected
**Details:** 
Updated for newer jquery
=> PROJQUAY-1586 - update pushgateway

buildman/builder.py
=> chore: import missing logging.config module (#706)

storage/cloud.py
Cherrypick  0722e6ee5e3ace5f88adbc69899b9fba6d9550e
=> format: remove extra comma from s3 connect_kwargs (#709)

storage/cloud.py
PROJQUAY-1803
(cherry picked from commit fd2746827a48100d5aba7316b20724d25104817e)
=> storage: fix us-east-2 S3 direct pull (#714)

data/model/gc.py, data/model/storage.py, util/metrics/prometheus.py, workers/gc/gcworker.py, workers/namespacegcworker.py, workers/repositorygcworker.py
Add counters for the number of resources deleted by the gc worker and
the repository gc worker.
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1802
**Example**:
=> gc: add metrics for deleted resources

data/model/gc.py, data/model/storage.py, util/locking.py, util/metrics/prometheus.py, workers/gc/gcworker.py, workers/namespacegcworker.py, workers/queueworker.py, workers/repositorygcworker.py
Cherrypicks:
- 3b94cda7
- f774e4c6
- 90f9ef95
=> Quayio cherrypick gc fixes

util/locking.py, workers/queueworker.py, workers/test/test_exportactionlogsworker.py
=> lock: reuse redis client when creating locks (PROJQUAY-1872) (#741)

util/locking.py, workers/blobuploadcleanupworker/blobuploadcleanupworker.py, workers/gc/gcworker.py, workers/globalpromstats/globalpromstats.py, workers/logrotateworker.py, workers/namespacegcworker.py, workers/repositorygcworker.py
Cherrypick:
- c12654bf
Add missing imports not included from cherrypicking  c12654bf
=> Quayio cherrypick for redis cache

config.py, data/cache/__init__.py, data/cache/cache_key.py, data/cache/impl.py, data/cache/test/test_cache.py, data/registry_model/registry_oci_model.py, data/registry_model/test/test_interface.py, endpoints/appr/models_cnr.py, endpoints/appr/registry.py, endpoints/v2/catalog.py, endpoints/v2/test/test_blob.py
Adds a configuration option to modify the cache expiry timeout for ModelCache objects
=> modelcache: Add config for cache ttl to keys (PROJQUAY-1878)

data/model/blob.py, data/model/image.py, data/model/oci/blob.py, data/model/oci/manifest.py, data/model/storage.py, data/model/test/test_gc.py, data/model/test/test_image_sharing.py, data/registry_model/manifestbuilder.py, data/registry_model/registry_oci_model.py, data/registry_model/test/test_blobuploader.py, data/registry_model/test/test_interface.py, endpoints/api/image.py, endpoints/verbs/__init__.py, tools/orphans.py, util/secscan/analyzer.py, util/verifyplacements.py
Readd uploading column changes by reverting #776
=> Revert "quayio:  revert uploading col changes (#776)"

data/model/blob.py, data/model/image.py, data/model/oci/blob.py, data/model/oci/manifest.py, data/model/storage.py, data/model/test/test_gc.py, data/model/test/test_image_sharing.py, data/registry_model/manifestbuilder.py, data/registry_model/registry_oci_model.py, data/registry_model/test/test_blobuploader.py, data/registry_model/test/test_interface.py, endpoints/api/image.py, endpoints/verbs/__init__.py, tools/orphans.py, util/secscan/analyzer.py, util/verifyplacements.py
This reverts commit f03482414908bf3209515bfed3b03ff60d50ce47.
NOTE: Re-revert this when ready to deploy
=> Revert "Revert "quayio:  revert uploading col changes (#776)" (#777)"

deploy/openshift/quay-app.yaml
Updating from canary deployment to a blue-green style deployment
=> deployment: Change canary to blue deployment (PROJQUAY-1896)

deploy/openshift/quay-app.yaml
Follow up on #754 This adds blue deployment to the quayio branch
=> Add blue deployment to Quayio branch (PROJQUAY-1896)

.github/workflows/CI.yaml, Dockerfile, _init.py, conf/init/certs_install.sh, external_libraries.py, test/registry/conformance_tests.py
Cherrypicks dockerfile improvements from #659
=> dockerfile: refactor dockerfile (PROJQUAY-1997)

data/model/blob.py
Decouples blob upload and db row creation when uploading the empty
layer. This avoids the transaction blocking on non-db/S3 related issues.
=> db: remove transaction from empty layer upload (PROJQUAY-1946)

CHANGELOG.md, config.py
=> chore: 3.4.5 release (PROJQUAY-2005)

CHANGELOG.md
=> chore: 3.5.2 release (PROJQUAY-1940)

CHANGELOG.md
=> release: Release v3.4.6 (PROJQUAY-2103)

package-lock.json, package.json
Bump url-parse version to 1.4.3
=> build: update node url-parse to 1.4.3 (PROJQUAY-1749)

requirements-osbs.txt, requirements.txt
=> build: update python pillow version (PROJQUAY-1520)

buildman/qemu-coreos/start.sh
Reference correct filename in start.sh
=> buildman: fix vm image name in startup script (PROJQUAY-2120)

CHANGELOG.md
=> chore: 3.5.3 release (PROJQUAY-2144)

package-lock.json
=> build: update package-lock.json (PROJQUAY-1749)

CHANGELOG.md
=> build: release v3.5.4

endpoints/common.py
=> quayio: python2 syntax fix

deploy/openshift/quay-recovery-endpoint.yaml
Adds openshift manifests for deployment for the recovery endpoint
=> deploy: cherrypick c6dcf and d37e3 for recovery endpoint (PROJQUAY-970)

CHANGELOG.md, config.py
Downstream build changes for release
=> release: v3.6.0 release changes (PROJQUAY-1861)

data/cache/__init__.py, data/cache/impl.py, data/cache/redis_cache.py, data/cache/test/test_cache.py, requirements-dev.txt, requirements-nover.txt, requirements-osbs.txt, requirements.txt
Adds support to use redis in cluster mode when using redis instead of
memcached for caching
=> cache: add support for redis cluster mode (PROJQUAY-2101)

data/cache/__init__.py, data/cache/impl.py, data/cache/redis_cache.py, data/cache/test/test_cache.py, requirements-nover.txt, requirements.txt
Adds support to use redis in cluster mode when using redis instead of
memcached for caching.
=> cache: add support for redis cluster mode (PROJQUAY-2101) (#810)

requirements-osbs.txt, requirements.txt
=> python: bump pillow to 8.3.1 (PROJQUAY-2250)

requirements-osbs.txt
Needed for dep closure downstream
=> chore: return zope.interface to requirements-osbs.txt (PROJQUAY-1535)

notifications/notificationmethod.py, tools/emailinvoice.py, tools/sendconfirmemail.py, tools/sendresetemail.py, util/fips.py, util/useremails.py
Patch CRAM-MD5 function to allow usage under FIPS but enforce TLS
=> fips: enforce smtp tls (PROJQUAY-1804)

CHANGELOG.md
Updated CHANGELOG.md to add v3.5.6 release
=> doc: Add v3.5.6 release version (PROJQUAY-2345)

docs/docker-local-dev.md
Update doc to include instructions to setup dev environment
=> Update doc to include dev environment setup instructions

oauth/oidc.py
Dennying requests when impersonated
=> Quay.io: Catching requests from impersonated principals

data/migrations/env.py, oauth/oidc.py
Reference: https://alembic.sqlalchemy.org/en/latest/api/config.html#configuration
=> migration: configure logging in alembic's env.py (PROJQUAY-2412)

Dockerfile
- Fix symlink in upstream dockerfile
=> dockerfile: Update symlink in upstream dockerfile (PROJQUAY-2550)

Dockerfile, local-dev/Dockerfile
Backport - https://github.com/quay/quay/pull/885
=> fix: pin setuptools to version 57

CHANGELOG.md
=> Updated changelog for v3.5.7

CHANGELOG.md
change version to alpha pre-release for v3.5.8
=> doc: change version to alpha pre-release for v3.5.8

emails/orgrecovery.html, package-lock.json, package.json
Cherrypicks:
- d81efe2f
- 66373020
=> email: fix org recovery link in email (PROJQUAY-2589)

.github/CONTRIBUTING.md, README.md, static/js/pages/contact.js, util/config/configdocs/schema.html, util/config/schema.py
https://issues.redhat.com/browse/PROJQUAY-2066
=> Document irc channels move to libera.chat

.github/workflows/CI.yaml, Dockerfile, requirements-osbs.txt, requirements.txt
Aplly patch by kleesc, see https://github.com/quay/quay/commit/c7c4c0dc4ca9681482a100a831950355634c3b61
=> fix: update funcparserlib and oci check

static/directives/header-bar.html
Follow-up to PROJQUAY-2340. Make the same change for the mobile template.
=> ui: fix csrf issue when login in with SSO on mobile (PROJQUAY-2340)

data/secscan_model/secscan_v4_model.py, data/secscan_model/test/securityinformation.json, data/secscan_model/test/securityinformation_withenrichments.json, static/directives/manifest-vulnerability-view.html, static/js/directives/ui/manifest-vulnerability-view.js, util/secscan/__init__.py
Backporting https://github.com/quay/quay/pull/887 and https://github.com/quay/quay/pull/937 from master
=> Backport: Quayio nvd data UI improvements 

data/model/gc.py, data/model/test/test_gc.py, data/model/test/test_repository.py
Make sure to remove orphaned storage blob when purging a repository's
uploadedblob.
=> gc: remove orphaned storage on repository purge (PROJQUAY-2313)

scripts/app_sre_post_deploy_rhel7.sh
=> Update BASE_IMAGE in post deploy script (PROJQUAY-2372)

deploy/openshift/quay-py3-app.yaml
THis makes the deployment more readable via app-sre automation
=> deploy: Seperate py3 deployment manifests (PROJQUAY-2374)

scripts/app_sre_post_deploy_rhel7.sh
Use quayio-py3-backup as the name for py3 images
=> Update backup base image name (PROJQUAY-2372)

deploy/openshift/quay-py3-app.yaml
Set tag explicitly in the SaaS file
=> deploy: Update syslog image tag(PROJQUAY-2374)

Dockerfile, Dockerfile.deploy
=> Update config tool version

Dockerfile.osbs
Updates quay.io to use latest RHEL
=> deploy:Update quay.io to use latest RHEL image (PROJQUAY-2874)

app.py
This for debugging issues with ALB in quay.io
=> debug: Log X-Forwaded-For for requests (PROJQUAY-2883)

util/ipresolver/test/test_ipresolver.py
Update the resolver's mmdb file.
TODO: We should find a way to update this at a somewhat regular interval, similar to the aws-ip-ranges file.
=> ipresolver: update country mmdb (PROJQUAY-3031)

util/ipresolver/test/test_ipresolver.py
=> Cherrypick b9557d14

data/buildlogs.py
The linter complains when a line is able to be condensed
but is expanded.
=> formatting: Update code to obey the linter (PROJQUAY-0)

endpoints/api/test/test_trigger_analyzer.py, endpoints/api/trigger_analyzer.py
Signed-off-by: Hank Donnay <hdonnay@redhat.com>
=> trigger_analyzer: fix confusing print (PROJQUAY-1995)

buildman/orchestrator.py
=> Revert "buildman: add connect parameters to build orchestrator client"

Dockerfile, Dockerfile.deploy
Adds more logging to debug config tool build validation issues
=> config: Update config-tool version to v0.1.10 (PROJQUAY-3125)

test/test_ldap.py
Add test for user defined filter formatting.
=> ldap: add test for user filter (PROJQUAY-2766)

buildman/manager/executor.py
Filter the completed or failed jobs from the kubernetes api requests.
=> buildman: fix kubernetes not returning correct running count (PROJQUAY-3169)

buildman/manager/ephemeral.py, buildman/manager/executor.py
Additional option allowing for Quay builds to leverage Podman directly in Openshift.
=> buildman: Add kubernetesPodman build option (PROJQUAY-3052)

data/secscan_model/secscan_v4_model.py, data/secscan_model/test/test_secscan_v4_model.py
Currently it is possible that Clair returns a state that Quay doesn't
know about and the previous logic will save this as a completed
manifest.
=> secscan: Don't save result if returned state is unknown (PROJQUAY-2939)

data/model/team.py, data/model/test/test_team.py
=> [redhat-3.6] teams: admin team deletion (PROJQUAY-2080)

data/migrations/env.py
This causes issues with where the DB user or password can have special chars
=> db: remove url unqoute from migration logic (PROJQUAY-3266)

storage/cloud.py
Handle S3 `cn-north-1`'s endpoint, which has a com.cn TLD.
=> storage: handle cn-north-1 region (PROJQUAY-3082)

buildman/manager/ephemeral.py
With the previous 15 sec hard-coded value, some build could
sporadically expire before having the time to boot start instance and
make the registration rpc call. Change the default to 30 sec, and make
it configurable.
=> buildman: configurable build job registration timeout (PROJQUAY-3280)

data/secscan_model/datatypes.py
Follow-up to [1133](https://github.com/quay/quay/pull/1133)
=> secscan: clairv2 - fix datatype bug (PROJQUAY-3279)

static/js/services/image-metadata-service.js, static/js/services/vulnerability-service.js
Image has been depricated in quay hence removing this from the UI as well
=> ui: Depricate getImageCommand in security UI (PROJQUAY-3284)

data/secscan_model/secscan_v4_model.py
Currently we randomly scan for entries to be indexed. This could take a
long time if we have a lot of unindexed images. Ideally, we want to
priortize scanning of newer images before we go to the old ones.
This PR creates a smaller batch of size `batch_size` from
`max_id - batch_size` to `max_id` to priortize scanning
those
=> sescan: prioritize scanning new pushes (PROJQUAY-3287)

data/database.py
An InterfaceError is raised by PyMySQL after a connection has
been idle for longer than the MySQL database's interactive_timeout
setting. This can happen on some workers without work to be done for a
long time. This causes Peewee to be unable to reuse its stale
connection. Instead, the peewee connection needs to be closed, and a
new session opened with MySQL.
=> database: retry connections on stale MySQL connections (PROJQUAY-3303)

config.py
This hack is for handling possible MySQL closing idle
connections. Peewee/pymysql's will try to reuse the existing
connection after the MySQL server has already closed it, which will
return an InterfaceError. AFAIK, there isn't a way to actually test
for a a stale connection without actually running a query. Closing the
connection before the transaction forces peewee/pymysql to reopen a
new session to MySQL. This should only applies to non-registry
workers, as the registry workers use a pool by default, and shouldn't
have this issue. Follow-up to 58b06572 (#1148).
=> database: force close existing non-pooled connections before transaction (PROJQUAY-3303)

requirements.txt
this backports changes from various commits in an attempt to fix e2e tests.
=> [redhat-3.6] update requirements, matching master's updates

util/migrate/allocator.py
This is useful for debugging which block is being processed
=> secscan: Log start and end index of block in clair (PROJQUAY-3287)

data/secscan_model/secscan_v4_model.py
for debugging quay.io clair issues
=> secscan: log manifest ID when indexing (PROJQUAY-3287)

config.py
This reverts commit 005b903345e03270e88b6762f0644d8d79cca432.
=> Revert "Revert 24b3c153 and 7cdb88b5 (#1158)"

data/secscan_model/secscan_v4_model.py
Adds a new iterator for exclusively scanning
recent manifests
=> secscan: scan recent manifests in addition to regular backfill  (PROJQUAY-3287)

bill-of-materials.json, requirements-osbs.txt, requirements.txt
=> chore: Remove unused dep (PROJQUAY-3437)

data/model/__init__.py, data/registry_model/registry_proxy_model.py, data/registry_model/test/test_registry_proxy_model.py, endpoints/v2/__init__.py
also check if the org is within its quota limits before caching an image
from the upstream registry.
=> registry_proxy_model: count repository size when caching images (PROJQUAY-3464)

data/secscan_model/secscan_v2_model.py, data/secscan_model/secscan_v4_model.py, data/secscan_model/test/test_secscan_interface.py, data/secscan_model/test/test_secscan_v4_model.py, requirements-osbs.txt, requirements.txt, setup.py, util/locking.py, workers/securityworker/securityworker.py
This reverts commit 9d89b6fa47dec4ab0c182d88f56772303adc09a6.
=> Revert "secscan: add a global lock on security worker runs (PROJQUAY-3501) (#1226)"

data/database.py, data/migrations/versions/b43b44996c26_increase_proxy_cache_config_creds_maxlen.py
fixes [PROJQUAY-3521](https://issues.redhat.com//browse/PROJQUAY-3521)
=> data: increase max len for proxy cache config credentials

config.py, endpoints/oauth/login.py, util/config/schema.py
- Add FEATURE_EXPORT_COMPLIANCE to config schema
- Add call to export compliance service during OAuth workflow when feature is enabled
=> quayio: Add export compliance service to Red Hat SSO (PROJQUAY-2056)

requirements-osbs.txt, requirements.txt
* Adds `packaging` for `oslo.utils`
=> chore: Add packaging dependency (PROJQUAY-2175)

requirements-osbs.txt, requirements.txt
* Update required dependency for `requests`
=> chore: Add charset-normalizer (PROJQUAY-2175)

workers/securityworker/securityworker.py
Fix missing GlobalLock import.
=> secscan: fix missing import (PROJQUAY-3501)

conf/supervisord.conf.jnj
Fix cleanup worker command in supervisord template.
=> conf: fix supervisord chunk worker template

data/secscan_model/secscan_v4_model.py
Correctly check for the end of the manifest table, for when the worker
needs to start over. Also add missing token to lock key.
=> secscan: fix check for end of table (PROJQUAY-3501)

config.py, endpoints/oauth/login.py, util/config/schema.py
This reverts commit 247fec3b0511eef3f5dc58633051a5dab4bc0f2e.
=> Revert "quayio: Add export compliance service to Red Hat SSO (PROJQUAY-2056) (#1239)"

static/js/directives/ui/quota-management-view.js
=> Quota UI: Display Error when decimal values entered from UI (PROJQUAY-3627)

data/model/namespacequota.py, endpoints/api/namespacequota.py, static/directives/quota-management-view.html, static/js/directives/ui/quota-management-view.js, static/js/pages/org-view.js, static/js/pages/superuser.js, static/partials/org-view.html
=> Quota: Show system default on UI when quota configuration for the org is not set (PROJQUAY-3518)

static/js/directives/ui/quota-management-view.js
=> Quota UI: Show message that System wide default cannot be removed from an organization (PROJQUAY-3658)

Dockerfile
- Bump config tool tag from v0.1.11 to v0.1.12
=> editor: Bump config tool to v0.1.12 (PROJQUAY-3593)

data/model/__init__.py, data/model/namespacequota.py
Raising exception when entered quota size is too big. Error is propagated on the UI as:
=> Quota: Raising exception when entered quota size is too big (PROJQUAY-3702)

endpoints/web.py, templates/oauthorize.html
Add the `state` parameter to the oauth permissions page
that's rendered when asking user for permission.
=> auth: Add state to the oauthorize page (PROJQUAY-3648)

static/css/directives/ui/quota-management-view.css, static/directives/quota-management-view.html, static/js/directives/ui/quota-management-view.js
=> Quota UI: Fix quota input value (PROJQUAY-3691)

data/fields.py, data/model/blob.py, data/registry_model/blobuploader.py, endpoints/v2/blob.py, endpoints/v2/manifest.py, endpoints/v2/tag.py
Addresses some uncaught exceptions seen on Sentry.
=> chore: various small changes to fix exceptions, remove unused code

buildman/manager/executor.py
Update kubernetesPodman builders default image with the production image.
=> builders: Set default kubernetesPodman image (PROJQUAY-3586)

workers/securityworker/securityworker.py
Having only one worker index recent manifest doesn't keep up with the
rate new manifests being pushed, given the time it takes for an index
request to complete. Adding the option to bypass the global lock
allows for more workers, but also increase the chance of duplicate work.
=> secscan: add option to skip recent manifest batch lock (PROJQUAY-3501)

data/secscan_model/secscan_v4_model.py
Split the work of indexing the recent manifests iterator into multiple
batches. This can reduce how often duplicate work happens when
allowing multiple workers to work on the same chunk of the table.
=> secscan: split the recent manifest chunk of work into multiple batch (PROJQUAY-3501)

endpoints/oauth/login.py, oauth/loginmanager.py, oauth/services/rhsso.py
- Created a RHSSO class
- Put export compliance logic in class override
=> compliance: Move export screening to RHSSO class (PROJQUAY-2056)

oauth/loginmanager.py, oauth/services/rhsso.py, oauth/test/test_loginmanager.py
- Add test for RHSSOOAuthService class
=> sso: Add test for RHSSO OAuth service (PROJQUAY-2056)

oauth/services/rhsso.py
- Change mount path from  $CONF_DIR to $CONF_DIR/stack
=> sso: Update mount path for export compliance certificate (PROJQUAY-2056)

oauth/services/rhsso.py
- Fix debug statement to print stringified json
=> sso: Fix debug statement (PROJQUAY-2056)

oauth/services/rhsso.py
- Handle 400 status code gracefully as users in stage sso may not necessarily exist in compliance backend
=> sso: Handle edge case for stage sso only users (PROJQUAY-2056)

buildman/manager/executor.py, oauth/services/rhsso.py
Currently imagePullPolicy is set to IfNotPresent. This will ignore updates to the builder image.
=> builders: Set imagePullPolicy to always (PROJQUAY-3507)

oauth/services/rhsso.py
- Check for additional error messages returned from export screen
=> rhsso: Add checks for e-mail blocked in export screen (PROJQUAY-2056)

Dockerfile, requirements.txt
=> localdev: Add support for running on M1 macs (PROJQUAY-3870)

buildman/manager/ephemeral.py
Currently builds do not send notifications on success or failure. Adding calls to send out those notifications.
=> builders: Send notifications on build completion (PROJQUAY-3614)

endpoints/web.py, oauth/provider.py, requirements-dev.txt, templates/oauthorize.html, test/test_endpoints.py
Fixes an issue where the code param is not passed to the app redirect
URI if the user has not authorized the app before
=> oauth: Fix oauth code flow when user has not authorized the app (PROJQUAY-3648)

buildtrigger/customhandler.py, data/logs_model/elastic_logs.py, image/docker/schema2/config.py, image/oci/config.py, test/test_ldap.py, util/dockerfileparse.py
mostly invalid escape sequences
=> fix several warnings

static/directives/repo-view/repo-panel-info.html, static/js/directives/repo-view/repo-panel-info.js
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
I don't know how to render this to make sure it looks ok, could someone check to see how this renders?
=> GUI: Show how to pull an image using podman pull (PROJQUAY-3948)

data/model/repository.py
Method for calculating size of repo joined on repo id instead of manifest id. This causes deleted manifests to be counted. Change updates call to join on manifest id.
=> quota: Fix join on caching repo size (PROJQUAY-3889)

_init.py, app.py, notifications/__init__.py, notifications/notificationmethod.py, singletons/app.py, singletons/avatar.py, singletons/config.py, singletons/mail.py, singletons/workqueues.py, util/config/provider/testprovider.py, util/config/validators/validate_ssl.py, util/jinjautil.py, util/ssl.py, workers/notificationworker/notificationworker.py, workers/queueworker.py, workers/worker.py
Reduce notificationworker's memory usage from 110 MB to 75 MB.
=> Reduce memory usage

data/model/namespacequota.py
Fixing database call which will now match on manifest vs repository to correctly calculate org size.
=> quota: Fix calculating org size (PROJQUAY-3889)

app.py, data/database.py, data/logs_model/__init__.py
This fixes notificationworker as it no longer depends on `app.py`.
=> Initialize database and log_model on their import

Makefile, docker-compose.yaml
This allows to use podman for local development:
```
make local-dev-up DOCKER=podman
make local-dev-down DOCKER=podman
```
=> Allow to override docker and docker-compose location

app.py, features/__init__.py, util/generatepresharedkey.py, util/registry/replication.py, util/useremails.py, workers/expiredappspecifictokenworker.py, workers/gc/gcworker.py, workers/globalpromstats/globalpromstats.py, workers/manifestbackfillworker.py, workers/namespacegcworker.py, workers/queuecleanupworker.py, workers/repomirrorworker/__init__.py, workers/repositoryactioncounter.py, workers/repositorygcworker.py
Where it is possible, instead of importing app, import only required packages.
=> Replace app with singletons.config and workqueues

conf/nginx/server-base.conf.jnj, storage/azurestorage.py, storage/test/test_azure.py
- Increase nginx send timeout on blobs endpoints
- Reduce Azure blob block size
TODO: Spread block uploads over multiple worker threads.
=> storage: optimize large azure chunked upload (PROJQUAY-3753)

Makefile, docs/getting-started.md, scripts/pre-commit
Automatically formats python files before commit
=> dev: Add pre-commit script to run black (PROJQUAY-4039)

static/js/services/plan-service.js
- When a user clicks 'Start Free Trial', they should be redirected to the user billing page after signing in with RHSSO
=> quayio: Redirect user to billing page when starting free trial (PROJAUAY-4130)

.github/workflows/CI.yaml, requirements.txt
It could help avoid #1428 (and maybe #1429).
=> Check that requirements.txt has all dependencies

CHANGELOG.md
Signed-off-by: GitHub <noreply@github.com>
Co-authored-by: HammerMeetNail <HammerMeetNail@users.noreply.github.com>
=> chore: v3.7.4 changelog bump (https://issues.redhat.com/browse/PROJQUAY-4050) (#1446)

config.py, endpoints/api/organization.py, endpoints/api/user.py, features/__init__.pyi, test/test_api_usage.py, test/testconfig.py, util/config/schema.py
Add Feature flag to whitelist users from recaptcha security check(PROJQUAY-3697)
=> Add Feature flag to whitelist users from recaptcha security check (PROJQUAY-3697)

static/directives/plans-display.html
This is to prevent fradulent accounts and bots from creating
large accounts
=> ui: Remove trial from larger plans for quay.io (PROJQUAY-4197)

templates/oauthorize.html
Fixes issue where we are not passing the response type to oauth
with dangerous scopes
=> oauth: fix oauth token generation when using dangerous scopes (PROJQUAY-4042)

CHANGELOG.md
* cherry pick of https://github.com/quay/quay/pull/1466
=> chore: Update changelog to 3.6.9

auth/test/test_registry_jwt.py, buildman/build_token.py, buildman/manager/ephemeral.py, endpoints/v2/test/test_blob.py, endpoints/v2/test/test_manifest.py, endpoints/v2/test/test_manifest_pullthru.py, endpoints/v2/v2auth.py, oauth/test/test_oidc.py, requirements.txt, storage/downloadproxy.py, test/test_endpoints.py, test/test_external_jwt_authn.py, test/test_oauth_login.py, util/secscan/blob.py, util/security/jwtutil.py, util/tufmetadata/api.py
* Update PyJWT to resolve CVE-2022-29217
=> deps: Bump PyJWT (PROJQUAY-4229)

util/secscan/v4/api.py
* Additional cleanup from #1471
=> deps: Remove unused decode (PROJQUAY-4267)

Makefile
Example:
```
TESTS="data/registry_model/test/test_registry_proxy_model.py" make test_postgres
```
`TESTS` is set to ./ by default
=> Makefile: use variable to tell postgres test target which tests to run

endpoints/web.py
needed for the new UI to read quay config
=> api: add OPTIONS method to /config request (PROJQUAY-4276)

CHANGELOG.md
Signed-off-by: GitHub <noreply@github.com>
Signed-off-by: GitHub <noreply@github.com>
Co-authored-by: HammerMeetNail <HammerMeetNail@users.noreply.github.com>
=> [redhat-3.7] v3.7.6 Changelog Bump

data/registry_model/registry_proxy_model.py, data/registry_model/test/test_registry_proxy_model.py, data/registry_model/test/testdata.py
fixes [PROJQUAY-3976](https://issues.redhat.com//browse/PROJQUAY-3976)
=> registry: correctly bump tag expiration when tag changes upstream (PROJQUAY-3976)

endpoints/v1/registry.py, endpoints/v2/blob.py, endpoints/v2/test/test_blob.py, storage/azurestorage.py, storage/basestorage.py, storage/cloud.py, storage/distributedstorage.py, storage/fakestorage.py, storage/swift.py, storage/test/test_cloudfront.py
This is to corelate the a user with CDN traffic in CloudFront logs
=> storage: Add username field to requests on CloudFront (PROJQUAY-3511)

proxy/__init__.py
Fixes [PROJQUAY-4362](https://issues.redhat.com/browse/PROJQUAY-4362).
=> bug: Fix schema discovery on basic auth (PROJQUAY-4362)

conf/nginx/server-base.conf.jnj
* Updates nginx config to not append port
=> ui: Remove port on proxy redirect (PROJQUAY-4390)

static/directives/header-bar.html, static/js/directives/ui/header-bar.js
* Hide toggle when on signin page
=> ui: Don't show UI toggle on signin page (PROJQUAY-4402)

.github/workflows/cut-release.yml
* Cherry pick of https://github.com/quay/quay/pull/1526
=> [redhat-3.7] ci: Update release workflow to use new release action (PROJQUAY-4444)

conf/nginx/server-base.conf.jnj
* Resolves issue where oauth failed when trying to login with the new UI toggled
=> auth: Resolve 404 on oauth (PROJQUAY-4420)

conf/nginx/server-base.conf.jnj
* Add remaining `url_prefix` from web.py
=> net: Update nginx to support all old UI endpoints (PROJQUAY-4420)

data/model/oci/tag.py, data/registry_model/registry_proxy_model.py, data/registry_model/test/test_registry_proxy_model.py
Adds ability to automatically prune images from a proxy org when it's quota limit is reached 
- The tags marked for delete are eventually garbage collected by a GC worker
=> proxy: Evict LRU images when proxy cache org reaches limit (PROJQUAY-3063)

Dockerfile
* Updates golang versin to `1.17.12`
=> deps: Bump golang (PROJQUAY-4556)

requirements.txt
* Addresses [PROJQUAY-4504](https://issues.redhat.com//browse/PROJQUAY-4504) and [PROJQUAY-4499](https://issues.redhat.com//browse/PROJQUAY-4499)
=> deps: Bump deps (PROJQUAY-4504)

data/registry_model/registry_proxy_model.py
Fix proxy-cache overflow quota limit when pulling same image 
=> Fix proxy-cache overflow quota limit when pulling same image (PROJQUAY-4670)

buildman/manager/ephemeral.py
This adds a metric that calculates the time a build job spends in the queue.
=> buildman: add SLO metric for time spent in queue for build jobs (PROJQUAY-4487)

data/users/__init__.py, endpoints/api/organization.py, endpoints/api/prototype.py, endpoints/api/robot.py, endpoints/api/team.py
When FEATURE_SUPERUSERS_FULL_ACCESS is set, grant superusers org admin permissions:
- [PROJQUAY-4687](https://issues.redhat.com//browse/PROJQUAY-4687)
- [PROJQUAY-4690](https://issues.redhat.com//browse/PROJQUAY-4690)
- [PROJQUAY-4693](https://issues.redhat.com//browse/PROJQUAY-4693)
- [PROJQUAY-4697](https://issues.redhat.com//browse/PROJQUAY-4697)
- [PROJQUAY-4701](https://issues.redhat.com//browse/PROJQUAY-4701)
=> superusers: grant superusers additinonal org permissions (PROJQUAY-4687)

endpoints/v2/v2auth.py
Prevent restricted users' from automatically creating repos or orgs on v2 auth requests ([PROJQUAY-4706](https://issues.redhat.com//browse/PROJQUAY-4706), [PROJQUAY-4708](https://issues.redhat.com//browse/PROJQUAY-4708)).
=> users: prevent creating repo on push for restricted users (PROJQUAY-4706)

endpoints/api/__init__.py, endpoints/api/build.py, endpoints/api/logs.py, endpoints/api/manifest.py, endpoints/api/mirror.py, endpoints/api/permission.py, endpoints/api/repoemail.py, endpoints/api/repository.py, endpoints/api/repositorynotification.py, endpoints/api/repotoken.py, endpoints/api/tag.py, endpoints/api/trigger.py
When FEATURE_SUPERUSERS_FULL_ACCESS is set, grant superusers repository permission registry-wide.
- [PROJQUAY-4708](https://issues.redhat.com//browse/PROJQUAY-4708)
- [PROJQUAY-4709](https://issues.redhat.com//browse/PROJQUAY-4709)
- [PROJQUAY-4718](https://issues.redhat.com//browse/PROJQUAY-4718)
- [PROJQUAY-4719](https://issues.redhat.com//browse/PROJQUAY-4719)
- [PROJQUAY-4720](https://issues.redhat.com//browse/PROJQUAY-4720)
=> users: when FEATURE_SUPERUSERS_FULL_ACCESS is set, grant superusers repository permissions (PROJQUAY-4708)

data/users/__init__.py, endpoints/v2/v2auth.py, util/config/superusermanager.py, util/config/test/test_superusermanager.py
Prevent creating namespaces/orgs on pushes (CREATE_NAMESPACE_ON_PUSH) if user is restricted.
=> users: prevent CREATE_NAMESPACE_ON_PUSH is restricted (PROJQUAY-4702)

buildman/manager/ephemeral.py
Added a counter metrics to track total number of build jobs and total number of failed builds. These can be used to calculate the build success % in Grafana.
=> buildman: add SLO metric that calculates build success rate (PROJQUAY-4486)

Dockerfile, scripts/app_sre_build_deploy_rhel7.sh
Analytics will be added only when building for quay.io
=> ui: Add script for adobe analytics for quay.io (PROJQUAY-4582)

static/js/directives/ui/header-bar.js, templates/base.html
This will be used for usage analytics on quay.io
=> ui: Add script for adobe analytics for quay.io in angular UI (PROJQUAY-4582)

templates/base.html
the variable `feature_set` has features with the `FEATURE_` prefix removed. Fix the jinja check for this
=> ui: Remove FEATURE_UI_V2 from analytics scripts (PROJQUAY-4582)

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
Add panels for registry api metrics along with a heatmap for build queue duration.
=> deploy: update grafana dashboard (PROJQUAY-4484)

Dockerfile, scripts/app_sre_build_deploy_rhel7.sh
The new UI will dynamically add the analytics scripts
=> ui: Remove add_analytics script from Dockerfile (PROJQUAY-4582)

config.py, util/config/schema.py
Adds feature flag to restrict the repository settings feature.
=> ui: Repository settings feature flag (PROJQUAY-4565)

Dockerfile
=> Revert "chore: Update Dockerfile to reduce size of image (PROJQUAY-4837)"

Dockerfile
=> chore: Update Dockerfile to reduce size of image (PROJQUAY-4837)

requirements.txt
This should fix the build error:
error: invalid command 'bdist_wininst'
=> chore: Bump pbr

oauth/services/rhsso.py
This is to debug errors from export compliance in case of incorrect matching for usernames
=> login: Add subject in debug logs for export compliance (PROJQUAY-4844)

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
Adds panel for tracking build success %
=> deploy: add panel to dashboard (PROJQUAY-4486)

data/registry_model/datatypes.py, data/secscan_model/secscan_v4_model.py, endpoints/v2/blob.py, util/metrics/prometheus.py
Add histogram metric that calculates time taken to get security scan results after pushing image to quay.
=> secscan: add metric for scan results (PROJQUAY-4488)

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
add two new panels for tracking security scan results on slo dashboard
=> deploy: update slo dashboard (PROJQUAY-4488)

data/registry_model/datatypes.py, data/secscan_model/secscan_v4_model.py, endpoints/v2/blob.py, util/metrics/prometheus.py
=> Revert "secscan: add metric for scan results (PROJQUAY-4488)"

oauth/services/rhsso.py
Fixes an issue where the export compliance exception gets caught as a generic OAUTH exception
=> login: Re-raise the export compliance exception on RHSSO (PROJQUAY-4844)

endpoints/oauth/login.py
Pass the correct arg quay_username
=> login: Re-raise the export compliance exception on RHSSO (prod) (PROJQUAY-4844)

static/partials/error-view.html
Remove quay-devel from export compliance emails
=> login: Use dedicated mailing list for export compliance email (PROJQUAY-4844)

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
re-arrange dashboard based on received feedback
=> deploy: change slo dashboard (PROJQUAY-5026)

data/registry_model/datatypes.py, data/secscan_model/secscan_v4_model.py, util/metrics/prometheus.py, util/secscan/v4/api.py
re-adding metric for initial scan results duration, updated bucket range to better reflect timing
=> secscan: add scan metric (PROJQUAY-4488)

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
add panel to track push/pull monitor across all regions and update query for secscan metric
=> deploy: change push-pull panel (PROJQUAY-4956)

data/appr_model/channel.py
Partial cherry-pick of https://github.com/quay/quay/pull/1389
=> Cherry-pick fix for IS NULL check

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
panel calculating quay_secscan_result_duration_seconds as minutes, change to seconds.
=> deploy: fix units in slo panel (PROJQUAY-4956)

deploy/openshift/quay-py3-app.yaml, deploy/openshift/quay-py3-cloudflare-app.yaml
disable min replicas check for staging environment where we only have a single replica
=> deploy: add annotation for disabling DVO check (PROJQUAY-3680)

deploy/openshift/quay-py3-deploy-template.yaml
Allows for creation of separate services for multiple deployments.
=> deploy: Allow for dynamic service names (PROJQUAY-5103)

Dockerfile
I have update the comments for grpc installation on IBMZ. comments has been added keeping in mind that once wget is removed from dockerfile , necessary changes to be done for grpc installation on IBMZ
=> Updated comments for grpc installation on IBMZ

data/billing.py, endpoints/api/subscribe.py, requirements.txt
Update stripe payment behavior to 'default_incomplete'.
=> billing: update default subscription payment behavior (PROJQUAY-5129)

requirements.txt
Partial backport of https://github.com/quay/quay/pull/1644.
=> chore: backport requirements.txt changes (PROJQUAY-4777)

.github/workflows/oci-distribution-spec.yaml, Dockerfile
* switch to ubi-minimal to avoid old urllib3
* bump deps to remediate CVEs
* formatting
* remove unnused dependency jsonpickle
* bump wheel
* Wait longer until the container is running
* Remove noise from health check output
* Explicitly set timezone name
=> build(deps): reduce CVEs in dependencies and runtime environment (PROJQUAY-4777)

util/config/schema.py, util/request.py
multiple CORS Origin are required for integration with console.redhat
=> api: Allow setting multiple CORS_ORIGIN (PROJQUAY-5213)

config.py, data/secscan_model/secscan_v4_model.py, features/__init__.pyi, notifications/notificationevent.py, util/config/schema.py
On a new push, send a notification if vulnerabilities are found after indexing.
=> secscan: send notifications for new indexes (PROJQUAY-4659)

data/logs_model/__init__.py, data/logs_model/logs_producer/splunk_logs_producer.py, data/logs_model/splunk_logs_model.py, data/logs_model/test/test_splunk.py, endpoints/decorated.py, requirements.txt, static/directives/logs-view.html, static/js/directives/ui/logs-view.js, util/config/schema.py
This PR adds Splunk logging model to forward user action logs to a splunk instance
=> PROJQUAY-4993: Allow action logs to be forwarded to Splunk

scripts/app_sre_build_deploy_frontend.sh, web/src/libs/axios.ts, web/src/routes/PluginMain.tsx
Adds app-sre-build-deploy-frontend.sh script
=> build: Add build scripts for quay.io frontend (PROJQUAY-5229)

deploy/openshift/quayio-frontend-deploy-template.yaml
Adds the quayio-frontend-deploy-template.yaml for console dot deployment
=> build: Add template for deploying quayio frontend in console (PROJQUAY-5229)

web/src/components/NewUserEmptyPage.tsx, web/src/components/modals/CreateNewUser.tsx, web/src/components/modals/NewUserConfirmation.tsx, web/src/resources/AuthResource.ts, web/src/resources/UserResource.ts, web/src/routes/PluginMain.tsx
Contains temporary modal until mocks are ready.
=> Quay UI: Creating new username for accounts that login via SSO (PROJQUAY-5289)

web/src/libs/axios.ts, web/src/routes/NavigationPath.tsx, web/src/routes/PluginMain.tsx, web/src/routes/RepositoriesList/RepositoriesList.tsx, web/src/routes/StandaloneMain.tsx, web/webpack.plugin.js
Depending on the where the plugin is deployed use stage or prod quay.io
=> ui: Use the correct endpoint for plugin (PROJQUAY-3203)

local-dev/stack/config.yaml
Noticed we have RH SSO config in config.yaml for local-dev.
=> Remove stage.quay.io SSO Config

web/src/libs/utils.ts, web/webpack.dev.js
Set to 'N/A' if last modified is not retured from the API
=> ui: fix last modified date on repo list (PROJQUAY-5408)

web/cypress/e2e/repository-details.cy.ts, web/src/resources/TagResource.ts, web/src/routes/RepositoryDetails/Tags/DeleteModal.tsx, web/src/routes/RepositoryDetails/Tags/TagsToolbar.tsx
Adds additional option in new UI `Permanently Delete` for individual alive tags where the tag's `lifetime_end_ms` will be set outside the time machine window.
=> ui: Adding option to permanently delete tags past time machine window (PROJQUAY-5303)

endpoints/api/subscribe.py
Fix to allow non-stripe user changing to free plan in order to convert from user to organization.
=> billing: allow changing subscription on empty stripe_id (PROJQUAY-5413)

web/src/routes/PluginMain.tsx, web/src/routes/StandaloneMain.tsx
updates to new survey at https://7qdvkuo9rkj.typeform.com/to/fuxVxdWM
=> ui: update survey link to new survey (PROJQUAY-5432)

web/src/atoms/RobotAccountState.ts, web/src/hooks/UseDeleteRobotAccount.ts, web/src/resources/RobotsResource.ts, web/src/routes/RepositoriesList/RobotAccountKebab.tsx, web/src/routes/RepositoriesList/RobotAccountsList.tsx
Fix search in bulk delete modal for robot accounts page
=> ui: Fix search in bulk delete for robot accounts (PROJQUAY-5355)

web/src/libs/utils.ts, web/src/routes/PluginMain.tsx, web/src/routes/RepositoryTagRouter.tsx, web/src/routes/StandaloneMain.tsx
Thanks to @jamestalton for his input here :)
=> UI: Fixing repository name for nested repos (PROJQUAY-5446)

static/js/directives/ui/manage-user-tab.js, static/js/directives/ui/repo-list-table.js, static/js/pages/org-view.js, static/js/pages/superuser.js
Removing the rounding and adding fixed decimal place to give a more accurate quota size.
=> ui: updating quota size format (PROJQUAY-5471)

endpoints/api/superuser.py, endpoints/api/superuser_models_interface.py, endpoints/api/superuser_models_pre_oci.py, endpoints/api/test/test_superuser.py, static/directives/page-controls.html, static/js/directives/ui/page-controls.js, static/js/pages/superuser.js, static/partials/super-user.html
Paginates calls to the `/v1/superuser/organizations/` endpoint. Allows the superuser organization list to load when quota is enabled.
=> superuser: paginating superuser organization list (PROJQUAY-4297)

data/logs_model/logs_producer/splunk_logs_producer.py, data/logs_model/splunk_logs_model.py, data/logs_model/test/test_splunk.py, util/config/schema.py
This PR adds SSL cert support or splunk and additional test coverage
=> logs: Add SSL cert support and test coverage for splunk logging (PROJQUAY-4993)

data/migrations/versions/8cf90670bf38_add_permanently_delete_tag_log_entry_.py, endpoints/api/tag.py, initdb.py, static/js/directives/ui/logs-view.js
Now logging the permanently delete tag as a usage log.
=> api: add permanently delete tag usage log (PROJQUAY-5496)

web/src/components/header/QuayHeader.tsx, web/src/routes/Signin/Signin.tsx
=> ui: adding null check on dark logo

.github/workflows/CI-nightly.yaml
Added Nightly CI to run all test [ Unit , E2E , Registry ] on multi arch i.e. s390x , amd64 , ppc64le
=> Added nightly ci

.github/workflows/CI-nightly.yaml
Support for IBM/Z
- Updated Secret **SSH_USER** to **ZVSI_SSH_USER**
- Added Status of ZVSI after Creation of Instance
=> chore: updated secrets and added status of ZVSI

data/model/namespacequota.py, static/js/pages/user-view.js, static/partials/user-view.html
User namespaces can now view the quota total.
=> ui: displaying quota totals on user namespaces (PROJQUAY-5581)

.github/workflows/CI-nightly.yaml
Increased the timer for instance to come up properly on zvsi
Updated zone and subnet to another region
removed the success check in zvsi deletion. now it will be invoked in all scenario
=> ZVSI Cleanup process updated with new region details in Nightly CI

.github/workflows/build-and-publish.yaml
Updated checks for the status of ZVSI and Post Clean-Up ZVSI
- [Tested with Build and Publish in Private repo](https://github.com/ksdeekshith/quay/actions/runs/5342439901)
- Updated Names of ZVSI instances based on **Github run_id** to create different instances for each run
- Added check for the **status of ZVSI** states [ failed, running, not created] 
- Added check to **Clean the ZVSI** based on the state of ZVSI
=> chore: Updated checks for s390x ZVSI builder

Dockerfile
=> build(deps): bump config-tool to v0.1.19

storage/cloud.py, storage/test/test_cloudfront.py
This is causing issues with config editor where it configure CloudFront provider because of the required override param
=> storage: make cloudfront_distribution_org_overrides optional (PROJQUAY-5788)

Dockerfile
=> build(deps): bump config-tool to v0.1.20 (PROJQUAY-5109)

requirements.txt
=> Revert "[redhat-3.9] chore: Bump PyYAML"

requirements.txt
=> Revert "[redhat-3.9] chore: Use stable Cython"

requirements.txt
=> Revert "chore: Use stable Cython"

requirements.txt
=> Revert "chore: Bump PyYAML"

Dockerfile
=> build(deps): bump config-tool to v0.1.21

web/cypress/e2e/repository-details.cy.ts, web/src/atoms/AlertState.ts, web/src/components/labels/EditableLabel.tsx, web/src/components/labels/Labels.tsx, web/src/components/labels/LabelsEditable.tsx, web/src/components/labels/LabelsReadOnly.tsx, web/src/hooks/UseTagLabels.ts, web/src/resources/ErrorHandling.ts, web/src/resources/NotificationResource.ts, web/src/resources/RepositoryResource.ts, web/src/resources/TagResource.ts, web/src/routes/Alerts.tsx, web/src/routes/RepositoryDetails/Tags/TagsActions.tsx, web/src/routes/RepositoryDetails/Tags/TagsActionsAddTagModal.tsx, web/src/routes/RepositoryDetails/Tags/TagsActionsLabelsModal.tsx, web/src/tests/fake-db/data/tag/labels.ts
- Adds the edit labels tag operation
- Adds editable variant to labels component
=> ui: adding edit labels tag operation (PROJQUAY-5290)

data/secscan_model/secscan_v4_model.py
In Clair 4.7, an API field documented to have version information in no particular format may URL encode it. This change attempts to decode and read a known field that contains the "fixed" version. If that fails, the value will be passed through, as it is now.
Closes: [PROJQUAY-5886](https://issues.redhat.com//browse/PROJQUAY-5886)
=> secscan_model: attempt urldecoding `fixed_in_version` (PROJQUAY-5886)

util/removelocation.py
- Gracefully handle errors that are thrown during remove location script
- This should handle scenarios where the location is not found or not provided, as well as other error cases
=> georep: Add error handling for remove location script (PROJQUAY-5878)

.github/workflows/build-and-publish.yaml, Dockerfile, requirements.txt
This PR fixes issue with s390x builds
=> [redhat-3.9] chore: pull changes for s390x from master

data/secscan_model/secscan_v4_model.py
Currently the error message doesn't align with the operation.
=> secscan: update error from secscan delete (PROJQUAY-0000)

util/metrics/prometheus.py, util/secscan/v4/api.py
Also fixes typo in function call.
=> secscan: fix metrics to track all request types to secscan service (PROJQUAY-3839)

web/cypress/e2e/repository-details.cy.ts, web/src/hooks/UseTags.ts, web/src/resources/TagResource.ts, web/src/routes/RepositoryDetails/Tags/DeleteModal.tsx, web/src/routes/RepositoryDetails/Tags/TagsActions.tsx, web/src/routes/RepositoryDetails/Tags/TagsActionsAddTagModal.tsx, web/src/routes/RepositoryDetails/Tags/TagsList.tsx, web/src/routes/RepositoryDetails/Tags/TagsTable.tsx, web/src/routes/RepositoryDetails/Tags/TagsToolbar.tsx
=> ui: adding delete tag by row (PROJQUAY-5933)

config-tool/pkg/lib/fieldgroups/database/database.go, config-tool/pkg/lib/fieldgroups/database/database_validator.go
Cherry-pick of https://github.com/quay/config-tool/pull/214
=> feat(config-tool): add SSL client authentication (PROJQUAY-2417)

web/webpack.plugin.js
=> ui: Fix public path for console dot (PROJQUAY-5938)

workers/quotaregistrysizeworker.py, workers/test/test_quotaregistrysizeworker.py
Worker fails to start because of wrong import + adding test.
=> quota: fixing registry total worker failing to start (PROJQUAY-6010)

static/partials/error-view.html
New email used by export hold team
=> compliance: Update export hold email (PROJQUAY-6024)

data/cache/cache_key.py, data/database.py, data/secscan_model/__init__.py, data/secscan_model/interface.py, data/secscan_model/secscan_v4_model.py, data/secscan_model/test/test_secscan_v4_model.py, endpoints/api/secscan.py
uses modelcache to for caching clair security report responses
=> secscan: Cache clair vuln reports (PROJQUAY-6057)

deploy/openshift/quayio-frontend-deploy-template.yaml
This changes the frontend resource name so that the correct paths will be generated
=> frontend: Change frontend name so that correct paths will be generated (RHCLOUD-28385)

requirements.txt
=> Revert "build(deps): bump peewee from 3.13.1 to 3.16.3 (#2323)"

web/src/routes/RepositoryDetails/RepositoryDetails.tsx
Adds missing props for create robot account modal
=> ui: Add missing props for create robot acocunt modal (PROJQUAY-6184)

web/cypress/e2e/default-permissions.cy.ts, web/cypress/e2e/org-list.cy.ts, web/cypress/test/quay-db-data.txt, web/src/components/modals/BulkDeleteModalTemplate.tsx, web/src/components/modals/RobotRepositoryPermissions.tsx, web/src/components/toolbar/DropdownCheckbox.tsx, web/src/hooks/UseDefaultPermissions.ts, web/src/resources/DefaultPermissionResource.ts, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/DefaultPermissionsList.tsx, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/DefaultPermissionsToolbar.tsx, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/DeleteDefaultPermissionKebab.tsx, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/createPermissionDrawer/CreatePermissionDrawer.tsx, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/createPermissionDrawer/CreateTeamModal.tsx, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/createTeamWizard/CreateTeamWizard.tsx
- Adds bulk delete for default permissions tab
- Also fixes a bug with select checkbox where multiple rows are selected when selecting one of the row since default permissions can have same repository creator
=> ui: Add bulk deletion for default permissions (PROJQUAY-6093)

local-dev/stack/config.yaml, web/cypress/e2e/account-settings.cy.ts, web/cypress/e2e/autopruning.cy.ts, web/cypress/e2e/org-settings.cy.ts, web/cypress/fixtures/config.json, web/src/components/modals/GenerateEncryptedPasswordModal.tsx, web/src/components/modals/UserConvertConflictsModal.tsx, web/src/hooks/UseAlerts.ts, web/src/hooks/UseConvertAccount.ts, web/src/hooks/UseCreateClientKey.ts, web/src/hooks/UseCurrentUser.ts, web/src/hooks/UseOrganizationSettings.ts, web/src/hooks/UseUpgradePlan.ts, web/src/resources/OrganizationResource.ts, web/src/resources/UserResource.ts, web/src/routes/OrganizationsList/Organization/Organization.tsx, web/src/routes/OrganizationsList/Organization/Tabs/Settings/BillingInformation.tsx, web/src/routes/OrganizationsList/Organization/Tabs/Settings/CLIConfiguration.tsx, web/src/routes/OrganizationsList/Organization/Tabs/Settings/GeneralSettings.tsx, web/src/routes/OrganizationsList/Organization/Tabs/Settings/Settings.tsx
- This PR adds settings pages to the organization and user organization pages.
- Admin users can edit their preferences, billing, and organization type
- Updated cypress version to address bug https://github.com/cypress-io/cypress/issues/25397
=> ui: Add organization and user account settings (PROJQUAY-4553)

web/src/components/modals/robotAccountWizard/AddToTeam.tsx, web/src/components/toolbar/FilterWithDropdown.tsx
=> ui: fixing RobotAccount AddToTeam console error (PROJQUAY-6233)

data/test/test_namespace_autoprune.py, web/src/routes/OrganizationsList/Organization/Tabs/Settings/AutoPruning.tsx
Validates correct input on auto-prune policy creation.
=> autoprune: validating input to autoprune policy (PROJQUAY-6230)

storage/cloudflarestorage.py
This is needed for correctly signing URLs for CloudFlare
=> storage: pass S3 region to S3Storage init (PROJQUAY-6375)

web/cypress/e2e/repository-state.cy.ts, web/src/hooks/UseRepositoryState.ts, web/src/resources/RepositoryResource.ts, web/src/routes/RepositoryDetails/Settings/RepositoryState.tsx, web/src/routes/RepositoryDetails/Settings/Settings.tsx
- Allow user to switch repository between normal, mirror, and read-only states
=> ui: Add form for repository state (PROJQUAY-5715)

web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/DefaultPermissionsList.tsx
Fix search for bulk delete default permission modal
=> ui: fix search for bulk delete default permission modal (PROJQUAY-6369)

deploy/openshift/quay-py3-deploy-template.yaml
Add connection pooling env variable ([PROJQUAY-5550](https://issues.redhat.com//browse/PROJQUAY-5550))
=> deploy: Add connection pooling env variable (PROJQUAY-5550)

deploy/openshift/quay-py3-app.yaml
this is used for quay.io deployment
=> deploy: add DB pooling to py3 template (PROJQUAY-5550)

web/cypress/e2e/org-list.cy.ts, web/cypress/e2e/repositories-list.cy.ts, web/cypress/e2e/teams-and-membership.cy.ts, web/cypress/test/quay-db-data.txt, web/src/hooks/UseTeams.ts, web/src/routes/OrganizationsList/Organization/Organization.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsAndMembershipList.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/ManageMembers/ManageMembersList.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/ManageMembers/ManageMembersToolbar.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/TeamsRoleDropDown.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/TeamsViewList.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/TeamsViewToolbar.tsx
Fix tab visibility for teams and membership
=> ui: fix tab visibility for teams and membership (PROJQUAY-6333)

web/cypress/e2e/default-permissions.cy.ts, web/cypress/e2e/teams-and-membership.cy.ts, web/src/components/EntitySearch.tsx, web/src/hooks/UseMembers.ts, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/createPermissionDrawer/CreatePermissionDrawer.tsx, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/createTeamWizard/AddTeamMember.tsx, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/createTeamWizard/AddTeamToolbar.tsx, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/createTeamWizard/CreateTeamWizard.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/ManageMembers/AddNewTeamMemberDrawer.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/SetRepoPermissionsModal/SetRepoPermissionForTeamModal.tsx, web/src/routes/RepositoryDetails/Settings/PermissionsAddPermission.tsx
Allows adding user from the dropdown in create team wizard:
=> ui: Allow adding user from create team wizard (PROJQUAY-6336)

deploy/openshift/quay-py3-app.yaml
- Remove cpu limits
- Add 'no cpu limits' annotations
=> quayio: Remove cpu limits (PROJQUAY-6440)

data/cache/cache_key.py, data/cache/impl.py, data/registry_model/interface.py, data/registry_model/registry_oci_model.py, data/registry_model/registry_proxy_model.py, data/registry_model/test/test_interface.py, endpoints/v2/manifest.py
=> Revert "api: add caching for get_repository method (PROJQUAY-6472)"

config.py, data/model/user.py, util/config/schema.py
* Fixed typo
* added ROBOTS_WHITELIST as without the ROBOTS_DISALLOW does not make sense
=> user(robots): disallow robot login and create 2nd (PROJQUAY-5968)

deploy/openshift/quay-py3-app.yaml
sets the number of registry workers in the primary deployment
=> deploy: update main deployment to add regitry worker count (PROJQUAY-6456)

static/js/directives/ui/header-bar.js
Removes the check that limits the UI toggle to RedHat users
=> ui: show UI toogle to all users in quay.io (PROJQUAY-6505)

web/cypress/e2e/breadcrumbs.cy.ts, web/cypress/test/quay-db-data.txt, web/src/components/breadcrumb/Breadcrumb.tsx
=> ui: breadcrumbs fix when org and repo names are identical (PROJQUAY-6504)

config-tool/pkg/lib/editor/js/core-config-setup/config-setup-tool.html, config-tool/pkg/lib/editor/js/core-config-setup/core-config-setup.js, config-tool/pkg/lib/shared/storage_validators.go, config-tool/pkg/lib/shared/structs.go
Adding config validation for the `IBMCloudStorage` option.
=> configtool: Adding validation for IBM Cloud Storage (PROJQUAY-6549)

static/js/directives/repo-view/repo-panel-tags.js
Currently, when the tag list contains multiple pages of manifest list tags and the user attempts to move forward through the pages the list would abruptly reset to page 1, preventing the user from viewing all the available tags. This was due to the `repositoryTags` Angular model being modified when the submanifests were being fetched, specifically [here](https://github.com/quay/quay/blob/master/static/js/directives/repo-view/repo-panel-tags.js#L513) and [here](https://github.com/quay/quay/blob/master/static/js/directives/repo-view/repo-panel-tags.js#L531). This caused the watch on `repositoryTags` to fire which rebuilds the list view and also resets the page to 1. 
This change modifies the `repositoryTags` watch to not run when the modification was done during the fetch of sub manifests …
=> ui: fixing tag list reset when rendering manifest lists (PROJQUAY-5793)

web/src/routes/RepositoryDetails/Builds/BuildHistory.tsx
resizes the avatar in the build history table
=> ui: adjusting size of avatar (PROJQUAY-6676)

config.py, image/docker/schema1.py, image/docker/schema2/list.py, image/docker/schema2/manifest.py, image/oci/descriptor.py, image/oci/index.py, image/oci/manifest.py, image/oci/test/test_oci_index.py, image/oci/test/test_oci_manifest.py, image/oci/test/testdata/__init__.py, image/shared/interfaces.py, image/shared/schemas.py, image/shared/schemautil.py, image/shared/types.py, util/config/schema.py
Allow manifests to be pushed with a artifactType and subject fields.
=> registry: allow pushing manifests with artifactType and subject fields (PROJQUAY-6673)

conf/nginx/server-base.conf.jnj, web/src/routes/NavigationPath.tsx
Adds breadcrumb to quay.io overview nav and updates nginx routes.
=> ui: add breadcrumbs for overview (PROJQUAY-5460)

web/cypress/e2e/builds.cy.ts
The date has passed making all repositories in the list stale and hiding them all, causing no components to be rendered.
=> ui: fixing build trigger test (PROJQUAY-6695)

.pre-commit-config.yaml, web/cypress/e2e/builds.cy.ts, web/cypress/fixtures/TestDockerfile, web/cypress/fixtures/build-triggers.json, web/cypress/fixtures/robots.json, web/src/components/FileUpload.tsx, web/src/components/toolbar/SearchTypes.ts, web/src/hooks/UseBuildTriggers.ts, web/src/hooks/UseBuilds.ts, web/src/hooks/UseRepository.ts, web/src/hooks/useRobotAccounts.ts, web/src/libs/dockerfileParser.ts, web/src/resources/BuildResource.ts, web/src/resources/RepositoryResource.ts, web/src/routes/RepositoryDetails/Builds/BuilTriggerViewCredentials.tsx, web/src/routes/RepositoryDetails/Builds/BuildHistory.tsx, web/src/routes/RepositoryDetails/Builds/BuildHistoryManuallyStartTriggerModal.tsx, web/src/routes/RepositoryDetails/Builds/BuildHistoryStartBuildModal.tsx, web/src/routes/RepositoryDetails/Builds/BuildHistoryStartBuildModalUploadDockerfile.tsx, web/src/routes/RepositoryDetails/Builds/BuildTriggerActions.tsx, web/src/routes/RepositoryDetails/Builds/BuildTriggers.tsx, web/src/routes/RepositoryDetails/Builds/Builds.tsx
Adds the ability for users to run builds via the Patternfly UI.
=> ui: run builds (PROJQUAY-6297)

web/src/routes/OverviewList/css/OverviewList.scss
Adds width and height to logo css so it shows up in console dot
=> ui: add width and height for logo (PROJQUAY-5460)

web/cypress/e2e/usage-logs.cy.ts, web/src/hooks/UseUsageLogs.ts, web/src/routes/OrganizationsList/Organization/Organization.tsx, web/src/routes/UsageLogs/UsageLogs.tsx, web/src/routes/UsageLogs/UsageLogsExportModal.tsx, web/src/routes/UsageLogs/UsageLogsGraph.tsx
Adds chart in usage log view for orgs and repos
=> ui: add chart for usage logs (PROJQUAY-6701)

data/users/__init__.py, data/users/externaloidc.py, endpoints/oauth/test/test_login.py, static/js/pages/team-view.js, web/cypress/e2e/team-sync.cy.ts, web/cypress/fixtures/config.json, web/cypress/fixtures/emptystate-team-members.json, web/cypress/fixtures/oidc-user.json, web/cypress/fixtures/teamsync-robots.json, web/cypress/fixtures/teamsync-team-members.json, web/cypress/fixtures/teamsynced-members-superuser.json, web/cypress/fixtures/teamsynced-members.json, web/cypress/fixtures/teamsyncorg.json, web/src/components/empty/Empty.tsx, web/src/components/modals/ConfirmationModal.tsx, web/src/components/modals/OIDCTeamSyncModal.tsx, web/src/hooks/UseMembers.ts, web/src/hooks/UseTeamSync.ts, web/src/resources/MembersResource.ts, web/src/resources/TeamSyncResource.ts, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/ManageMembers/ManageMembersList.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/ManageMembers/ManageMembersToolbar.tsx
- Added base class for OIDC Authentication
- UI to enable group synchronisation + option to enter OIDC group value
- API call to `/syncing` that inserts group config in `TeamSync` table
- adding read-only teams page
- display sync config
- option to remove team sync
=> ui: ui and initial scaffolding for OIDC auth (PROJQUAY-6298)

config-tool/pkg/lib/fieldgroups/distributedstorage/distributedstorage.go, config-tool/pkg/lib/shared/storage_validators.go, config-tool/pkg/lib/shared/structs.go, storage/__init__.py, storage/cloud.py
- Add STS authentication to s3
- Add STS validation to config tool
- PR automatically refreshes token on expiry
=> sts: Add STS support for S3 (PROJQUAY-6362)

web/cypress/e2e/team-sync.cy.ts, web/cypress/e2e/usage-logs.cy.ts, web/src/hooks/UseLogDescriptions.tsx, web/src/hooks/UseUsageLogs.ts, web/src/routes/UsageLogs/UsageLogs.tsx, web/src/routes/UsageLogs/UsageLogsGraph.tsx, web/src/routes/UsageLogs/UsageLogsTable.tsx, web/tsconfig.json
Adds a table for logs in the repository and organization settings. 
Screens:
https://github.com/quay/quay/assets/47163063/2b295614-a8b0-423e-a0c0-30fb653b8574
=> ui: add usage log table (PROJQUAY-6702)

endpoints/decorated.py, endpoints/test/test_request_redirect.py
Adds an error handler for RequestRedirect exceptions raised by werkzeug to reduce noise in sentry
=> endpoints: add error handler for RequestRedirect (PROJQUAY-6724)

web/cypress/e2e/repository-autopruning.cy.ts, web/src/routes/RepositoryDetails/Settings/RepositoryAutoPruning.tsx, workers/test/test_autopruneworker.py
- Adds more repository auto-prune tests 
- Fixes UI issue: when user is not an admin, the namespace autoprune policy under repository auto-prune policies tab shouldbe hidden
=> chore: Add auto-prune tests + fix namespace autoprune policy UI issue (PROJQUAY-6773)

web/cypress/e2e/builds.cy.ts, web/src/routes/RepositoryDetails/RepositoryDetails.tsx
Hides the build tab if the repo is not in `NORMAL` state.
=> ui: not displaying build tab when repo is mirror or readonly (PROJQUAY-6827)

web/src/hooks/UseLogDescriptions.tsx, web/src/routes/UsageLogs/UsageLogs.tsx, web/src/routes/UsageLogs/UsageLogsTable.tsx
Fixes:
- https://issues.redhat.com/browse/PROJQUAY-6781
- https://issues.redhat.com/browse/PROJQUAY-6783
- Also adds log description for proxy cache config which QE reported in the above jira
=> ui: add description for log kind autoprune policy (PROJQUAY-6781)

web/cypress/e2e/team-sync.cy.ts, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/ManageMembers/ManageMembersList.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/ManageMembers/ManageMembersToolbar.tsx
=> ui: rename directory sync to team sync (PROJQUAY-6880)

web/src/routes/OrganizationsList/Organization/Organization.tsx
Adds usage logs view to user namespace.
=> logs: enable logs for user namespace (PROJQUAY-6855)

data/migrations/versions/36cd2b747a08_team_sync_logs.py, endpoints/api/team.py, initdb.py, web/src/hooks/UseLogDescriptions.tsx
Add logging for enabling and disabling team sync.
=> logs: add action log for team sync enable/disable (PROJQUAY-6763)

data/readreplica.py
=> chore: fix type check in read replica (PROJQUAY-6397)

web/cypress/e2e/usage-logs.cy.ts, web/src/routes/UsageLogs/UsageLogs.tsx
Adds a button to the usage logs view that allows the user to toggle the log chart visibility.
=> logs: add button to hide/show logs (PROJQUAY-6826)

static/directives/signin-form.html, static/js/directives/ui/signin-form.js
=> ui: dont show username password signin when auth_type is oidc (PROJQUAY-6740)

web/cypress/e2e/repository-autopruning.cy.ts, web/src/routes/RepositoryDetails/Settings/RepositoryAutoPruning.tsx
=> ui: Add human readable autoprune policy method type (PROJQUAY-6918)

README.md
Adding the community meeting link to the readme.
=> readme: adding community meeting link (PROJQUAY-6925)

util/config/schema.py
fixing typo for DB_CONNECTION_POOLING
=> chore: fix typo (PROJQUAY-6397)

web/cypress/e2e/team-sync.cy.ts, web/cypress/fixtures/teamsynced-members.json, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/ManageMembers/ManageMembersList.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/ManageMembers/ManageMembersToolbar.tsx
=> ui: non org admins cannot remove team sync (PROJQUAY-6924)

app.py, data/users/__init__.py, data/users/externaloidc.py, endpoints/oauth/test/test_login.py, test/test_external_oidc.py, web/cypress/e2e/team-sync.cy.ts, web/cypress/fixtures/teamsync-azure.json, web/cypress/fixtures/teamsync-team-members.json, web/src/hooks/UseMembers.ts, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/ManageMembers/ManageMembersList.tsx
=> oidc: ask for group object id for azure oauth login (PROJQUAY-6917)

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
signalfx has moved on that new cluster recently
=> observability: move catchpoint_datasource to new cluster (PROJQUAY-7007)

web/cypress/e2e/team-sync.cy.ts, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/ManageMembers/ManageMembersList.tsx
=> ui: disable invited tab when team is synced (PROJQUAY-6831)

static/directives/manage-users-tab.html
=> ui: send recovery email option in superusers panel (PROJQUAY-7195)

endpoints/api/__init__.py, endpoints/api/logs.py, endpoints/api/namespacequota.py, endpoints/api/organization.py, endpoints/api/policy.py, endpoints/api/prototype.py, endpoints/api/repository.py, endpoints/api/team.py, endpoints/api/test/test_security.py, features/__init__.pyi
Allows superuser to have access to additional endpoints when the `FEATURE_SUPERUSERS_FULL_ACCESS` flag is enabled.
=> api: adding endpoints to FEATURE_SUPERUSERS_FULL_ACCESS (PROJQUAY-7045)

storage/cloud.py
Adds an option for min_chunk_size to the S3 storage provider
=> storage: Add min chunk size for S3 storage for multipart upload (PROJQUAY-7328)

data/registry_model/blobuploader.py
Adds logging on uploads to object storage
during the initial upload and the final copy
=> storage: add debug log for time taken to upload blob (PROJQUAY-7328)

data/model/autoprune.py, data/model/oci/tag.py, util/notification.py
Update autoprune model to fetch tags based on autoprune policies that are due to expire
=> autoprune: autoprune model changes (PROJQUAY-7076)

web/cypress/e2e/repository-notifications.cy.ts, web/src/routes/RepositoryDetails/Settings/NotificationsCreateNotification.tsx, web/src/routes/RepositoryDetails/Settings/RepoEventExpiry.tsx
=> ui: fix for negative integers in image expiry days (PROJQUAY-7442)

web/src/routes/RepositoryDetails/Settings/NotificationsCreateNotification.tsx, web/src/routes/RepositoryDetails/Settings/RepoEventExpiry.tsx
=> ui: add helper text for input (PROJQUAY-7442)

static/js/services/external-notification-data.js
=> ui: show image expiry trigger in usage logs (PROJQUAY-7466)

data/migrations/versions/8a7ba94c2e84_add_assign_token_logentry.py, data/model/oauth.py, endpoints/web.py, initdb.py, static/js/directives/ui/logs-view.js, web/cypress/test/quay-db-data.txt, web/src/hooks/UseLogDescriptions.tsx, web/src/routes/UsageLogs/UsageLogs.tsx
Adds audit log when an OAuth token is assigned.
=> oauth: logging assign oauth action to audit logs (PROJQUAY-7431)

data/migrations/versions/8a7ba94c2e84_add_assign_token_logentry.py, data/model/oauth.py, endpoints/web.py, initdb.py, static/js/directives/ui/logs-view.js, web/cypress/test/quay-db-data.txt, web/src/hooks/UseLogDescriptions.tsx, web/src/routes/UsageLogs/UsageLogs.tsx
logging assign oauth action to audit logs
=> oauth: logging assign oauth action to audit logs (PROJQUAY-7431) (#3033)

static/js/pages/manage-application.js, static/partials/manage-application.html
Fixes 2 bugs:
- Disables assign token button if user has selected a user to assign token to but hasn't selected and scopes (https://issues.redhat.com/browse/PROJQUAY-7461)
- Resolves issue where if user cancels assignment the button will still attempt to assign the token to the user
=> ui: assign OAuth token to user form checks (PROJQUAY-7433)

data/model/notification.py, notifications/__init__.py, notifications/test/test_tag_expiry_notification.py, util/notification.py
Passing notification uuid to fetch matching notification event.
=> events: fix notification methods for image expiry events (PROJQUAY-7487)

data/model/autoprune.py
=> Revert "audit: fix auto-prune audit logging (PROJQUAY-7423)"

web/cypress/e2e/usage-logs.cy.ts, web/src/hooks/UseLogDescriptions.tsx, web/src/routes/UsageLogs/UsageLogsTable.tsx
manual cherry pick of [PROJQUAY-7109](https://github.com/quay/quay/pull/2955) due to merge conflict
=> [redhat-3.12] ui: add search bar for usage logs (PROJQUAY-7109)

CHANGELOG.md
=> Revert "v3.12.1 Changelog Bump"

requirements.txt
This should resolve CVE-2024-36039.
=> deps: bump PyMySQL version (PROJQUAY-7251)

web/cypress/e2e/repository-permissions.cy.ts
Cypress test are intermittently failing at this test case. 
This is the image of the failed test case from test summary:
=> cypress: fix flake test (PROJQUAY-7624)

.github/workflows/build-and-publish.yaml
Removed s390x changes temporarily . 
Updating s390x instance with sudo user & same will be updated in this workflow
=> task: Temporary remove s390x support (PROJQUAY-7673)

static/directives/create-external-notification.html
=> ui: removing image expiry trigger option for old ui (PROJQUAY-7735)

requirements.txt
deps: Bump jinja2 
Signed off-by: harishsurf <hgovinda@redhat.com>
=> deps: Bump jinja2 (PROJQUAY-7288)

endpoints/api/organization.py
https://issues.redhat.com/browse/PROJQUAY-6465
Current member view:
Fixed member view:
Unauth view of the organization:
=> bug: fixing NaN value error for quota displayed on member org page (PROJQUAY-6465)

web/cypress/e2e/autopruning.cy.ts, web/src/routes/RepositoryDetails/Settings/RepositoryAutoPruningReadonlyPolicy.tsx
=> ui: show all auto-pruning policies for namespace (PROJQUAY-7975)

web/cypress/e2e/autopruning.cy.ts, web/cypress/e2e/repository-autopruning.cy.ts, web/cypress/e2e/usage-logs.cy.ts, web/src/hooks/UseLogDescriptions.tsx, web/src/routes/RepositoryDetails/Settings/RepositoryAutoPruningReadonlyPolicy.tsx
Adds the tag pattern to audit logs and the namespace policy list in the repository auto-pruning tab.
=> ui: adding tag pattern to audit logs in namespace policy list (PROJQUAY-8002)

requirements.txt
reverts (#3293) which is causing AttributeError in stage
=> Revert "build(deps): bump stripe from 5.5.0 to 11.0.0 (#3293)"

endpoints/api/superuser.py
remove internal-only decorator from PUT request
=> api: put /superuser/users/<username> will now show up in swagger (PROJQUAY-7579)

web/cypress/e2e/repository-autopruning.cy.ts, web/src/routes/RepositoryDetails/Settings/RepositoryAutoPruning.tsx
=> ui: show user autoprune policies under repo autoprune policies tab (PROJQUAY-8093)

package-lock.json, package.json
- Upgrade express and its dependencies. This updates path-to-regexp
=> deps: Upgrade express and dependencies (PROJQUAY-7800)

package-lock.json, package.json
- Upgrade express and its dependencies. This updates path-to-regexp
=> deps: Upgrade express and dependencies (PROJQUAY-7799)

data/logs_model/elastic_logs.py, data/logs_model/logs_producer/elasticsearch_logs_producer.py, data/logs_model/test/fake_elasticsearch.py, data/logs_model/test/mock_elasticsearch.py, data/logs_model/test/test_elasticsearch.py, requirements.txt
=> chore: Revert "[redhat-3.12] cve: upgrade elasticsearch and elasticsearch-dsl to 8.13.0 (PROJQUAY-6962)" (PROJQUAY-6962)

data/logs_model/elastic_logs.py, data/logs_model/logs_producer/elasticsearch_logs_producer.py, data/logs_model/test/fake_elasticsearch.py, data/logs_model/test/mock_elasticsearch.py, data/logs_model/test/test_elasticsearch.py, requirements.txt
=> chore: Revert "cve: upgrade elasticsearch and elasticsearch-dsl to 8.13.0 (PROJQUAY-6962)" (PROJQUAY-6962)

package-lock.json, package.json
=> Revert "deps: Upgrade express and dependencies (PROJQUAY-7800)"

web/package-lock.json, web/package.json
Updating axios. Cherrypick for https://github.com/quay/quay/pull/3462
=> dep: updating axios (PROJQUAY-7657)

web/package-lock.json, web/package.json
=> dep: updating axios (PROJQUAY-7657) (#3462)

.github/workflows/CI.yaml
docker-compose is not installed on test instance, need to change to docker compose.
=> changing docker-compose to docker compose in cypress tests

requirements.txt
updating jinja2 to 3.1.5. This is a cherrypick of https://github.com/quay/quay/pull/3536
=> dep: updating jinja2 to 3.1.5 (PROJQUAY-8375)

data/database.py, data/migrations/versions/3634f2df3c5b_drop_unique_constraint_on_org_sku_table.py, data/model/organization.py, data/model/organization_skus.py, endpoints/api/billing.py, static/directives/org-binding.html, static/js/directives/ui/org-binding.js, static/js/directives/ui/usage-chart.js, test/test_api_usage.py, util/marketplace.py, web/src/components/modals/OrgSubscriptionModal.tsx, web/src/hooks/UseMarketplaceSubscriptions.ts
* Alembic migration to drop unique constraint on the orgrhsubscriptions table
* Can split sub quantities of MW02702 across multiple orgs
* Can specify quantity for the MW02702 SKU across orgs on react UI
* Update angular UI to allow user to specify quantities for MW02702
* Write unit tests for splittable skus
=> marketplace: splittable sku for MW02702 (PROJQUAY-8151)

data/model/repository.py
Allows adding a suffix to uuid repo names to collect metrics
=> gc: Allow setting a deleted repo name's suffix (PROJQUAY-8408)

conf/nginx/nginx.conf.jnj
=> Revert "util: parse forwarded headers for ip (PROJQUAY-8444)"

setup.py
=> chore: update setup.py

storage/akamaistorage.py, storage/test/test_akamai.py
Redirect in network request to return s3 signed URL
=> storage: Redirect in network request to return s3 signed URL (PROJQUAY-8489)

package-lock.json, package.json
updating jquery to 3.5.0. This is a cherrypick of https://github.com/quay/quay/pull/3629
=> deps: updating jquery to 3.5.0 (PROJQUAY-8522)

.github/workflows/build-and-publish.yaml
Request you to merge with redhat 3.11,redhat 3.12 & redhat 3.13
=> chore: fix for wide open ssh for vsi for Z

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
updated target group names in stage dashboard
=> chore: updated target group names in stage dashboard (PROJQUAY-8506)

endpoints/api/__init__.py, endpoints/api/robot.py, endpoints/api/test/test_robot.py
This is a cherrypick of https://github.com/quay/quay/pull/2420
=> api: accepting empty body for create robot endpoints (PROJQUAY-6224)

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
- Added Pull SLI Panel
- Added Push SLI Panel
- Added ELB errors to the calculations of SLI
=> chore: Added SLO dashboards based on ALB metrics (PROJQUAY-8506) 

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
Corrected Invalid Json Formatting
=> chore: corrected Invalid Json Formatting (PROJQUAY-8506)

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
The SLO is 99.5%. Corrected the equation.
=> chore: corrected error budget left calculations (PROJQUAY-8506)

.github/workflows/build-and-publish.yaml
There is a change in CIDR. Hence added new code for CIDR retrieval and added conditions for run clean up. Request you to review and approve changes.
=> chore: Change in the CIDR for Z

storage/cloud.py
Add missing argument in debug log
=> storage: fix format error (PROJQUAY-8610)

requirements.txt
cherrypick of https://github.com/quay/quay/pull/3706
=> chore: upgrade jinja to 3.1.6 (PROJQUAY-8657) (#3706)

requirements.txt
cherrypick of https://github.com/quay/quay/pull/3706
=> chore: upgrade jinja to 3.1.6 (PROJQUAY-8657)

endpoints/api/billing.py
Fixes bug where removing a MW02702 sub after all it's quantities have been bound causes the next item in the subscription list to be skipped over, resulting in a malformed api response for the marketplace endpoint.
=> billing: stop modifying subscription list that is being iterated over (PROJQUAY-8712)

requirements.txt
cherrypick for https://github.com/quay/quay/pull/3731
=> deps: bump gunicorn (PROJQUAY-8726)

web/cypress/e2e/repository-details.cy.ts, web/src/routes/RepositoryDetails/Tags/TagsTable.tsx
=> fix(ui): corrected pull column alignment in tag view (PROJQUAY-8623)

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
tested in stage and corrected metric to span over entire load balancer
=> operations: corrected metric expression to span over all targets (PROJQUAY-8508)

.github/workflows/build-and-publish.yaml
This is an extension for PR (https://github.com/quay/quay/pull/3693) to merge the changes to redhat-3.10 branch.
=> chore: Change in the CIDR for Z (#3693)

deploy/openshift/quay-py3-app.yaml
=> Revert "deploy: Adding graceful shutdown on pods (PROJQUAY-8760)"

health/services.py
=> Revert "healthcheck: Make gunicorn health check timeout configurable (PROJQUAY-8757)"

deploy/openshift/quay-py3-app.yaml
=> Revert "healthchecks: Use httpGet for liveness and readiness probe checks (PROJQUAY-8747)"

.github/workflows/CI.yaml
cherrypick of https://github.com/quay/quay/pull/3783
=> chore: move github runners to ubuntu-22.04 (#3783)

web/src/components/DateTimePicker.tsx
This code provides a locale-aware date+time picker, synchronizing user selections between calendar button and manual input fields. Fixes problems in [PROJQUAY-8633](https://issues.redhat.com//browse/PROJQUAY-8633)
=> bug: make changes to taghistory page to accept manually entered date (PROJQUAY-8633)

.tekton/quay-test-pull-request.yaml, .tekton/quay-test-push.yaml
adding remaining package-lock.json files to prefetch command
=> add npm deps to prefetch

data/registry_model/registry_proxy_model.py, data/registry_model/test/test_registry_proxy_model.py
Changes do not resolve the issue.
=> Reverting PROJQUAY-8536

deploy/openshift/quay-py3-app.yaml
Remove anti-affinity for reg proxy
=> deploy: remove anti-affinitfy for registry proxy (PROJQUAY-8839)

package-lock.json, package.json
cherrypick of PR https://github.com/quay/quay/pull/3872
=> deps: updating angular to 1.6.4 (PROJQUAY-8781) (#3872)

Dockerfile
cherry pick of https://github.com/quay/quay/pull/3817
=> dockerfile: dockerfile changes for konflux (PROJQUAY-8804)

requirements.txt
Upgrading gevent and greenlet. cherrypick of https://github.com/quay/quay/pull/3928
=> deps: upgrading gevent (PROJQUAY-8938)

.tekton/quay-test-pull-request.yaml, artifacts.lock.yaml
adds labels to build pipeline in order to pass conforma
fixes `[Violation] labels.disallowed_inherited_labels`
=> chore: add labels (PROJQUAY-0000)

hack/generate-rpms.sh, rpms.lock.yaml, ubi.repo
attempts to fix `rpm_repos.ids_known`
need to update the repo file to match those in [known repositories](https://github.com/release-engineering/rhtap-ec-policy/blob/main/data/known_rpm_repositories.yml)
=> chore: updating rpms (PROJQUAY-0000)

requirements-build.txt
This is already vendored by the cryptography package. This causes conflicting versions.
=> deps: removing maturin

deploy/openshift/quay-py3-deploy-template.yaml
Updating deploy file used by debug deployment.
=> healthchecks: Use httpGet for liveness and readiness probe checks (PROJQUAY-8747)

data/registry_model/test/test_registry_proxy_model.py, requirements.txt
updating python protobuf version. cherrypick of https://github.com/quay/quay/pull/4096
=> deps: updating python protobuf (PROJQUAY-9081) (#4096)

data/registry_model/test/test_registry_proxy_model.py, web/package-lock.json
=> [redhat-3.13] deps: update pbkdf2 to version 3.1.3 (PROJQUAY-9090)

data/registry_model/test/test_registry_proxy_model.py, web/package-lock.json
=> [redhat-3.9] deps: update pbkdf2 to version 3.1.3 (PROJQUAY-9094)

web/cypress/e2e/mirroring.cy.ts, web/package-lock.json, web/package.json, web/src/components/StatusDisplay.tsx, web/src/components/forms/FormCheckbox.tsx, web/src/components/forms/FormTextInput.tsx, web/src/hooks/UseMirroringConfig.ts, web/src/hooks/UseMirroringForm.ts, web/src/libs/utils.ts, web/src/resources/MirroringResource.ts, web/src/routes/RepositoryDetails/Mirroring/Mirroring.css, web/src/routes/RepositoryDetails/Mirroring/Mirroring.tsx, web/src/routes/RepositoryDetails/Mirroring/MirroringAdvancedSettings.tsx, web/src/routes/RepositoryDetails/Mirroring/MirroringConfiguration.tsx, web/src/routes/RepositoryDetails/Mirroring/MirroringCredentials.tsx, web/src/routes/RepositoryDetails/Mirroring/MirroringHeader.tsx, web/src/routes/RepositoryDetails/Mirroring/MirroringModals.tsx, web/src/routes/RepositoryDetails/Mirroring/MirroringStatus.tsx, web/src/routes/RepositoryDetails/Mirroring/types.ts, web/src/routes/RepositoryDetails/RepositoryDetails.tsx
this is a cherrypick of https://github.com/quay/quay/pull/4121
=> ui: Add Mirroring to ui (PROJQUAY-8886)

.tekton/quay-v3-14-pull-request.yaml, .tekton/quay-v3-14-push.yaml
add labels and add hermetic param
=> konflux: hermetic script (PROJQUAY-0000)

Dockerfile, package-lock.json
manual cherry pick of https://github.com/quay/quay/pull/4192
=> konflux: update to nodejs-22 (PROJQUAY-9279)
