README.md
Fixing a broken link in the README for documentation on the Docker Registry Protocol. Also adding some ands!
Added the following link to replace broken link:
https://docs.docker.com/registry/spec/api/
---
=> Fix Broken Link for Docker Registry Protocol

conf/nginx/server-base.conf.jnj
Fixes an issue encountered when attempting to pull images from Quay via podman when storage proxying is enabled. Configures nginx to clear the Authorization header to ensure that storage engine does not raise a 400
updated line 45 of nginx/server-base.conf.jnj
https://issues.jboss.org/projects/PROJQUAY/issues/PROJQUAY-4
---
=> PROJQUAY-4 - Fix 400s raised when podman is attempting to pull images via proxied storage

Makefile, scripts/app_sre_build_deploy.sh, scripts/app_sre_pr_check.sh
Added scripts used by app-sre CI pipeline. These scripts are required for any applications managed by APP SRE and deployed to OSD cluster.
- PR check script
- Deployment image build script
- Make file target to build the docker image.
=> PROJQUAY-8 - Added app-sre ci pipleline scripts and Makefile targets

deploy/openshift/quay-app.yaml
Added OpenShift template to setup Quay.io application on OSD cluster. This template will be used by App-SRE CI/CD pipeline to install & update Quay application on OSD cluster.
https://issues.jboss.org/browse/PROJQUAY-11
=> added OpenShift template for Quay app

deploy/openshift/quay-app.yaml
The value for progressDeadlineSeconds had time unit in it. It needs to be integer
=> PROJQUAY-11 - update progressDeadlineSeconds value for openshift deployment

data/model/repo_mirror.py, endpoints/api/mirror.py, endpoints/api/test/test_mirror.py, endpoints/api/test/test_security.py, static/js/directives/repo-view/repo-panel-mirroring.js, test/registry/registry_tests.py
Updated API to remove mirror/rules endpoint. Rule is now handled within body of config only.
https://issues.jboss.org/browse/PROJQUAY-12
=> PROJQUAY-12 - remove mirror/rules API

endpoints/web.py, templates/base.html, templates/opensearch.xml
Adds [OpenSearch](https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md) capabilities to Quay. This allows searching [directly using the Chrome OmniBar](https://stackoverflow.com/questions/7630144/how-to-add-google-chrome-omnibox-search-support-for-your-site).
- Add `/opensearch.xml` route handler and template (for specific hostname)
- Add `<link rel="search">` tag to `base.html`
**Chrome OnmiBar search (using `ngrok` because `localhost` not allowed):**
Addresses https://issues.jboss.org/browse/PROJQUAY-14
=> OpenSearch

Dockerfile.osbs
Some container platforms don't allow containers running as root user. This creates a rhel7-based Dockerfile with the changes required for this. Although this may become the standard in the future, confine this change to a custom Dockerfile so it can be thoroughly tested by interested users.
https://issues.jboss.org/browse/PROJQUAY-20
=> PROJQUAY-20 - Dockerfile.osbs for non-root container

Dockerfile.centos7.osbs, Makefile
Until we get App-SRE pipleline setup to build RHEL7 based container images, we will use CentOS7 as the base image.
https://issues.jboss.org/browse/PROJQUAY-20
=> PROJQUAY-20 - CentOS7 based Docker file for non-root container

Makefile, scripts/app_sre_build_deploy.sh, scripts/app_sre_build_deploy_centos7.sh, scripts/app_sre_build_deploy_rhel7.sh, scripts/app_sre_pr_check _centos7.sh, scripts/app_sre_pr_check.sh, scripts/app_sre_pr_check_rhel7.sh
As we setup CI/CD pipeline for Quay, we may need to switch the source image for quay container images. We should achieve this code change for Jenkins job in the app-interface repository and not the upstream quay repository.
https://issues.jboss.org/browse/PROJQUAY-24
=> added scripts to build off both rhel7 and centos7

Dockerfile.osbs
App-SRE is able to pull RHEL7 images from registry.access.redhat.com/rhel7:7.7 and not from registry.redhat.io/rhel7:7.7
https://issues.jboss.org/browse/PROJQUAY-27
=> PROJQUAY-27 - changed source of rhel7 container image

scripts/ci
This script intends this command to be `docker logs` not `docker log`.
https://issues.jboss.org/browse/PROJQUAY-30
=> PROJQUAY-30 - scripts/ci: fix incorrect logs command usage

data/migrations/tester.py, data/migrations/versions/34c8ef052ec9_repo_mirror_columns.py, data/migrations/versions/703298a825c2_backfill_new_encrypted_fields.py, data/migrations/versions/c059b952ed76_remove_unencrypted_fields_and_data.py
The no-op-er appears to return different results for abstractproperty's under different versions of Python, and this was therefore breaking the checks. We change to a method to ensure we always get a boolean response.
Correct fix for https://issues.jboss.org/browse/PROJQUAY-19
=> Change is_testing to a method under DataTester

Dockerfile, Dockerfile.centos7.osbs, Dockerfile.osbs, Dockerfile.rhel7
The `certs_create.sh` expects _/certificates_ to be writable. Dockerfiles updated.
https://issues.jboss.org/browse/PROJQUAY-34
=> PROJQUAY-34 - create and chown /certificates

buildtrigger/gitlabhandler.py
We were trying to get an authorized client, which is failing. In such a scenario, just delete the trigger.
Fixes https://issues.jboss.org/browse/PROJQUAY-35
=> Fix deactivation of Gitlab triggers with invalid tokens

static/css/directives/ui/repository-events-table.css, static/directives/repo-view/repo-panel-settings.html, static/directives/repository-events-table.html, static/js/directives/repo-view/repo-panel-settings.js, static/js/directives/ui/repo-state/repo-state.component.css, static/js/directives/ui/repo-state/repo-state.component.html, static/js/directives/ui/repo-state/repo-state.component.ts, static/js/quay.module.ts, static/js/types/custom.d.ts
Improves styling of repo state dropdown. Refactored in the process to a TypeScript component.
**Pretty repository state dropdown:**
Addresses https://jira.coreos.com/browse/QUAY-2071
=> QUAY-2071 - Repo Mirroring Styling

active_migration.py, data/migrations/versions/49e1138ed12d_change_token_column_types.py, data/migrations/versions/703298a825c2_backfill_new_encrypted_fields.py, data/migrations/versions/c059b952ed76_remove_unencrypted_fields_and_data.py
This will ensure that if we have an issue, we don't also have to contend with a schema change
=> Break the encrypted token backfill into its own phase

Dockerfile.rhel7
This should allow the image to be executed successfully without manually providing the environment variable `ENCRYPTED_ROBOT_TOKEN_MIGRATION_PHASE`.
Additionally, users who want to take advantage of the 5-phase migration can do so by overriding the environment variable upon startup/deployment.
* Modified RHEL Dockerfile to specify a default for the migration environment variable.
* [PROJQUAY-45](https://issues.jboss.org/browse/PROJQUAY-45)
**TESTING**
1. Build the Image
2. Run it without overriding the environment variable. It should start as expected and perform the migration in whole.
3. Run it while specifying another value for the environment variable. It should start running the associated migration.
More detail is included in the referenced Jira story.
n/a
---
=> [PROJQUAY-45] Specify `new-installation` migration for 3.2.

static/directives/repository-events-table.html, static/js/directives/ui/repository-events-table.js
Previously we hid the "Create Notification" button if in readonly mode or if the user didn't have write access to the repository. For mirrored repositories, users don't have write access, but the notification worker can still create notifications, so allow users to make them.
**"Create Notification" button for a mirrored repository:**
Fixes https://issues.jboss.org/browse/PROJQUAY-42
Fixes https://jira.coreos.com/browse/QUAY-2198
=> Allow Creating Notifications for Mirrored Repositories

config.py
Ensure running RHQ with zero config results in correct product branding.
Addresses https://jira.coreos.com/browse/QUAY-2211
=> Default RHQ Product Branding

deploy/openshift/quay-app.yaml
The Liveness and Readiness probes were not working because the connection to port 8443 was being rejected due to SSL cert issues. As the cert is setup for external domain name, requests to `localhost` were being rejected with `400` error code.
The modified check uses `curl` with `-k` (insecure) flag to check if the application is ready and later check if it is still live.
https://issues.redhat.com/browse/PROJQUAY-39
=> PROJQUAY-39 modified quay liveness and readiness probes

endpoints/api/repository_models_pre_oci.py
Ensure that the `repoList` endpoint uses the `repo_kind` when checking if a repository is starred.
Fixes https://issues.redhat.com/browse/PROJQUAY-55
=> Fix Starred Application Repositories

static/directives/repo-view/repo-panel-mirroring.html, static/js/directives/ui/entity-search.js
It doesn't make sense to show other entities in this dropdown.
**Robot dropdown:**
Addresses https://issues.redhat.com/browse/PROJQUAY-57
=> Restrict Mirror Robot Dropdown Select to Just Robots

deploy/openshift/quay-app.yaml
Secrets in vault do not allow us to configure sub directories. We need to store content of sub directories in a separate secret and mount it in the right location in the container.
JIRA: https://issues.redhat.com/browse/PROJQUAY-61
=> mount the extra_ca_certs dir in /conf/stack

conf/init/supervisord_conf_create.py, conf/supervisord.conf.jnj, requirements-nover.txt, requirements.txt
https://issues.redhat.com/browse/PROJQUAY-67
Configure quay to use syslog by setting the following env vars:
```sh
SYSLOG_SERVER=<ip address>
SYSLOG_PORT=514
SYSLOG_PROTO=udp
QUAY_LOGGING=syslog
```
Following the config from this blog post:
http://mneilsworld.com/discussion/supervisord-docker-and-loggly
=> PROJQUAY-67 - Allow quay to forward logs to syslog

initdb.py
(cherry picked from commit 68686c0def14b4220cb08f2e5e54fd6598659972)
https://issues.redhat.com/browse/PROJQUAY-63
=> PROJQUAY-63 - cherry-pick - Add missing parameter to call on count_repository_actions in initdb

deploy/openshift/quay-app.yaml
Deploy a syslog sidecar with Quay app container and forward logs to AWS CloudWatch.
JIRA: https://issues.redhat.com/projects/PROJQUAY/issues/PROJQUAY-67
=> PROJQUAY67 - added syslog sidecar to openshift template

deploy/openshift/quay-app.yaml
mount extra ca certs in `/conf/kube_extra_certs` instead of `/conf/stack/extra_ca_certs`
=> mount extra ca certs in /conf/kube_extra_certs

config.py, endpoints/api/__init__.py, util/config/schema.py
This PR adjusts the fresh login check so that it will be skipped if a password is not set for the user in any auth system.
This PR also makes the fresh login check time configurable
Fixes https://jira.coreos.com/browse/QUAY-1312
=> Fresh login check improvements

deploy/openshift/quay-app.yaml
[ci skip]
Default timeout on ELB is 60 seconds and this can cause issue when user is pushing container image with large (4GB+) layers.
JIRA: https://issues.redhat.com/browse/PROJQUAY-117
=> PROJQUAY-117 - Set ELB timeout to 3600 seconds

image/docker/schema2/config.py
Fixes https://issues.redhat.com/browse/QUAY-2111
=> The `created` key in V2_2 config is optional, so make sure to treat it as such

conf/nginx/http-base.conf, config_app/conf/http-base.conf
* centos8/rhel8 changed the location of `mime.types`
* ..
* ..
**TESTING** ->
---
=> Update location for centos8/rhel8

deploy/openshift/quay-app.yaml
[ci skip]
JIRA: https://issues.redhat.com/browse/PROJQUAY-138
Proxy protocol support must be enabled in the ELB so that quay app can get source IP address.
=> PROJQUAY-138: Enable proxy protocol for Quay application ELB

requirements.txt, util/config/validators/test/test_validate_redis.py
* [PROJQUAY-134](https://issues.redhat.com/browse/PROJQUAY-134)
* Replaces mockredispy (deprecated) with fakeredis
* ..
**TESTING** ->
---
=> Replace mockredis with fakeredis

config_app/config_util/config/baseprovider.py, features/__init__.py, util/config/provider/baseprovider.py
* Changes `yaml.safe_dump` to return a str instead of bytes
* ..
* ..
**TESTING** ->
---
=> Remove encoding arg to get str instead of bytes

emails/emailchanged.html
* changed text in email template from 'password' to 'e-mail address'
* string 'e-mail-address' is used in subject as well
* seems to be a copy/paste bug
* changed string to fit to purpose of email
**TESTING** ->
---
=> Fixed text in emailchanged template from password to email

app.py, features/__init__.py, util/config/superusermanager.py
It appears a few files are failing when verifying their syntax/formatting using `black`. This change-set resolves that issue.
- Python 3 Upgrade Epic: https://issues.redhat.com/browse/PROJQUAY-68
**TESTING**
- CI on changes to the Python3 branch should no longer fail with `black` errors unless they are introduced in new branches.
n/a
---
=> Run `black` on Python3 branch

data/fields.py
Fixes the following test failure from `test/test_ldap.py` in Python 3
```
data/database.py:637: in <module>
class RobotAccountToken(BaseModel):
.venv-37/lib64/python3.7/site-packages/peewee.py:6004: in __new__
cls._meta.add_field(name, field)
.venv-37/lib64/python3.7/site-packages/peewee.py:5804: in add_field
self.defaults[field] = field.default
E   TypeError: unhashable type: 'indexed_class'
```
- https://issues.redhat.com/browse/PROJQUAY-135
**TESTING**
Ensure this test doesn't fail with the same error any longer.
n/a
---
=> Fix unhashable class test failure

Dockerfile, Dockerfile.rhel7
This is a temporary fix for the following error when building the base `Dockerfile`.
```
ERROR: Package 'setuptools' requires a different Python: 2.7.16 not in '>=3.5'
Error: error building at STEP "RUN scl enable python27 "    pip install --upgrade setuptools pip &&     pip install -r requirements.txt --no-cache &&     pip install -r requirements-tests.txt --no-cache &&     pip freeze &&     mkdir -p $QUAYDIR/static/webfonts &&     mkdir -p $QUAYDIR/static/fonts &&     mkdir -p $QUAYDIR/static/ldn &&     PYTHONPATH=$QUAYPATH python -m external_libraries     "": error while running runtime: exit status 1
```
Long-term, the issue should be addressed properly when the project transitions to Python 3.x.
* Pin setuptools to the latest available version compatible with Python 2.7 in the …
=> Use specific setuptools version in Dockerfile

Dockerfile.osbs
https://issues.redhat.com/browse/PROJQUAY-146
Missed Dockerfile.osbs
=> PROJQUAY-146 - correct Dockerfile.osbs

requirements.txt
Replaces Python package bencode with [bencode.py](https://pypi.org/project/bencode.py/) for Python 3 compatibility.
- Replaced a single package with a newer fork.
- https://issues.redhat.com/browse/PROJQUAY-165
**TESTING**
- Install `requirements.txt` in a Python 3.6 environment and ensure that it doesn't fail on `bencode`
n/a
---
=> [PROJQUAY-165] Replace package `bencode` with `bencode.py`

test/fixtures.py, test/helpers.py, test/queue_threads.py, test/registry_tests.py, test/test_api_usage.py, test/test_endpoints.py, test/test_external_jwt_authn.py, test/test_keystone_auth.py, test/test_ldap.py, test/test_oauth_login.py, test/test_secscan.py, test/testlogs.py
https://issues.redhat.com/browse/PROJQUAY-68
Fix imports for test files
=> PROJQUAY-38 - fix test imports

data/logs_model/logs_producer/kinesis_stream_logs_producer.py, features/__init__.py
A couple of files did not meet the formatting expectations for `black` as a Python 3.6 target. This PR reformats them. 
* Fix formatting in 2 files
n/a
**TESTING**
- `black` should no longer fail
n/a
---
=> Run `black` to cleanup Python 3 code

buildman/manager/ephemeral.py
Previously, a library (`trollius`) was used to take advantage of asyncio
in Python 2.7. However, one function (`async`) is now a keyword. This
causes certain parsers to encounter a syntax error when parsing the Python
file for linting and other verification purposes.
According to the Python documentation, the old `async()` function is
now simply an alias for `ensure_future()` and it has been replaced accordingly.
Example Error:
```
(quay) [kmullins@rh-laptop quay]$ mypy .
buildman/manager/ephemeral.py:12: error: invalid syntax
```
- Replace `async(...)` with `ensure_future(...)` in a specific file which throws a syntax error when parsing in Python 3.6+
- Remove the import of `async` from the same file
- Related to https://issues.redhat.com/browse/PROJQUAY-116
**TESTING**
- Linters should …
=> Fix syntax error in Python 3.6+

data/test/test_encryption.py
Adds a unit test to ensure fix for https://issues.redhat.com/browse/PROJQUAY-164 in Python3 is backwards-compatible.
Addresses https://issues.redhat.com/browse/PROJQUAY-171
=> Test for encrypted fields

requirements.txt
https://issues.redhat.com/browse/PROJQUAY-68
Allow gpg package version available on fedora as well as centos8 and rhel8
=> PROJQUAY-38 - unpin gpg package version

scripts/ci
* Run flake8 to find Python syntax errors and undefined names.
* Add a flake8 run to the CI listing step
**TESTING** -> Yes.  Linting is part of the continuous integration testing
**BREAKING CHANGE** -> No.
https://flake8.pycqa.org/en/latest/user/error-codes.html
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these tests focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic …
=> scripts/ci: add run_flake8() to lint step

.travis.yml
* Travis CI have fully deprecated the __sudo:__ tag and has removed all mention of it from their documentation.
https://changelog.travis-ci.com/the-container-based-build-environment-is-fully-deprecated-84517
* Remove the __sudo:__ tag.
**TESTING** -> Yes.  Travis CI is continuous integration testing.
**BREAKING CHANGE** -> No.
---
=> Travis CI: sudo: is fully deprecated in Travis

util/metrics/prometheus.py
Endpoint already has semantic meaning as a label in existing Prometheus scraping. In order to avoid conflicts and simplify aggregation, this label is being renamed.
=> metrics: s/endpoint/route

scripts/ci
- It appears that Flake8 is raising issues with the existing Python 2.7 code.
While it is possible that these could genuinely use some cleanup, it
appears some errors come from the expectation of Python 3.x syntax. It  has
been temporarily commented out until we can fix it.
- Related to: https://github.com/quay/quay/pull/162
Example CI Error:
```
35    E999 SyntaxError: invalid syntax
27    F821 undefined name 'basestring'
62
The command "scripts/ci lint" exited with 1.
```
* Comment out execution of `flake8` in CI until all offending files are fixed or Flake8 is configured to verify against the correct Python version
- This is a resolution to the CI failures caused in #162
**TESTING**
- The CI lint stage should no longer fail on `flake8` and `flake8` is not executed during CI at this …
=> Disable Flake8 in CI on Python 2.7 branch

deploy/openshift/quay-app.yaml
[ci skip]
JIRA: https://issues.redhat.com/browse/PROJQUAY-181
http://quay.io should be redirected to https://quay.io
=> PROJQUAY-181: redirect http to https for quay.io

util/jsontemplate.py
Replaces #179 using https://six.readthedocs.io/index.html#six.string_types
* __basestring__ was removed in Python 3 because all __str__ are Unicode.
* from six import string_types
* replace basestring with string_types
**TESTING** ->
---
=> Python 3: Replace basestring with six.string_types

data/test/test_encryption.py
Fixes lint failure in branch by cleaning up a file using `black`.
* Run `black` on offending file.
n/a
**TESTING**
CI should no longer fail in the lint stage on the `python3` branch.
n/a
---
=> Reformat 1 Python file using `black`

conf/init/nginx_conf_create.py, conf/nginx/hosted-http-base.conf.jnj
[ci skip]
JIRA: https://issues.redhat.com/browse/PROJQUAY-181
http://quay.io should be redirected to https://quay.io
Set `FEATURE_PROXY_PROTOCOL` to `True` to enable proxy protocol support for HTTP traffic.
=> PROJQUAY-181: updated nginx to redirect http to https for quay.io

oauth/utils.py
* __xrange()__ was removed in Python 3 so convert to __range()__ instead as recommended at:
https://portingguide.readthedocs.io/en/latest/iterators.html#new-behavior-of-range
* __xrange()__ --> __range()__
**TESTING** -> Discovered via our flake8 in our continuous integration.
**BREAKING CHANGE** -> No.  Fixing change.
---
=> xrange() was removed in Python 3

digest/checksums.py
* __file()__ was removed in Python 3 so replace with __open()__.
* __file()__ --> __open()__
**TESTING** -> Discovered and verified by the flake8 testing in our continuous integration.
**BREAKING CHANGE** ->. No.  Fix ing change.
---
=> file() was removed in Python 3

oauth/provider.py
* __StandardError__ was removed in Python 3 so replace all instances with __Exception__ as recommended at:
https://portingguide.readthedocs.io/en/latest/exceptions.html#the-removed-standarderror
* __StandardError__ --> __Exception__
**TESTING** -> Discovered and tested by our flake8 tests.
**BREAKING CHANGE** -> No
---
=> StandardError was removed in Python 3

.travis.yml, Dockerfile.cirun, scripts/ci
Fixes an issue where `make` is missing during certain CI tests and causes CI to fail.
* Use the CI image for all tests
* Ran `black` and corrected formatting on one file to unblock CI in the lint stage.
- https://issues.redhat.com/browse/PROJQUAY-68
**TESTING**
- CI should no longer fail on executing `make`
n/a
---
=> Install make for ci

data/fields.py
* __serialized_state__ is an _undefined name_ in this context which has the potential to raise NameError at runtime.  __serialized_tate__ (typo) is defined on the line above.
* serialized_tate --> serialized_state
**TESTING** ->
__flake8 . --count --show-source --statistics --select=E9,F63,F72,F82__
No.  Fixing change.
---
=> Typo: serialized_tate --> serialized_state

Dockerfile.cirun
In the `python3` branch, the installation of `requirements-tests.txt` was removed from the primary Dockerfile.
This PR installs both the Python test requirements and git when building the Dockerfile used by CI, `Dockerfile.cirun`.
=> Install test dependencies in CI Image

data/model/oci/manifest.py, data/model/oci/retriever.py, data/model/oci/test/test_oci_manifest.py, data/secscan_model/secscan_v2_model.py
- Add additional retries and slightly increase the delay time
- Add a proper exception returned on failure
- Add a test to verify that we raise the proper exception
=> Additional fixes for config load failure in manifest creation

endpoints/v2/test/test_blob.py, endpoints/v2/test/test_manifest.py, scripts/ci, storage/downloadproxy.py, test/specs.py, util/secscan/api.py, util/tufmetadata/api.py
In the Python3 work, we have introduced multiple changes to CI. Specifically, we have moved all test-dependencies from the base Dockerfile(s) into Dockerfile.cirun.
There is now the following error:
```
Unable to find image 'quay-ci:943072a-687-ci-run' locally
docker: Error response from daemon: pull access denied for quay-ci, repository does not exist or may require 'docker login'.
```
**Jira:**
https://issues.redhat.com/browse/PROJQUAY-218
=> Fix missing Dockerfile in CI

buildtrigger/basehandler.py, buildtrigger/test/test_basehandler.py, endpoints/building.py, endpoints/test/test_building.py, static/css/directives/repo-view/repo-panel-builds.css, static/css/directives/ui/manage-trigger-control.css, static/directives/repo-view/repo-panel-builds.html, static/js/directives/ui/manage-trigger/manage-trigger.component.html, static/js/directives/ui/manage-trigger/manage-trigger.component.ts, static/js/types/common.types.ts, util/jsontemplate.py
Users can now configure whether they want the default tagging options enabled (tag `latest` for the default branch, and tag with the git branch or tag name), and can also specify custom tags, including static tags and dynamic templated tags.
Fixes https://jira.coreos.com/browse/QUAY-1747
=> Add better tagging options for build triggers.

config_app/config_application.py, config_app/config_endpoints/api/superuser.py, scripts/ci
__python2 -m flake8 . --count --show-source --statistics --select=E9,F63,F72,F82__
```
./config_app/config_application.py:7:5: F821 undefined name 'logging'
logging.config.fileConfig(logfile_path(debug=True), disable_existing_loggers=False)
^
./config_app/config_application.py:7:31: F821 undefined name 'logfile_path'
logging.config.fileConfig(logfile_path(debug=True), disable_existing_loggers=False)
^
./config_app/config_endpoints/api/superuser.py:255:16: F821 undefined name 'ServiceKeyAlreadyApproved'
except ServiceKeyAlreadyApproved:
^
3     F821 undefined name 'logging'
3
```
https://flake8.pycqa.org/en/latest/user/error-codes.html
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that …
=> Fix some flake8 undefined names

util/security/crypto.py
When Quay used the Fernet library with Python 2, strings were implicitly treated as bytes. With Python 3, the conversion between Bytes and Strings has to be performed manually.
This change-set handles that conversion when calling Fernet.
* Convert between Strings and Bytes appropriately when calling Fernet.
- <Include associated Jira Story here>
**TESTING**
- One should be able to access the "Logs" page, as one example.
n/a
---
=> Fix usage of Fernet for Python3

config_app/config_util/config/__init__.py, config_app/config_util/config/test/test_helpers.py
This PR fixes one failing test in the configuration app's unit tests.
* Explicitly read certificate files as bytes (previous behavior) and then convert them to unicode/strings after base64 encoding them (achieves previous behavior) in the configuration app.
- Fixing unit test failures in the Python3 branch as we progress in our transition.
**TESTING**
- Configuration App tests should no longer fail
n/a
---
=> Fix base64 encode/decode error in config app.

data/model/repository.py, data/model/test/test_repository.py, endpoints/api/repository.py, endpoints/api/repository_models_pre_oci.py, endpoints/v2/v2auth.py
Instead of raising an unhandled exception, we now check for the repository during the create process. If it was created since we last checked, we simply use the reference. Otherwise, we return an error to the user.
Fixes https://issues.redhat.com/projects/PROJQUAY/issues/PROJQUAY-289
=> Handle integrity errors being raised in v2 auth

endpoints/v2/manifest.py
Doing so is technically incorrect, so we just return the unaltered manifest now.
Fixes https://issues.redhat.com/browse/PROJQUAY-227
=> Don't return down-converted manifests on digest pulls

endpoints/metrics.py, endpoints/v1/index.py, endpoints/v2/manifest.py
Currently, we mark them as v2_1, which isn't fully correct, as we serve both v2_1 and v2_2 through the same code paths
=> The incremented counters are for v2 as a whole

buildman/manager/executor.py, util/greenlet_tracing.py, util/metrics/prometheus.py
By reverting back to the default histogram buckets, additional buckets are added to make the slowest queries report more accurately.
---
=> prometheus: default histogram buckets

buildtrigger/githubhandler.py
This is a required change, as GitHub is deprecating the query parameters in a few months. See https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/ for details.
Fixes https://issues.redhat.com/browse/PROJQUAY-268
=> Change GitHub calls to pass client_id and secret in the Auth header

data/model/blob.py, workers/blobuploadcleanupworker/blobuploadcleanupworker.py, workers/blobuploadcleanupworker/models_interface.py, workers/blobuploadcleanupworker/models_pre_oci.py
Instead of running simultaneously across multiple nodes, we change the
worker to run only from a single instance. This is better for the DB and
the previous behavior was not necessary given the size of the BlobUpload
table.
Fixes https://issues.redhat.com/browse/PROJQUAY-365
=> Have the BlobUpload cleanup worker run on a single instance only

templates/base.html
Use Redhat Terms of Service and Privacy Page links in Footer
- `Terms` links to https://www.openshift.com/legal/terms
- `Privacy` links to https://www.redhat.com/en/about/privacy-policy
- https://issues.redhat.com/browse/PROJQUAY-162
- https://issues.redhat.com/browse/PROJQUAY-161
**TESTING** 
- Verify `Terms` and `Privacy` links in the footer link to Redhat's official pages and open in a new tab/window.
---
=> Use Redhat Terms & Privacy links in footer

quay-entrypoint.sh
This commit properly makes the `openssl` invocation correct for passwords starting with `-`and simplifies the code.
**TESTING** ->
---
=> quay-entypoint.sh: fix config argument handling

quay-entrypoint.sh
Turns out `--` isn't in the openssl in rhel7.
This is my bad to begin with, as this argument terminator isn't
documented even on versions where it works.
Signed-off-by: Hank Donnay <hdonnay@redhat.com>
* fixes command line
**TESTING** ->
---
=> quay-entrypoint.sh: fix openssl commandline

config_app/js/core-config-setup/config-setup-tool.html
Usage of `quay.io` in a server hostname breaks the superuser API
(on purpose) to ensure that API is never available in production.
This change ensures this is messaged properly.
Fixes https://issues.redhat.com/browse/PROJQUAY-80
=> Mark any server hostnames with `quay.io` as reserved

data/model/blob.py, data/model/gc.py, data/model/tag.py, data/model/test/test_tag.py, data/registry_model/manifestbuilder.py
The purge code assumes that once it has deleted tags, no new ones will
be added, so we need to enforce that state
=> Ensure that temporary tags cannot be written for repositories marked for deletion

data/model/repositoryactioncount.py, workers/repositoryactioncounter.py
We don't make use of any action counts older than a year, so this
change will have the worker remove old rows, one month (roughly) at
a time
=> Have the RepositoryActionCount worker cleanup old rows in RAC

data/database.py, data/model/test/test_gc.py, data/model/test/test_user.py, test/helpers.py, test/test_api_usage.py
We were not testing for transitive deletes when performing *User*
deletion, which led us to have a few
=> Add additional detection for transitive deletes and fix those found

endpoints/verbs/__init__.py
The `inc` function rejects these with an exception
Fixes https://issues.redhat.com/browse/PROJQUAY-456
=> Make sure we don't send zero value metrics to Prometheus in verbs

buildtrigger/githubhandler.py, buildtrigger/test/test_githosthandler.py
It appears GitHub has narrowed the permissions returned, so while we
might still have the ability to admin the *repo*, the permissions
list is returning `false`, so we disallow people to create triggers,
which is wrong.
Fixes https://issues.redhat.com/browse/PROJQUAY-523
=> Stop relying on GitHub's admin permissions for a repository

data/registry_model/manifestbuilder.py
When stored directly, we were encountering unicode errors for the image
metadata on older Docker clients. By serializing to/from JSON, we ensure
the unicode is handled properly
=> Change manifest builder's state to be serialized via JSON

data/database.py, data/migrations/env.py, data/model/sqlalchemybridge.py
We now cap the index name length at 64 (as per MySQL restrictions). If
an index name is *longer* than that, we hash the index name in its
entirety and then append the short-sha of the hash as a suffix to a
shortened version of the index name. This ensures the index name meets
the length requirements while *also* being stable across generations.
This change also adds a legacy map of long index names to the names we
manually applied, to ensure they don't get regenerated either
=> Implement a solution for long index names in sqlalchemybridge

buildtrigger/githubhandler.py
GitHub doesn't always send it, so we need to support the empty/missing
case.
Fixes https://issues.redhat.com/browse/PROJQUAY-210
=> Remove `message` as a required field in GitHub response

endpoints/api/__init__.py, endpoints/api/image.py, endpoints/api/secscan.py, endpoints/api/test/test_deprecated_route.py, endpoints/wellknown.py
Introduces `@deprecated` decorator for API resources, which adds the [`Deprecation: true` header](https://tools.ietf.org/id/draft-dalal-deprecation-header-01.html#RFC7234) to the response. Applies this decorator to `getRepoImageSecurity`.
```shell
$ TZ=UTC TEST=true PYTHONPATH="." py.test --verbose -x ./endpoints/api/test/test_deprecated_route.py
```
Addresses https://issues.redhat.com/browse/PROJQUAY-282
Addresses https://issues.redhat.com/browse/PROJQUAY-537
=> Deprecation Decorator for API Resources

static/js/directives/ui/fetch-tag-dialog.js
These will eventually be removed, so start the deprecation process
=> Remove squashed pull and ACI conversion from the tags UI

data/secscan_model/datatypes.py, data/secscan_model/secscan_v4_model.py, data/secscan_model/test/test_secscan_v2_model.py
Fixes `KeyError` when `Features` field is missing from Clair v2 response.
=> Safe Lookup for Clair v2 "Features" Property

config_app/c_app.py, config_app/config_endpoints/setup_web.py, config_app/js/config-field-templates/config-numeric-field.html, config_app/js/config-field-templates/config-string-field.html, config_app/js/core-config-setup/config-setup-tool.html, config_app/js/core-config-setup/core-config-setup.js, config_app/templates/index.html
This change-set allows Users to mark certain fields in the Configuration application as read-only. This is helpful for cases where certain fields may be managed by an external resource, such as the Quay Operator.
The data should still be available when read from an existing configuration, but the User should not be allowed to manually edit it through the UI.
The following options are currently supported:
- Redis
- ~Storage~ Not used at the moment. Can be implemented in the future.
- Hostname
* When running the Quay Configuration app, the following environment variable and options can be used to specify certain components as read-only: `READ_ONLY_FIELDS=redis,hostname`
- [PROJQUAY-319](https://issues.redhat.com/browse/PROJQUAY-319)
**TESTING**
- Run the Quay Configuration application with …
=> Enable marking config-app fields as read only.

data/secscan_model/datatypes.py, data/secscan_model/secscan_v4_model.py, data/secscan_model/test/securityinformation.json, data/secscan_model/test/test_secscan_v2_model.py, data/secscan_model/test/test_secscan_v4_model.py, static/js/services/vulnerability-service.js
The repo tags view doesn't fetch the actual image manifest data, so it was causing this error, which we now handle:
```
angular.min.js-f0f4228b82f7.js:116 TypeError: Cannot read property 'image' of null
at main-quay-frontend-ce466c1779e9a981eb4e.bundle.js:1
at Array.forEach (<anonymous>)
at Object.vulnService.forEachFeature (main-quay-frontend-ce466c1779e9a981eb4e.bundle.js:1)
at Object.vulnService.buildFeaturesInfo (main-quay-frontend-ce466c1779e9a981eb4e.bundle.js:1)
at main-quay-frontend-ce466c1779e9a981eb4e.bundle.js:1
at angular.min.js-f0f4228b82f7.js:128
at m.$eval (angular.min.js-f0f4228b82f7.js:142)
at m.$digest (angular.min.js-f0f4228b82f7.js:140)
at m.$apply (angular.min.js-f0f4228b82f7.js:143)
at g (angular.min.js-f0f4228b82f7.js:95)
```
=> Fix Security Scan Column on Repo Tags View

emails/base.html
Also removes the obsolete docs.quay.io reference
=> Change email template to use the configured values instead of hard coding the Quay name

storage/azurestorage.py
We were incorrectly using the source blob service
Fixes https://issues.redhat.com/browse/PROJQUAY-540
=> Have Azure copy blob use the destination credentials

storage/azurestorage.py
We were incorrectly using the source blob service
Fixes https://issues.redhat.com/browse/PROJQUAY-540
(cherry picked from commit f8ff4e0f6991bb0272bbff9948f022d47e1ac481)
https://issues.redhat.com/browse/PROJQUAY-540
=> PROJQUAY-540 - Have Azure copy blob use the destination credentials

data/secscan_model/secscan_v4_model.py, data/secscan_model/test/test_secscan_interface.py, util/secscan/v4/api.py
* Fix a few references using the wrong name
**TESTING** ->
---
=> Fix wrong reference name in ClairSecurityScannerAPI

data/users/externalldap.py, test/test_ldap.py
https://issues.redhat.com/browse/PROJQUAY-617
The LDAP class defined the filter using a default Python parameter, so
we need to mimic it
=> Fix search filter for LDAP user lookup when no user filter is specified

data/secscan_model/secscan_v4_model.py, data/secscan_model/test/test_secscan_interface.py, util/secscan/v4/api.py
* Fix wrong reference name in ClairSecurityScannerAPI
* Fix min_id referencing the value instead of the tuple reference
(cherry picked from commit b703cb452480ae5e85f311751346eefcc50a885d)
=> PROJQUAY-620 - (cherrypick) Fix wrong reference name in ClairSecurityScannerAPI (#347)

config_app/config_util/k8saccessor.py, config_app/config_util/test/test_k8saccessor.py
The `Deployment` resource was removed from the `extensions/v1beta1` APIGroup in Kubernetes 1.16. 
Fixes https://issues.redhat.com/browse/PROJQUAY-363
=> PROJQUAY-363 - Update Config App to Use apps/v1 Deployment 

data/appr_model/tag.py, data/appr_model/test/test_appr_tag.py, data/model/oci/tag.py, data/model/oci/test/test_oci_tag.py
Add an extra check and return an empty dict if no repo is given.
The assertion is needed because `Tag.repository << [rid for rid in
repository_ids]` will fail on MySQL if the list is empty.
**TESTING** ->
---
=> Add check for no repos when getting recent tags

config.py, data/secscan_model/__init__.py, data/secscan_model/interface.py, data/secscan_model/secscan_v2_model.py, data/secscan_model/secscan_v4_model.py, data/secscan_model/test/test_secscan_interface.py, data/secscan_model/test/test_secscan_v4_model.py, util/config/schema.py
The logic in the secscan model prevented indexing or retrieving vulnerability information for manifests when Quay was configured without Clair v4. Changes the logic to skip model splitting and adds tests.
- Adds no-op implementations for `V2SecurityScanner` and `V4SecurityScanner` which are used if either are not configured (properly)
- Adds tests to ensure no-op implementations work 
Fixes https://issues.redhat.com/browse/PROJQUAY-662
Fixes https://issues.redhat.com/browse/PROJQUAY-640
=> Ensure Security Scanning Works Without Clair V4

data/model/oci/manifest.py, image/docker/schema2/manifest.py, image/oci/config.py, image/oci/manifest.py, image/oci/test/test_oci_manifest.py
We instead synthesize layers based solely on the blob data and the
last config entry
Should fix the conformance test: https://github.com/opencontainers/distribution-spec/issues/147
=> Handle the scenario where the OCI config is missing the history entry

data/users/externalldap.py
Up until now, the "if not found_results" line could throw an UnboundLocalError because the variable was assigned inside a try block which could fail with the variable never assigned.
=> LDAP: Defined found_results before try block so it's always assigned

data/database.py, data/model/gc.py, data/model/user.py, workers/namespacegcworker.py, workers/repositorygcworker.py, workers/test/test_namespacegcworker.py
While a transaction is obviously safer, with the number of tables
and rows referencing these tables now, a transaction is potentially
locking up a significant chunk of the database. Since we're already
performing cleanup before calling the delete, including disabling
new data being written for the User or Repository, deletion without
a transaction should (usually) be sufficient; if it isn't, an
IntegrityError will be raised, and the workers can retry continuing
the GC operation
=> Remove the use of a transaction for User and Repository delete

data/database.py, data/readreplica.py, data/test/test_readreplica.py, endpoints/v2/manifest.py
This ensures consistency when pushing when a read replica is enabled
=> Disable read replica reading in critical registry paths

deploy/openshift/quay-app.yaml
fixes:
```
error: failed to read input object (not a Template?): unable to decode "./quay-templates/quay.yaml": v1.Template.Parameters: []v1.Parameter: v1.Parameter.Value: ReadString: expects " or n, but found f, error found in #10 byte of ...|,"value":false}]}|..., bigger context ...|:"3600"},{"name":"DB_CONNECTION_POOLING","value":false}]}
```
https://ci-int-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/quayio/job/quay-quay-gh-build-master/246/console
=> fix value for DB_CONNECTION_POOLING

quay-entrypoint.sh
https://issues.redhat.com/browse/PROJQUAY-719
This change will install certs if they exist in /conf/stack/extra_ca_certs. This allows an LDAP cert to be included at container startup for setup.
=> PROJQUAY-719 - config app install extra certs

static/js/directives/ui/build-log-error.js, webpack.config.js
Add the right [minification flags](https://github.com/terser/terser#minify-options) to Webpack's `TerserPlugin` to fix `unknown provider` error:
```
angular.min.js-f0f4228b82f7.js:116 Error: [$injector:unpr] http://errors.angularjs.org/1.5.3/$injector/unpr?p0=DocumentationServiceProvider%20%3C-%20DocumentationService%20%3C-%20ExternalNotificationData
```
Fixes https://issues.redhat.com/browse/PROJQUAY-732
Fixes https://issues.redhat.com/browse/PROJQUAY-733
Fixes https://issues.redhat.com/browse/PROJQUAY-734
=> Fix Unknown Provider AngularJS Errors

docs/getting_started.md, util/generatepresharedkey.py
- Removed logging of 'service_key_create()' and 'service_key_approve()'
- Fixed peewee account_id no-null constraint caused by this logging
=> Removed logging of 'service_key_create' and 'service_key_approve'

deploy/openshift/quay-app.yaml
In order to be able to pull a private image, we need a ServiceAccount that mounts an image pull secret.
this secret already exists in all namespaces.
this PR is safe to merge after https://gitlab.cee.redhat.com/service/app-interface/merge_requests/5183
cc @josephschorr @tparikh
=> add ServiceAccount with imagePullSecrets

data/model/repository.py, docs/getting_started.md, endpoints/api/test/test_repository.py
- Added Repository.state to query to return in api call to list repos
- Added check for state in test_get_repo
- Added api test for listRepos endpoint
=> Fixed repo list showing 'null' for state in api

scripts/app_sre_post_deploy_rhel7.sh
instead of using `aws ecr get-login`, we now have new environment variables in the job that will always contain valid push credentials to the backup registry.
depends on https://gitlab.cee.redhat.com/service/app-interface/merge_requests/5254
cc @josephschorr @tparikh
=> use backup push creds

deploy/openshift/quay-app.yaml
This PR removes load balancer service that is no longer used. It also sets log stream name to pod name and makes ticker for syslog configurable.
=> OpenShift deploy template updates for log shipper

buildman/component/buildcomponent.py, buildman/jobutil/buildstatus.py, buildman/server.py, data/buildlogs.py
* `health_check_interval` will attempt a roundtrip ping before running a command if the connection has been idle for more that the set value. If the ping fails, the redis client should close and reestablish the socket connection.
* Wrap calls to build phase updates (Redis calls) with try blocks. If there is an exception, calls `_build_finished` with its result set to `ERROR`. This is to allow the buildmanager to handle Redis connection errors more gracefully. 
**TESTING** ->
---
=> Redis connection improvements

.github/workflows/CI.yaml, Dockerfile, quay-entrypoint.sh, tox.ini
* Add the missing filemode changes that were deleted by accident while rebasing
* Reverts to using Python 3.6 for now.
@thomasmckay Need to confirm how to get Python3.8 on CentOS 8(Centos 8, RHEL 8, ...) based images, or if we just use the system default Python 3.6.
**NOTE**: Python 3.6 will be used for now as it is readily available in CentOS 8 based images. The migration from 3.6 to more modern versions should not be too involved anyways.
**TESTING** ->
---
=> Run required filemode changes in Dockerfile

Dockerfile, Dockerfile.centos7.osbs, Dockerfile.osbs, Dockerfile.rhel7, Dockerfile.rhel8, requirements-nover.txt, requirements.txt
Includes an init application as PID 1 in all Dockerfiles to catch and handle any potential defunct/orphaned/zombie processes.
* Install [dumb-init](https://github.com/Yelp/dumb-init) using pypi as this is the easiest cross-platform (Centos7/Centos8/RHEL7/RHEL8) installation method.
* Prefix all entrypoints with dumb-init to ensure it is ran as PID 1 and will act as the container's init system.
- https://issues.redhat.com/browse/PROJQUAY-776
**TESTING**
- Just verify that the container starts and runs normally.
- Verify that `dumb-init` is running as PID 1
- Optionally, build the image while including the `psmisc` package and run `pstree` to verify that all processes are children of `dumb-init`.
Example while running the `config` app:
```
[kmullins@rh-laptop quay]$ podman exec -it …
```
=> [PROJQUAY-776] Run dumb-init as PID 1

data/users/keystone.py, test/test_keystone_auth.py
The behavior between keystonev2 and keystonev3 is different today.
In keystonev3 implementation, the username comes from [user.name][1],
but keystonev2 just uses the incoming `username_or_email`.
[1]: https://github.com/quay/quay/blob/f4179e5e719ebc8e795064b8703da8a29d877b3b/data/users/keystone.py#L316
=> keystonev2: populate user.name into UserInformation

buildman/builder.py, buildman/manager/ephemeral.py, buildman/manager/etcd_canceller.py, buildman/manager/orchestrator_canceller.py, conf/init/02_get_kube_certs.py, data/logs_model/logs_producer/__init__.py, data/model/user.py, data/secscan_model/secscan_v2_model.py, util/ipresolver/__init__.py, util/secscan/analyzer.py, util/secscan/api.py, workers/exportactionlogsworker.py, workers/namespacegcworker.py
Reduce signal to noise ratio in Quay's default logging configuration.
* Only use `info` level logging for information that is useful for system/application administrators and is not internal, implementation-level details.
* Change the build manager to emit `info` level logging instead of `debug` by default.
* Do not use `print()` statements for logging purposes.
- https://issues.redhat.com/browse/PROJQUAY-753
**TESTING**
- Ensure enough useful information is logged.
- Ensure the build manager's logging is not emitting any `debug` log messages.
None.
---
=> [PROJQUAY-753] Reduce logging noise

workers/namespacegcworker.py, workers/queueworker.py, workers/repositorygcworker.py, workers/test/test_namespacegcworker.py
This will ensure that the queue item gets re-queued and the worker is
put to sleep, rather than thrashing on retries
=> Have the GC workers raise a "go to sleep" exception to workers when they fail to acquire a lock

buildman/component/buildcomponent.py, buildman/manager/enterprise.py, buildman/manager/ephemeral.py, buildman/orchestrator.py, buildman/server.py
* Re-raise the exceptions when using the redis orchestrator so that the build manager can handle them.
* Add missing `yield From` on some async calls
* Update the build phase on log failure
* ..
* ..
**TESTING** ->
---
=> Raise Orchestrator errors on redis errors in orchestrator

endpoints/appr/models_cnr.py
This should avoid a `SELECT` query per loaded tag
=> Remove an additional lookup in a tight loop in Appr

data/model/repositoryactioncount.py, workers/repositoryactioncounter.py
This selects only the rows missing, rather than all repositories
=> Fix the RepositoryActionCount worker to properly select rows

data/model/user.py
We only allow ASCII for robot names anyway, so just catch it early
Fixes https://issues.redhat.com/browse/PROJQUAY-807
=> Ensure that all robot lookups are ASCII only

conf/supervisord.conf.jnj, requirements.txt
* Forked supervisor-stdout to handle event message as bytes (original repo looks unmaintained
* Disable builder from starting automatically (for now)
* https://github.com/quay/supervisor-stdout/commit/9bdf630d0d1b4a16cf8b60b96adafb1ed98e7380
* ..
* ..
**TESTING** ->
---
=> Update supervisor-stdout to process event messages correctly.

data/model/repository.py, data/model/repositoryactioncount.py, workers/repositoryactioncounter.py
The RAC worker will now check the count of entries for the day, versus
the number of repos. If all entries are found, the worker will go to
sleep.
=> Have the RAC worker fast-check whether it needs to do work

buildman/component/buildcomponent.py, buildman/manager/ephemeral.py
* Log a warning instead of exception to avoid getting too many Sentry alerts on transient Redis issues.
**TESTING** ->
---
=> Logs a warning instead of exception on some non-critical logs

buildman/component/buildcomponent.py, buildman/server.py
* Handle the case where a buildcomponent's job is None while trying access its id. 
e.g This might happen if the build timeouts, completes or gets canceled while Redis is unavailable.
* ..
* ..
**TESTING** ->
---
=> Handle buildcomponent's job being None

data/cache/impl.py
The PooledCache implementation incorrectly returns `None` instead of
the default if an exception occurs, but `None` is a valid cached value,
so we instead catch the exceptions ourselves now and skip the caching
code if we encounter an exception
Due to: https://github.com/pinterest/pymemcache/blob/54eb398eab4c625bf3696701f27e2a285477e1f5/pymemcache/client/base.py#L1117
=> Turn off ignore_exc in memcache cache to fix an NPE

buildman/manager/executor.py
Python3 is not supported by boto2
* Migrate the buildman's call to aws to use boto3
* ..
* ..
**TESTING** ->
---
=> Migrate to boto3 in the build executor

endpoints/appr/registry.py
Appears that some clients are relying upon the upload mediatype (even though its always the same).
This (partially) reverts commit 75276fd2eeaff9fd31df17bb29be5349c6f392ad.
=> Undo appr automatic 302 redirect

config_app/init/certs_create.sh
**Issue**: https://issues.redhat.com/browse/PROJQUAY-889
**Changelog**:
Added the ability to create certificates based on hostname parsed as an env. variable.
**Docs**:
When starting Quay config app, parse the additional `-e QUAY_CONFIG_HOSTNAME=some.hostname` to assign a CN to the created certificate. If the variable is not present, Quay config app will create default certificates with a bad CN that may not work in all browsers.
**Testing**:
Run Quay config app with -e `QUAY_CONFIG_HOSTNAME=some.hostname`.
**Details**:
n/a
=> PROJQUAY-889 Enable adding of specific CN to certs used by the config app

requirements.txt
**Issue:** https://issues.redhat.com/browse/PROJQUAY-861
**Docs:** 
**Testing:** 
**Details:** This provides a quick fix for https://issues.redhat.com/browse/PROJQUAY-861. We should still eventually migrate from boto2 as it has mostly stopped being supported in favor of boto3
------
=> Repin boto version with python3 fix

util/repomirror/skopeomirror.py, workers/repomirrorworker/test/test_repomirrorworker.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-796
Repository mirroring now copies all images if source is a manifest list.
**Docs:** 
When the source repository is a manifest list, all images in the manifest will be mirrored.
**Testing:** 
Attempt to mirror a known manifest list and confirm all images were copied.
**Details:** 
The change adds the "--all" option to skopeo calls.
------
Changelog: One line description to be added to CHANGELOG.md during release builds. Typically starts with "Added:", "Fixed:", …
=> PROJQUAY-796 - skopeo mirror all manifest list

buildman/component/buildcomponent.py, buildman/manager/ephemeral.py
logging.exception will re-raise the enclosing exception.
Since trollius uses exceptions to yield control of the event loop,
it will complain that the exception was used without `raise`.
**Docs:** 
**Testing:** 
**Details:** 
------
Docs: Detailed description of changes …
=> Change from logging exceptions to warnings

static/js/directives/repo-view/repo-panel-mirroring.js, util/repomirror/skopeomirror.py, workers/repomirrorworker/__init__.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-907
**Docs:** none
**Details:** 
* python3 corrections
* Set initial variable value of vm.syncStartDate allows datepicker to properly store value.
------
Docs: Detailed description of changes necessary to docs.projectquay.io. Examples would be addition of config.yaml, indication of UI changes and screenshot …
=> PROJQUAY-907 - repo mirror initial date

endpoints/secscan.py
Fixes https://issues.redhat.com/browse/PROJQUAY-912
**Issue:** https://issues.redhat.com/browse/PROJQUAY-912
**Changelog:** None
**Docs:** Provide
**Testing:** Start a pre-filled Quay with Clair V4 attached and watch `/secscan/_backfill_status`
**Details:** None
=> Add an endpoint for tracking the secscan backfill

data/model/oci/manifest.py
This changes the lookup to occur outside of the transaction as otherwise
we won't find the manifest that was inserted during the transaction's
view
Fixes https://issues.redhat.com/browse/PROJQUAY-915
**Changelog:** None
**Docs:** None
**Testing:** Push new tags with the same manifest simultaneously from multiple clients and ensure they succeed
**Details:** None
=> Fix lookup of manifests if we detect a duplicate during creation

endpoints/csrf.py, endpoints/test/test_csrf.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-917
**Changelog:** Fix CSRF token encoding in Python 3
**Docs:** n/a
**Testing:** Using any form in the UI, such as creating a User, should no longer fail with a CSRF token error.
**Details:** The CSRF token is being encoded in a way that causes the front-end to incorrectly escape certain sequences contained within the token. This causes CSRF validation to fail as the token created by the back-end and stored in the session does not match what is sent by the browser. This change fixes that issue.
=> [PROJQUAY-917] Fix CSRF token encoding

buildtrigger/bitbuckethandler.py, buildtrigger/customhandler.py, buildtrigger/githubhandler.py, buildtrigger/gitlabhandler.py
The keys are either part of a dict being serialized into json with
json.dumps to pass as a requests' body, or passed directly to the
client(e.g github). In both cases, the value needs to be a str.
**Issue:** https://issues.redhat.com/browse/PROJQUAY-926
**Docs:** 
**Testing:** 
**Details:** 
------
Docs: Detailed description of changes necessary to docs.projectquay.io. Examples would …
=> Handle generated ssh keypairs in build triggers as str

util/repomirror/skopeomirror.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-907
**Docs:** 
**Testing:** 
**Details:** 
The check for empty string to break out of loop was checking the bytes-string instead of the decoded.
------
Docs: Detailed description of changes necessary to docs.projectquay.io. Examples would be addition of config.yaml, indication of UI changes and screenshot impact, and changes in …
=> PROJQUAY-907 - properly check empty string

data/logs_model/datatypes.py, data/logs_model/document_logs_model.py, data/logs_model/elastic_logs.py, data/logs_model/test/mock_elasticsearch.py, data/logs_model/test/test_elasticsearch.py, workers/logrotateworker.py
The current "metadata_json" field is stored as a text field, and
cannot be searched easily. "metadata" will store the given dict as a
dynamically mapped Object type so that its fields can be indexed and searched more easily.
e.g Being able to filter the logs by user agents.
**Docs:** 
**Testing:** 
**Details:** 
------
Changelog: One line description to be added to CHANGELOG.md during release builds. Typically …
=> Add an extra "metadata" field to Elasticsearch logentries

data/registry_model/datatypes.py, data/registry_model/test/test_interface.py
Add missing `@property` decorator on legacy image size handler to fix
the raised exception
=> Fix lookup of tag history sizes

data/registry_model/interface.py, data/registry_model/registry_oci_model.py, data/registry_model/test/test_interface.py, endpoints/v2/manifest.py, util/secscan/test/test_blob_retriever.py
Due to the requirement for the shared empty layer for manifest schema 1,
we need to make sure it is written to the ImageStorage table, even if
the only schemas pushed are version 2
Fixes https://issues.redhat.com/browse/PROJQUAY-948
**Issue:** https://issues.redhat.com/browse/PROJQUAY-948
**Testing:** Push a schema 2 manifest and ensure Clair V4 indexing works
=> Ensure shared blob layers are present on lookup

util/registry/filelike.py, util/registry/test/test_filelike.py
Gunicorn will wrap the wsgi stream in its own wrapper class (see `class Body`).
This class is not compliant with the file-object api from Python (missing `readable`).
This issue never showed up before because of
https://github.com/quay/quay/blob/master/storage/swift.py#L418 always evaluating to `False` in Python2 which
was fixed by https://github.com/quay/quay/pull/508.
**Issue:** https://issues.redhat.com/browse/PROJQUAY-941
**Docs:** 
**Testing:** 
**Details:**
=> Fallback to reading 0 bytes if readable is not implemented.

data/logs_model/document_logs_model.py
Check that "after_datetime" token used for pagination is smaller than the given starting datetime when doing a lookup
**Issue:** https://issues.redhat.com/browse/PROJQUAY-958
**Docs:** 
**Testing:** 
**Details:** Before this, an exception would be raised if the pagination token contained a datetime that is smaller than the given starting datetime. This will return empty logs if that's the case.
=> Handles out of range pagination token datetime

data/registry_model/registry_oci_model.py, storage/local.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-948
**Testing:** 
Enable Clair v4 scanning in Quay which is configured to use local file storage.
**Details:** 
This PR fixes the build regression introduced by https://github.com/quay/quay/pull/511 where  `model.blob.get_or_create_shared_blob` doesn't pass storage argument.
It also fixes the following exception,
```
securityworker stdout | 2020-08-11 06:25:10,280 [106] [ERROR] [workers.worker] Operation raised exception
securityworker stdout | Traceback (most recent call last):
securityworker stdout |   File "/usr/local/lib/python3.6/site-packages/peewee.py", line 6741, in get
securityworker stdout |     return clone.execute(database)[0]
securityworker stdout |   File "/usr/local/lib/python3.6/site-packages/peewee.py", line 4184, in …
```
=> fix: Missing storage argument and type error when calling file.write

buildman/container_cloud_config.py, buildman/templates/dockersystemd.json
Jinja's default is only used if the variable is undefined, not None.
**Issue:** https://issues.redhat.com/browse/PROJQUAY-972
**Docs:** 
**Testing:** 
**Details:** 
------
Testing: …
=> Set default values for templated unit timeout

data/model/repository.py
We now break out of the transaction if the repository already exists,
so that Postgres doesn't raise an error when we try to retrieve the
existing repository
Fixes https://issues.redhat.com/browse/PROJQUAY-973
=> Fix transaction error in postgres on repo create

requirements.txt, storage/azurestorage.py, storage/test/test_azure.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-942
- Update Azure client library to v12
- Increase chunk size when reading stream when uploading to Azure
**Docs:** 
**Testing:** Try pushing/pulling images of different layer sizes to Quay
**Details:** 
Python 3 has some performance issues with the way streams are currently iterated over when uploading data using Azure.
This PR tweaks the chunk size to improve performance on Python 3 to be more comparable to Python 2, and updates the Azure library version used to v12.4.0 from 1.1.0, which handles large files better, and has support for newer Azure API versions.
=> Azure client update

buildman/manager/ephemeral.py, data/logs_model/datatypes.py
Follow-up to  https://issues.redhat.com/browse/PROJQUAY-974
- Reduce the log level from error to warning when falling back on executors.
- Set empty default metadata when trying to serialize to JSON if for some reason it is not set in `LogEntry`.
**Docs:** 
**Testing:** 
**Details:**
=> Reduce log noise from fallbacks in executor

util/repomirror/skopeomirror.py, workers/repomirrorworker/__init__.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-381
Fixed: Mirror of repos with a large number of tags may hang due to buffering skopeo output.
Fixed: When a mirror job is pre-empted, original tags may be deleted. Mirror jobs that are killed are less likely now to remove existing tags.
**Docs:** 
**Testing:** 
* Sync a repo with a lot of tags with debug logging enabled (eg. https://quay.io/repository/bitnami/sealed-secrets-controller ).
* Confirm job succeeds.
* Sync same repo again, cancelling after seeing the first skopeo inspect in the logs.
* Confirm job cancelled and any tags that were being synced are reverted in the tag history.
**Details:** 
A hung mirror job that was either pre-empted or killed would not always rollback the changes. These changes fix the …
=> PROJQUAY-381 - failed mirror tag cleanup

data/logs_model/datatypes.py
Fixes bug from https://github.com/quay/quay/pull/526
**Docs:** 
**Testing:** 
**Details:**
=> json loads fix: given arg should be a str

storage/azurestorage.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-989
- Allow the blobs in azure to be rewritten. This is the same behaviour as in s3. This is necessary for config validation (the same test blob is written to each time storage is validated)
**Docs:** 
**Testing:** 
- Setup quay with the config app with azure
- Try to edit the saved config from the previous setup -> Azure storage should be able to validate 
**Details:**
=> Allow existing blobs to be overwritten in azure

static/js/directives/repo-view/repo-panel-tags.js
**Issue:** https://issues.redhat.com/browse/PROJQUAY-953
Fix UI tags' tracks
**Docs:** 
**Testing:** 
- Push multiple tags with different manifest digests.
- Create new tags from the tags created above -> New tracks should be displayed correctly in the repo tags panel (even after page refresh).
**Details:**
=> Use manifest_digest instead of image_id when accessing current tracks

Dockerfile, Dockerfile.centos7.osbs, Dockerfile.dev, Dockerfile.osbs, Dockerfile.rhel7, Dockerfile.rhel8, dev.df, quay-base.dockerfile
using "--no-cache-dir" flag in pip install ,make sure downloaded packages
by pip don't cached on system . This is a best practice which make sure
to fetch from repo instead of using local cached one . Further , in case
of Docker Containers , by restricting caching , we can reduce image size.
In term of stats , it depends upon the number of python packages
multiplied by their respective size . e.g for heavy packages with a lot
of dependencies it reduce a lot by don't caching pip packages.
Further , more detail information can be found at
https://medium.com/sciforce/strategies-of-docker-images-optimization-2ca9cc5719b6
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
**Issue:** https://issues.redhat.com/browse/PROJQUAY-987
=> PROJQUAY-987 - use `--no-cache-dir` flag to `pip` in dockerfiles, to save space

.github/workflows/CI.yaml, external_libraries.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1020
**Testing:** 
**Details:** 
Looks like cdjs is not happy with the default user-agent string set from python urllib.
=> PROJQUAY-1020 chore: Fix cdnjs download failure(403) by setting custom User-Agent req header

requirements.txt
**Issue:** https://issues.redhat.com/browse/PROJQUAY-833
**Changelog:** Use Pillow to v7.2.0
**Docs:** n/a
**Testing:** n/a
**Details:** Pillow is a dependency used by xhtml2pdf. As xhtml2pdf is not as actively released, this commit manually pins a newer version of Pillow.
=> [PROJQUAY-833] Update Pillow to 7.2.0

endpoints/api/superuser_models_pre_oci.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1011
**Changelog:** Fix attribute used to access build namespace
**Docs:** 
**Testing:** 
- Navigate to Quay UI -> Super user panel -> Build logs -> Get Logs
**Details:**
=> Fix db RepositoryBuild model attribute name used

data/logs_model/table_logs_model.py, endpoints/api/logs.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-675
**Changelog:** Quay expects a month's time range to be 31 days. Using weeks limited the maximum time range to 28 days since a week is equivalent to 7 days only. Use days instead of weeks to represent a month's range. 
**Docs:** 
**Testing:** Try and export logs for the past n days where 28 < n < 32.
**Details:**
=> Use days instead of weeks to represent a month worth of time

util/secscan/v4/api.py, workers/securityworker/securityworker.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1055
none
**Docs:** 
none
**Testing:** 
Upload image to quay then watch `securityworker` logs (or clair logs) to confirm that after first scan, the image is not rescanned again. Prior to this fix, all manifests would be eligible for rescan after 5 minutes.
**Details:** 
The response "etag" header, by RFC, is a string that includes surrounding double quotes. Later comparison of data pulled from db would have these quotes stripped. Solution is to save string value w/o the quotes.
=> PROJQUAY-1055 - correct reindexing due to hash compare

image/oci/manifest.py, image/oci/test/test_oci_manifest.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1002
Fixes: FEATURE_EXPERIMENTAL_HELM_OCI_SUPPORT properly registers OCI layers
**Docs:** 
none
**Testing:** 
Using helm-3.3.0
```
helm registry login myquay
helm create mychart
helm package ./mychart
helm chart save mychart myquay/myname/mychart:v1
helm chart push myquay/myname/mychart:v1
helm chart remove myquay/myname/mychart:v1
help chart pull myquay/myname/mychart:v1
```
**Details:** 
------
Changelog: One line description to be added to CHANGELOG.md during …
=> PROJQUAY-1002 - properly register helm oci type

tools/generatekeypair.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1101
Pull-request title must start with "PROJQUAY-1101 - Add binary mode to generatekeypairs.py"
/tools/generatekeypair.py
**Docs:** 
**Testing:** 
**Details:** 
Need to add 'b' to the file open mode in line 26 (as referenced in Ivan B's article to set Quay into read-only: https://access.redhat.com/articles/5411111)
=> Added binary mode

config.py, data/secscan_model/secscan_v4_model.py, util/config/schema.py, util/secscan/v4/api.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-847
**Changelog:** Adds JWT support to ClairV4 client.
**Docs:** Two new config values are introduced. These values must be documented and will determine how Quay uses JWT to Clair.
**Testing:** Start Quay with new config values and confirm requests do not fail with http 401
**Details:**  PR Implements JWT signing toward ClairV4 directly in Quay. This eliminates the need for JWT Proxy.
=> sec: implement jwt signing to ClairV4

data/users/externalldap.py
**Issue:** 
- https://issues.redhat.com/browse/PROJQUAY-822
**Changelog:**
- security: Modified an LDAP logging statement to exclude potentially sensitive data.
**Docs:**
- n/a
**Testing:**
Run Quay with LDAP integration and DEBUG=true. When logging in, one should see a log line similar to the following:
```
2020-10-05 23:56:01,460 [24247] [DEBUG] [data.users.externalldap] Found matching DNs: ['uid=euclid,dc=example,dc=com']
```
**Details:** 
Exclude potential passwords and other sensitive data from a given LDAP logging statement.
=> [PROJQUAY-822] security: Hide sensitive LDAP log values

endpoints/secscan.py, util/security/jwtutil.py
this commit adds jwt verification to the notifications post endpoint.
Signed-off-by: ldelossa <ldelossa@localhost.localdomain>
**Issue:** https://issues.redhat.com/browse/PROJQUAY-847
**Changelog:** Verify JWT from Clair notification request
**Docs:** The "SECURITY_SCANNER_V4_PSK" config value being defined enforces jwt verification for all endpoints Clair V4 will request.
**Testing:** Use the test notifier in Clair V4's repo and start the Quay local dev environment. Update both configs to use a PSK.
**Details:** 
------
Changelog: One …
=> notifications: add incoming jwt verification

.github/workflows/CI.yaml
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1141
**Docs:** none
**Details:** 
Announced on October 1st, [set-env is being deprecated](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) and we've started to see warnings in various workflow runs that use it. I noticed you use it here, and wanted to offer a quick fix. I tested it out for my own workflow (thanks @jzelinskie for the tip!) [here](https://github.com/vsoch/django-oci/runs/1244736538?check_suite_focus=true) if you want to see if it works as expected to compile the conformance.test binary.
=> GitHub Actions set-env deprecation

workers/test/test_securityscanningnotificationworker.py
**Issue:** N/a
**Changelog:** N/a
**Docs:** N/a
**Testing:** N/a
**Details:** Skips the test when running against MySQL because it's flaky.
=> Skip Security Scanner Notification Worker Test

Dockerfile, conf/init/certs_install.sh
**Issue:** https://issues.redhat.com/browse/PROJQUAY-516
**Docs:** none
**Details:** 
In python3 the `requests` package now uses the cacert.pem provided through `certifi`
=> PROJQUAY-516 - requests no longer needs cacert.pem

conf/init/certs_create.sh
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1131
**Docs:** none
**Details:** 
The / dir is not writable in ubi8 so instead use /tmp for creating jwtproxy mitm certs (/tmp/certificates).
=> PROJQUAY-1131 - use /tmp for created certs

buildman/manager/ephemeral.py, external_libraries.py
Make sure to cleanup the the existing scheduled executor whenever the build is marked as incomplete and falls back to the next configured executor, if it has retries remaining. This avoid having duplicate executor for the same build, which can cause performance issues and cause an executor's control plane reach capacity.
=> Quayio builder chores

.flake8, .github/workflows/CI.yaml, tox.ini
**Issue:** 
n/a
**Changelog:**
- Use Python 3.8 for running tests in CI
- Show Flake8 data
**Docs:** 
n/a
**Testing:** 
n/a
**Details:**
n/a
=> fix: Use Python 3.8 for CI tests

buildman/manager/executor.py, buildman/templates/cloudconfig.json
Used by the manager to schedule builds based on the current running
count. Uses the specific executors' api to get the count of running
builders instead of Redis/Orchestrator.
This is due to issues encountered in the past where the manager would
have problems scheduling builds, and go into a weird state when
Redis was unavailable.
Remove wamp's REALM parameters from executor
Remove asyncio from executor
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1169
=> Implement executor methods to get the count of running builders

health/services.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1163
jwtproxy no longer required, removed from /health endpoint
**Docs:** 
TODO: Update health endpoint examples
**Testing:** 
Confirm jwtproxy status not present
**Details:** 
jwtproxy no longer used for secscan
=> PROJQUAY-1163 - remove jwtproxy from /health

data/model/user.py, util/security/test/test_token.py, util/security/token.py, util/test/test_useremails.py
**Issue:**
- https://issues.redhat.com/browse/PROJQUAY-1190
- fix: Use Python3 strings for user-facing tokens
**Docs:**
- n/a
**Testing:**
- Ensure recovery emails can be sent without a Python string concatenation error
**Details:** 
Addresses the following error when attempting to send recovery emails:
```
gunicorn-web stdout |     send_recovery_email(email, confirmation_code)
gunicorn-web stdout |   File "/quay-registry/util/useremails.py", line 167, in send_recovery_email
gunicorn-web stdout |     action = GmailAction.view("Recover Account", "recovery?code=" + token, "Recovery of an account")
gunicorn-web stdout | TypeError: can only concatenate str (not "bytes") to str
```
=> [PROJQUAY-1190] fix: Use Python3 strings for user-facing tokens

buildman/manager/ephemeral.py
`terminate_executor` is already being called after _mark_job_incomplete
=> Reverts ephemeral.py in f7e175d8

util/useremails.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1191
**Changelog:** add: log sent emails (debug)
**Docs:** When Quay is configured in such a way where `TESTING: true` or otherwise ends up in a testing configuration, emails are not actually sent. However, debug-level logging will show that those messages would have been sent.
**Testing:**
- With `DEBUGLOG=True`, trigger a user-registration confirmation email. The following line should show up in the logs: `[util.useremails] Sent email: '[Project Quay] Please confirm your e-mail address'`. The email **should be** sent successfully.
- Following the previous step, specify `TESTING: true` in the `config.yaml` file and run through the same process. The following line should be written to the logs: `[util.useremails] Quay is configured for …
=> [PROJQUAY-1191] add: log sent emails (debug)

data/users/externalldap.py, test/test_ldap.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1273
none
**Docs:** 
none
**Testing:** 
Login w/ LDAP and confirm working
**Details:** 
LDAP is returning bytes-like fields
=> PROJQUAY-1273 - ldap bytes-like strings

buildman/manager/executor.py, buildman/templates/cloudconfig.json
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1255
-  The http scheme is specified as a dial option on the grpc Go client, not as part of the address.
=> Removes the http scheme from the server address

data/registry_model/registry_oci_model.py, data/secscan_model/secscan_v4_model.py, data/secscan_model/test/test_secscan_v4_model.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1292
none
**Docs:** 
none
**Testing:** 
Push manifest list and see it is not scanned (no errors in securityworker logs)
**Details:** 
securityworker was erroring from assert, causing images not to be scanned. Error was result of a manifestlist making it to scanner. Both situations corrected.
=> PROJQUAY-1292 - do not scan manifest lists

data/users/externalldap.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1258
none
**Docs:** 
none
**Testing:** 
Able to login w/ ldap
**Details:** 
Changes in python3 ldap
=> PROJQUAY-1258 - correct ldap python3 call

data/migrations/env.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-813
**Changelog:** fix: Schema migrations with MySQL/MariaDB and SSL
**Docs:** 
- MySQL certificates now require the server's hostname or IP to be specified in both the SAN (Subject Alternative Names) and CN (Common Name) due to changes in Python >= 3.7.
**Testing:** 
- Ensure Quay can successfully run migrations when using a MySQL/MariaDB database with SSL enforced.
**Details:** 
- Alembic, the package responsible for performing schema migrations, does not share the same database connection as Quay. The config.yaml configuration portion to specify a CA bundle and other MySQL-specific SSL options are now passed to the connection used by Alembic.
- The schema migration code has been cleaned up a bit and currently unused/unsupported …
=> [PROJQUAY-813] fix: Schema migrations with MySQL and SSL

buildman/container_cloud_config.py, buildman/manager/executor.py, buildman/qemu-coreos/build.sh, buildman/templates/cloudconfig.json, buildman/templates/dockersystemd.json
Allow specifying the container runtime in the executor's ignition
file. This allow for different runtimes, e.g Docker, Podman to run a build.
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1295
**Docs:** 
**Testing:** 
**Details:**
=> Allow specifying the container runtime to the templated ignition file

config.py, static/directives/service-keys-manager.html
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1264
none
**Docs:** 
none
**Testing:** 
Confirm links visit valid pages
**Details:** 
Point links to docs.projectquay.io
=> PROJQUAY-1264 - correct doc links

data/database.py, util/metrics/prometheus.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1358
Add some metrics to Peewee:
- Connections in `PooledDatabase`s
- `connect`/`close` calls counts
Example: ![Screen Shot 2020-12-09 at 10 45 15 AM](https://user-images.githubusercontent.com/2530351/101652037-bde6c180-3a0b-11eb-9414-ec1322de16f8.png)
**Docs:** 
**Testing:**
=> Add metrics to app instance's peewee connection pool

endpoints/api/repoemail.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1366
- Code for e-mail verification is removed in response from `sendAuthorizeRepoEmail` endpoint. 
**Docs:** 
**Testing:** 
- Current tests for email notification auth is found here -> `endpoints/api/test/test_repoemail_models_pre_oci.py `
**Details:** 
------
=> PROJQUAY-1366

buildman/manager/ephemeral.py, buildman/manager/executor.py
* Handle non 200 api response from executors
* Allows the CA cert to be specified in the config for server verification
Allow the CA cert used for server verification to be specified in the
config even if client certificate authentication is not used.
Handles non-200 responses from executors when trying to get worker count.
**Docs:** 
**Testing:** 
**Details:** 
------
Changelog: One line description to be added …
=> PROJQUAY-1376 - Handle non 200 api response from executors (#619)

buildman/qemu-coreos/Dockerfile, buildman/qemu-coreos/start.sh
Create the working directory/change permissions, ownership in the
dockerfile instead of at runtime to avoid permission issues when
running the entrypoint script.
**Docs:** 
**Testing:** 
**Details:**
=> Update QEMU dockerfile.

buildman/qemu-coreos/Dockerfile, buildman/qemu-coreos/start.sh
Create the working directory/change permissions, ownership in the
dockerfile instead of at runtime to avoid permission issues when
running the entrypoint script.
**Docs:** 
**Testing:** 
**Details:**
=> Update QEMU dockerfile. (#626)

buildman/manager/executor.py, buildman/server.py, buildman/templates/cloudconfig.json
Generate the ignition template used by the builder using the correct
externally exposed secured GRPC port (55443).
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1393
**Docs:** 
**Testing:** 
**Details:**
=> PROJQUAY-1393 - Use correct nginx port in ignition template

buildman/manager/executor.py, buildman/server.py, buildman/templates/cloudconfig.json
Generate the ignition template used by the builder using the correct
externally exposed secured GRPC port (55443).
**Docs:** 
**Testing:** 
**Details:**
=> Use correct nginx port in ignition template (#628)

buildman/manager/executor.py, buildman/templates/cloudconfig.json
When set to true, DEBUG will prevent the build nodes from shutting
down after the quay-builder service is done or fails, and will prevent the
build manager from cleaning up the instances (terminating EC2
instances or deleting k8s jobs).
This will allow debugging builder node issues, and should not be set
in a production environment.
The lifetime service will still exist. i.e The instance will still
shutdown after ~2h (EC2 instances will terminate, k8s jobs will
complete)
Setting DEBUG will also affect ALLOWED_WORKER_COUNT, as the
unterminated instances/jobs will still count towards the total number
of running workers.
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1397
**Docs:** 
**Testing:** 
- Set DEBUG to True in the executor(s)' config
- Start a build from Quay
- …
=> PROJQUAY-1397 - Add a DEBUG flag to the executors to prevent cleanup

buildman/manager/executor.py, buildman/templates/cloudconfig.json
When set to true, DEBUG will prevent the build nodes from shutting
down after the quay-builder service is done or fails, and will prevent the
build manager from cleaning up the instances (terminating EC2
instances or deleting k8s jobs).
This will allow debugging builder node issues, and should not be set
in a production environment.
The lifetime service will still exist. i.e The instance will still
shutdown after ~2h (EC2 instances will terminate, k8s jobs will
complete)
Setting DEBUG will also affect ALLOWED_WORKER_COUNT, as the
unterminated instances/jobs will still count towards the total number
of running workers.
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1397
**Docs:** 
**Testing:** 
**Details:**
=> Add a DEBUG flag to the executors to prevent cleanup (#631)

Dockerfile
**Changelog:**  Use Centos Stream in Dockerfile
**Docs:**  n/a
**Testing:** Ensure Quay still works correctly when running within `Dockerfile`
**Details:** Centos 8 will be EOL after 2021. Centos Stream is the proposed solution. As there is not currently a Centos Stream image available, as far as I can see, I simply followed the [official steps to change from Centos 8 to Centos Stream](https://www.centos.org/centos-stream/). I also switched the image from Dockerhub to the [Centos registry](https://registry.centos.org/centos/centos) to avoid Dockerhub-related pull/build issues.
=> Use CentOS Stream in Dockerfile

buildman/qemu-coreos/start.sh
Newer version of qemu will return a non-zero error when --shrink is not set when resizing an image.
- Add `--shrink` to the qemu-img resize command
**Docs:** 
**Testing:** 
**Details:**
=> Add a --shrink flag when resizing the qemu image.

buildman/qemu-coreos/start.sh
Newer version of qemu will return a non-zero error when --shrink is not set when resizing an image.
**Docs:** 
**Testing:** 
**Details:**
=> Add a --shrink flag when resizing the qemu image. (#635)

storage/swift.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1391
- Removed to_bytes function on return object. 
- Fixed bug with pulling from swift storage
**Docs:** 
- N/A
**Testing:** 
- Tested push/pull to swift storage on a local environment as well as with the operator. 
**Details:** 
------
=> PROJQUAY-1391

buildman/qemu-coreos/start.sh, buildman/templates/cloudconfig.json
- Prevent shrinking builder vm image, as that might truncate existing partitions. If the configured volume size is smaller than the default vdisk size, the image will not be resized.
**Docs:** 
**Testing:** 
**Details:**
=> PROJQUAY-1392 prevent over shrinking vm image

buildman/templates/cloudconfig.json, buildman/templates/dockersystemd.json
Occasional DNS resolution issue would happen when running `podman
login` if network-online.target was not a prerequisite for quay-builder.service
- Start `quay-builder.service` only after `network-online.target`
**Docs:** 
**Testing:** 
**Details:**
=> Make sure network is up before starting the quay-builder systemd service

buildman/manager/executor.py
If `SERVER_HOSTNAME` and `BUILDMAN_HOSTNAME` are served under the same host, the gRPC service will be exposed at `SERVER_HOSTNAME:55443`.
If that's not the case, then `BUILDMAN_HOSTNAME` _should_ include the port at which the service is being served.
For example, `BUILDMAN_HOST:443` for an Openshift `Route`
- Keep port to gRPC endpoint if `BUILDMAN_HOSTNAME` is set. 
**Docs:** 
**Testing:** 
**Details:**
=> Don't replace port by default 55443 if BUILDMAN_HOSTNAME is defined

buildman/manager/ephemeral.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1441
- Remove extra param not needed in `commit_sha` call when a private key is used during a build
**Docs:** 
**Testing:** 
**Details:**
=> Remove extra extra parameter when calling commit_sha

buildman/manager/ephemeral.py
Update the log level from EXCEPTION to WARNING when getting a KeyError
from the orchestrator to avoid geetting a traceback. The KeyError is valid and happens when a build
has expired.
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1438
- Log missing build duration metrics key as a warning instead of an exception
**Docs:** 
**Testing:** 
**Details:**
=> Update log level when unable to write build duration metrics to a WARNING

config.py, util/config/configutil.py, workers/repomirrorworker/__init__.py
Set `REPO_MIRROR_SERVER_HOSTNAME` to a value instead of None in order to
match the defined json schema for the config.
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1499
- Set default `REPO_MIRROR_SERVER_HOSTNAME` value to `SERVER_HOSTNAME` instaed of `None`
**Docs:** 
**Testing:** 
**Details:**
=> Set default REPO_MIRROR_SERVER_HOSTNAME value to match SERVER_HOSTNAME

tox.ini
- Update container name + move docker specific configuration to the same section.
- Update postgres healthcheck command to use pg_isready
(cherry picked from commit 32d7063315481b8159413d1a425c9a331fb9dae4)
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1549
=> Update tox.ini for tox-docker v2.0.0 (#669)

config.py, util/config/configutil.py, util/config/schema.py, workers/repomirrorworker/__init__.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1562
Revert #667 . It wrongly assumed that `REPO_MIRROR_SERVER_HOSTNAME` shouldn't be null given the previous config schema. `REPO_MIRROR_SERVER_HOSTNAME` _can_ be null and should have the same value as `SERVER_HOSTNAME` if not explicitly set.
- Reverts #667 
- Allow `REPO_MIRROR_SERVER_HOSTNAME` to be null in the jsonschema
**Docs:** 
**Testing:** 
**Details:**
=> PROJQUAY-1562 repo mirror config schema

storage/swift.py, storage/test/test_swift.py, util/registry/filelike.py
- Allow any binary stream (IOBase, including Werkzeug's LimitedStream) to Swift's type assertion
- Allow LimitingStream from util.registry.filelike to seek backward, since it is required by the Swift client in order to retry operations, if it is configured to do so
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1508
- Update use of `_pyio` to `io` (`io` is implemented in C instead of pure Python) in Swift's implementation
- Fix Swift storage allowed stream types
- Fix Swift storage connection retries
**Docs:** 
**Testing:** 
**Details:**
=> Fix Swift assertion for chunked upload

data/users/__init__.py, requirements-osbs.txt, requirements.txt, util/security/aes.py, util/security/secret.py, util/security/test/test_secret.py
Since we're already using the `cryptography` package elsewhere, there is no need to have 2 different crypto packages as dependencies.
**NOTE**: `pycryptodome` is still needed for `pyjwkest`, but the latter (https://github.com/IdentityPython/pyjwkest) is not being maintained anymore, so we should eventually move it to some other JOSE library:
- https://github.com/mpdavis/python-jose or 
- https://github.com/latchset/jwcrypto
**Issue:** 
- https://issues.redhat.com/browse/PROJQUAY-1619
- https://issues.redhat.com/browse/PROJQUAY-224
- Use `cryptography` instead of `pycryptodome` for AES
**Docs:** 
**Testing:** 
- Generate an encrypted password with a version of Quay using `cryptography` -> encrypted password should work using `docker login`
- Generate an encrypted password …
=> Deprecate use of pycryptodome for AES

static/partials/update-user.html
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1519
Pull-request title must start with "PROJQUAY-1519 - "
* Use `registry-name` instead of `registry-title` as the class directive
=> Use registry-name instead of registry-title as registry directive

Dockerfile.osbs
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1409
none
**Docs:** 
none
**Testing:** 
none
**Details:** 
nodejs not needed in final container build stage
=> PROJQUAY-1409 - remove nodejs from final container

conf/init/d_validate_config_bundle.sh
**Issue:** 
Not tracked by JIRA (N/A)
N/A
**Docs:** 
N/A
**Testing:** 
Script is called during Quay startup.
**Details:** 
Error occurs if `$IGNORE_VALIDATION` is set:
`line 12: [: missing ]'`
=> Fixed typo in if statement

config.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1705
Pull-request title must start with "PROJQUAY-1705 - "
* Made Helm support enabled by default on Quay
**Testing:** 
Please follow this document for testing Helm support in Quay: https://www.openshift.com/blog/quay-oci-artifact-support-for-helm-charts
=> PROJQUAY-1705 Enable Helm by default on Quay

static/directives/repo-count-checker.html
**Issue:** n/a
**Changelog:** Fixed: removed spurious whitespace in repo-count-checker
**Docs:** n/a
**Testing:** I have not been able to emulate this exact scenario in a test instance of quay.  From observation I'm confident that the whitespace is removed as expected.
**Details:** when repo-count-checker.html is called for "isUserNameSpace", there is an embedded newline between the two ng-if lines that ends up causing a spurious space between the phrase and the comma.
**Screenshot:**
=> Whitespace error fixed in repo-count-checker.html

endpoints/api/secscan.py, endpoints/api/test/test_secscan.py
Allow the auth flow to use basic auth on the secscan api resource when
FEATURE_ANONYMOUS_ACCESS (e.g CSO uses pull secrets to fetch secscan
resources)
This will still not allow anonymous acces to the secscan api resource (no auth)
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1128
**Docs:** 
**Testing:** 
- set `FEATURE_ANONYMOUS_ACCESS` to `false`
- Try querying the secscan api with basic auth -> should succeed
- Try querying the secscan api with auth token -> should succeed
- Try querying the secscan api with no auth -> should fail with 401
- set `FEATURE_ANONYMOUS_ACCESS` to `True`
- Try querying the secscan api with basic auth -> should succeed
- Try querying the secscan api with auth token -> should succeed
- Try querying the secscan api with no auth -> should …
=> PROJQUAY-1128 - Allow basic auth on the secscan api endpoint when anonymous api resource is set.

data/model/oci/tag.py, data/registry_model/label_handlers.py, data/registry_model/registry_oci_model.py, data/registry_model/test/test_interface.py
Apply a manifest's `quay.expires-after` label expiry value to new tags pointing
to that existing manifest. Before, that label would be only applied when the
manifest was created, and new tags targeting that manifest would not
have the manifest's corresponding expiry value set.
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1713
- Fix issue where new tags targeting an existing manifest would not have manifest's `quay.expires-after` label applied
**Docs:** 
**Testing:** 
- Push an image with a valid `quay.expires-after` label/value -> the tag used should have the corresponding expiration
- Create another tag pointing to the same manifest -> the new tag should also have an expiration
- NOTE: this should work for using both the registry api and tags api to create the tag …
=> tags: apply tag expiry to created tags pointing to existing manifest

data/model/oci/tag.py, data/registry_model/label_handlers.py, data/registry_model/registry_oci_model.py, data/registry_model/test/test_interface.py
Apply a manifest's "quay.expires-after" label expiry value to new tags pointing
to that existing manifest. Before, that label would be only applied at when the
manifest was created, and new tags targeting that manifest would not
have the manifest's corresponding expiry value set.
(cherry picked from commit 79faf5f3679b3ac416c13b70f9fd101d496a6eef)
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1713
=> PROJQUAY-1713 - cherry-pick - apply tag expiry to created tags

storage/cloud.py
Explicitly call abort on a mpu if no bytes were written.
Noobaa and Rados will not clean the artifacts, resulting in empty
files being stuck in an "uploading" state.
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1123
- Explicitly abort MultipartUpload where no bytes were uploaded
**Docs:** 
**Testing:** 
**Details:**
=> storage: abort unfinished mpu when no bytes are written

buildman/builder.py
Add missing module import from logging package
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1795
- Add missing module import from logging package
**Docs:** 
**Testing:** 
**Details:**
=> chore: import missing logging.config module

storage/cloud.py
The way it was formatted (with the top-level parentheses), the extra
comma was causing the connection parameters to be passed as a 1-tuple
instead of a string.
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1787
- Fix formating issue resulting in tuple instead of string
**Docs:** 
**Testing:** 
**Details:**
=> format: remove extra comma from s3 connect_kwargs

storage/cloud.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1803
**Docs:** 
**Testing:** 
- test push/pull on s3 us-east-2, us-east-1
- test push/pull on other cloud storage
**Details:** 
us-east-2 does not support signature v2
=> PROJQUAY-1803 - specify S3 signature version

util/locking.py, workers/gc/gcworker.py, workers/namespacegcworker.py, workers/repositorygcworker.py
Correctly converts the given ttl from seconds to milliseconds when
passed to Redis (redlock uses 'px', not 'ex'). Also increase the lock
timeout of gc workers to 1 day.
Some iteration, for repos with large numbers of tags (1000s), will
take more than 15 minutes to complete. This change will prevent multiple
workers GCing the same repo, and one possibly preempting
another. GlobalLock's ttl will make the lock available again when
expired, but will not actually stop execution of the current GC
iteration until the GlobalLock context is done. Having a 1 day timeout
should be enough.
NOTE: The correct solution would have GlobalLock should either renew
the lock until the caller is done, or signal that it is no longer
valid to the caller.
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1823
=> gc: fix GlobalLock ttl unit and increase gc workers lock timeout

data/model/gc.py, workers/gc/gcworker.py, workers/namespacegcworker.py, workers/queueworker.py, workers/repositorygcworker.py
Prevents the queueworker from setting the event to stop the poll_queue
job when a WorkerSleepException is raised. On WorkerSleepException,
the worker should instead skip this iteration (go to sleep). e.g when
the NamespaceGCWorker can't acquire a lock because it is already taken
by some other worker.
Reverts the gcworkers job timeout from 24h to 3h. In case of a
deadlock between processes (for example, redeploying the app will not
clear the existing Redis keys), 24h is too long waiting for the locks to
expires so that the workers can resume work.
Add missing Counter increment for on row deletion on the Manifest table.
=> queueworker: prevent stop event on WorkerSleepException (PROJQUAY-1857)

util/locking.py, workers/queueworker.py, workers/test/test_exportactionlogsworker.py
By default, Redlock creates a new client per instance. Using the
provided factory allows Redlock to reuse a single connection per
instance and avoid running out of connections. e.g When a worker tries
to get a lock, it should not open new connections every time.
Increase sleep duration between queue polls on
WorkerSleepException. This will give more time before retrying after
failing to acquire a lock.
=> lock: reuse redis client when creating locks (PROJQUAY-1872)

util/locking.py, workers/blobuploadcleanupworker/blobuploadcleanupworker.py, workers/gc/gcworker.py, workers/globalpromstats/globalpromstats.py, workers/logrotateworker.py, workers/namespacegcworker.py, workers/repositorygcworker.py
GlobalLock had a dependency on app, which would cause a circular
dependency if imported from the main app. Workaround this by requiring
to pass the configuration to the GlobalLock instead (this is done by a
classmethod, due to the use of Redlock's factory). This means before
the use of GlobalLock, "configure" will need to be called once, per process.
=> lock: allows global lock to be used from main app (PROJQUAY-788)

data/cache/__init__.py, data/cache/impl.py, data/cache/test/test_cache.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-788
**Changelog:** Add model cache implementation backed by Redis.
**Docs:** N/a
**Testing:** Add the following section to `config.yaml`:
```yaml
DATA_MODEL_CACHE_CONFIG:
engine: redis
host: <redis-hostname>
port: 6379
```
**Details:** Adds an implementation of the model cache which uses Redis. The goal is when deploying a cluster of Quay app containers, they will all use a shared Redis instance for caching requests (as opposed to a per-container memcache), which will reduce load on the database for expensive queries. [Enhancements proposal](https://github.com/quay/enhancements/blob/main/enhancements/redis-cache.md).
*NOTE:* When using this model cache implementation, the Redis dependency changes from being low priority (effectively …
=> Redis Model Cache (PROJQUAY-788)

data/model/user.py
This was already fixed in `master` but not in the quayio branch, and is preventing the namespacegcworker from correctly reporting its metrics.
=> quayio: returns value from delete_user calls

data/cache/__init__.py, data/cache/impl.py, data/cache/test/test_cache.py
Remove GlobalLock from Redis model cache implementation in
favor of 'nx=True' when setting the key.
Signed-off-by: Alec Merdler <alecmerdler@gmail.com>
=> cache: remove GlobalLock from redis model cache (PROJQUAY-1902)

deploy/openshift/quay-app.yaml
Adds a new deployment quay-app-canary to the deployment YAML file. This
will be picked up AppSRE when deploying quay.io. The canary deployment
can have a different image than the main deployment and can point to a
differnt config secret.
=> Add Quay canary deployment manifest

deploy/openshift/quay-app.yaml
This change adds the parameter IMAGE_TAG_CANARY to the deployment
file quay-app.yaml to use a different image tag for the canary
deployment
=> deployment: Add image tag param to the deploy file (PROJQUAY-1896)

data/model/blob.py, data/model/image.py, data/model/oci/blob.py, data/model/oci/manifest.py, data/model/storage.py, data/model/test/test_gc.py, data/model/test/test_image_sharing.py, data/registry_model/manifestbuilder.py, data/registry_model/test/test_blobuploader.py, data/registry_model/test/test_interface.py, tools/orphans.py, util/verifyplacements.py
The "uploading" column is an artifact from depending on writing to the
Image table (see BlobUpload table instead). As of 3.4, Quay no longer
writes to that table, and is only needed until quayio moves away from
Clair v2, after which work to remove "glue" code and fully deprecate
the Image table (amongst other tables) can start.
This is done as a separate commit from the actual migration so that it
can be cherrypicked.
=> chore: remove uploading filtering from imagestorage queries

data/migrations/dba_operator/909d725887d3-databasemigration.yaml, data/migrations/versions/909d725887d3_add_composite_index_on_manifestblob.py
Adds composite index manifestblob_repository_id_blob_id.  From our
testing on the quay.io production DB, This increased the number of rows
filtered for the manifestblob & imagestorage join slow query from 1.8%
to 100%
=> migration: Add composite index in manifestblob (PROJQUAY-1922)

oauth/base.py, oauth/test/test_oidc.py
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1335
**Changelog:** Add timeout to OAuth token exchange to avoid ECONNRESET from RH SSO.
**Docs:** N/a
**Testing:** `tox`
**Details:** Attempting to log into to quay.io using Red Hat SSO would occasionally result in an `HTTP 404`/`HTTP 502` response from the server. Exception logging revealed this to be the result of a `ECONNRESET` when sending a `POST` request to the SSO service for token exchange. As this is a problem in a service we do not control, our only option is to be more defensive on Quay's side. Adding a timeout here should alleviate this problem.
=> Add Timeout and Retry To OAuth Token Exchange (PROJQUAY-1335)

config.py, data/cache/__init__.py, data/cache/cache_key.py, data/cache/impl.py, data/cache/test/test_cache.py, data/registry_model/registry_oci_model.py, data/registry_model/test/test_interface.py, endpoints/appr/models_cnr.py, endpoints/appr/registry.py, endpoints/v2/catalog.py, endpoints/v2/test/test_blob.py
Adds a configuration option to modify the cache expiry timeout
for ModelCache objects
=> modelcache: Make ModelCache TTL configurable

data/model/blob.py, data/model/oci/manifest.py, data/model/storage.py, data/registry_model/registry_oci_model.py, endpoints/api/image.py, endpoints/verbs/__init__.py, util/secscan/analyzer.py
Removes uploading filters/asertions that were not removed when cherripicking 1fd8194e.
These changes were not in the original PR to master to begin with, which is why they didn't raise a merge conflict.
=> quayio: followup to 1fd8194e

storage/cloud.py
Explicitly call abort on a mpu if no bytes were written.
Noobaa and Rados will not clean the artifacts, resulting in empty
files being stuck in an "uploading" state.
=> PROJQUAY-1123 (3.5.2)

data/cache/__init__.py, data/cache/impl.py, data/cache/test/test_cache.py
Adds `read_client` and `write_client` for Redis ModelCache to seperate out read
and write calls to separate on endpoints
=> modelcache: Add read and write endpoints to Redis (PROJQUAY-1939)

data/cache/__init__.py, data/cache/impl.py, data/cache/test/test_cache.py
Adds `read_client` and `write_client` to Redis ModelCache to separate out read
and write calls to different endpoints
=> modelcache: Add read and write endpoints to Redis (PROJQUAY-1939) (#795)

util/jsontemplate.py, util/test/test_jsontemplate.py
> This is my first contribution to quay. I tried my best to follow the CONTRIBUTING.md guide, but I guessed on a lot of things.
Matching multiples caused exceptions to be raised. This made it so webhook notification POST bodies could not template things like the image tags as `${tags[*]}`. This was caused by a typo in the jsonpath_rw match field that was used.
I encountered this when trying to use the notification system in quay.io and decided to dig through the code to understand why it didn't work. I did not find a relevant Jira ticket about this, so I just created this PR without a Jira ticket.
Signed-off-by: Kalle Jillheden <kalle.jillheden@iver.se>
=> util: fix matching multiples in jsontemplate.py

buildman/qemu-coreos/start.sh
Reference correct filename in start.sh
=> buildman: fix vm image name in startup script (PROJQUAY-2120) (#811)

requirements-osbs.txt
Downstream build requires requirements-osbs.txt to be fully dep complete.
=> build: add full python build dependencies (PROJQUAY-2216)

templates/base.html
Cherrypicks 1c157e2a:
- Correctly converts Python bool to JS when templating the value of
config flag with Jinja.
=> templates: escape templated script value (PROJQUAY-970) (#828)

util/backfillreplication.py
utility: Fixes backfillreplication script to use manifest blobs (PROJQUAY-2218)
Fixes an issue where the backfill replication script was using the `image` table and not the `manfiestblob` table which is being used since Quay 3.4.x exclusively.
JIRA: https://issues.redhat.com/browse/PROJQUAY-2218
=> utility: Fixes backfillreplication script to use manifest blobs (PROJQUAY-2218)

deploy/openshift/quay-recovery-endpoint.yaml
This change adds the deployment and service manifests for the recovery endpoint
that will be used for quay.io to recover accounts which have not already been
transitioned to RH SSO
=> deploy: Add recovery endpoint deployment manifests (PROJQUAY-970)

buildman/manager/executor.py, buildman/templates/cloudconfig.json
Adds the ability to define proxy variables for builders. The proxy variables are parsed as env. variables and defined in Quay's config.yaml file.
=> buildman: Add proxy variables to builds if they exist (PROJQUAY-2120)

Dockerfile
- Fixed group permissions on $QUAYCONF folder
- Fixed config-tool build step
=> dockerfile: Fix $QUAYCONF symlink and config-tool build in refactored Dockerfile (PROJQUAY-2254)

buildman/manager/executor.py, buildman/templates/cloudconfig.json
buildman: Add proxy variables to builds if they exist (PROJQUAY-2120) (#834)
Adds the ability to define proxy variables for builders. The proxy variables are parsed as env. variables and defined in Quay's config.yaml file.
=> Cherrypick f5b9492a

config.py, data/secscan_model/secscan_v2_model.py, util/secscan/v4/api.py
Handle the case where a layer might be remote (not hosted in Quay's
storage) and add the remote blob url instead of the storage's download
url.
=> secscan: handle remote layer url when sending request to Clair

Dockerfile.osbs, conf/init/certs_install.sh
- Allow PYTHONUSERBASE_SITE_PACKAGE to be added as an environment variable
- Set PYTHONUSERBASE_SITE_PACKAGE to /usr/local/lib/python3.8/site-packages in downstream Dockerfile
=> dockerfile: Fix downstream python site-packages location (PROJQUAY-2258)

static/directives/repo-view/repo-panel-settings.html, static/js/directives/repo-view/repo-panel-settings.js
Added confirmation form when deleting a repository. The user must type in namespace/repo in order to delete repository. See images below:
@kurtismullins 
@josephschorr
=> Confirmation prompt on repo deletion

data/secscan_model/__init__.py, data/secscan_model/secscan_v2_model.py, data/secscan_model/secscan_v4_model.py
Handles the case where a V2 scanner is not configured (noop
implementation) and the proxy model tries to load security information
that has not been indexed in V4 yet. In such case, the noop
implementation of the V2 scanner should return a COULD_NOT_LOAD
status (instead of None, to comply to the secscan model interface),
and ignore the fallback to V2, and finally just return the V4
status (NOT_YET_INDEXED)
=> secscan: handle proxy model fallback to noop v2 (PROJQUAY-2289)

data/secscan_model/__init__.py, data/secscan_model/secscan_v2_model.py, data/secscan_model/secscan_v4_model.py
Handles the case where a V2 scanner is not configured (noop
implementation) and the proxy model tries to load security information
that has not been indexed in V4 yet. In such case, the noop
implementation of the V2 scanner should return a COULD_NOT_LOAD
status (instead of None, to comply to the secscan model interface),
and ignore the fallback to V2, and finally just return the V4
status (NOT_YET_INDEXED)
=> secscan: handle proxy model fallback to noop v2 (PROJQUAY-2289) (#847)

data/cache/__init__.py
Look for "rediscluster" instead of "redis-cluster" in the cache config.
=> chore: fix rediscluster cache config key name cherry-pick 0999b (PROJQUAY-2101)

app.py, conf/nginx/server-base.conf.jnj, config.py, data/test/test_userfiles.py, endpoints/api/repository.py, endpoints/api/test/test_repository.py, endpoints/appr/registry.py, endpoints/v1/index.py, endpoints/v2/v2auth.py, endpoints/web.py, image/docker/schema1.py, path_converters.py, requirements-osbs.txt, requirements.txt, static/js/pages/new-repo.js, static/js/quay-routes.module.ts, static/partials/new-repo.html, test/fixtures.py, test/registry/protocol_fixtures.py, test/registry/protocol_v1.py, test/registry/registry_tests.py, util/config/schema.py, util/names.py, util/test/test_names.py
Allows forward slashes to be used in repository names according to
https://docs.docker.com/docker-hub/repos/.
NOTE: This change simply allows the use of "/" in repository
names needed for certain Openshift use cases. This does not implement
any new permission model for nested paths. i.e A repository with a
nested path is treated as a single repository under a _single_
namespace.
=> registry: add support for extended repository names (PROJQUAY-1535)

data/cache/redis_cache.py
Fix compaitbily with the py2 quayio branch. move the kwargs at the
end of the call
=> cache: py2 compatibility, kwargs after named args (PROJQUAY-2101)

data/cache/redis_cache.py
Fix compaitbily with the py2 quayio branch. move the kwargs at the
end of the call
=> cache: py2 compatibility, kwargs after named args (PROJQUAY-2101) (#859)

oauth/oidc.py, static/js/quay-routes.module.ts
Unlike Flask, Angular does not use weights to match paths to routes,
so order matters. In order to support repository with "/" in them, we
previously added "*" to the repository name named group, allowing it
to capture subsequent "/". When that's the case, it is important that
to general "catch-all" route comes after the more specific routes (e.g
repo manifest). Otherwise, Angular will just eagerly use the first
route that matches a path, even though it may have "better" match in
subsequent routes.
e.g - '/api/v1/repository/:namespace/:name*'
- '/api/v1/repository/:namespace/:name*\/tag/:tag'
In this case, something like
/api/v1/repository/devtable/testrepo/tag/testtag would match the
first route, even though if using a weighted system, the second
route in most case be a better fit.
=> ui: change angular routing order for repo paths (PROJQUAY-2325)

config.py
Includes Helm and Cosign layers as default allowable oci types.
=> config: define default oci artifact types

config.py
Includes Helm and Cosign layers as default allowable oci types.
(cherry picked from commit c507eeff2eae61efe1a18a4b0e6addce4d37bc5a)
=> config: define default oci artifact types (PROJQUAY-2334) (#877)

static/js/services/notification-service.js
**Fixes:**
Fix an invalid link in the "too many private repository" notification you can see in this screen recording.
**Screen recording of the broken link:**
**See also**
The changed path matches the definition in `quay-routes.module.ts`. See:
* https://github.com/quay/quay/blob/3dde364615ae3f2b839fb38b7e791805e4243c3c/static/js/quay-routes.module.ts#L98-L99
* https://github.com/quay/quay/blob/3dde364615ae3f2b839fb38b7e791805e4243c3c/static/js/quay-routes.module.ts#L107-L108
=> PROJQUAY-2329: Fix links to billing in private repo notification

Dockerfile, local-dev/Dockerfile
As to avoid breaking the installation of our requirements.
See https://github.com/vlasovskikh/funcparserlib/issues/69 for details.
Also fixes it on `local-dev/Dockerfile`.
=> dockerfile: pin setuptools to version 57 (PROJQUAY-2520)

notifications/notificationmethod.py
Make sure the Quay key/cert pair (ssl.key + ssl.cert) have been
mounted/exists whenever it tries sending a webhook request with client
cert. If that's not the case, then the webhook is sent without client
cert. This can happen when TLS is not handled by the Quay container,
in which case these certs are not required by default in the Quay
container.
=> notification: check certs exists for webhooks (PROJQUAY-2424)

data/secscan_model/secscan_v4_model.py
If Clair returns an error the current behaviour is to
error out, thus not indexing any subsequent manifests.
This change allows the worker to continue indexing
subsequent manifests after one failure.
=> secscan: continue iterating after failure

data/secscan_model/test/test_secscan_v4_model.py
Follow-up to 694fa2ac. Correctly set the expected value for the
pagination token when not blocking on a failed API request.
=> secscan: fix secscan api ApiRequestFailure test (PROJQUAY-2563)

CHANGELOG.md, Dockerfile, data/secscan_model/secscan_v4_model.py, data/secscan_model/test/test_secscan_v4_model.py, requirements-osbs.txt, requirements.txt
If Clair returns an error the current behaviour is to
error out, thus not indexing any subsequent manifests.
This change allows the worker to continue indexing
subsequent manifests after one failure.
=> secscan: continue iterating after failure (PROJQUAY-2563)

.github/workflows/CI.yaml
This pins the distribution-spec repo: https://github.com/opencontainers/distribution-spec to a specific sha
to prevent OCI CI failing because of a recent change in the source test: https://github.com/opencontainers/distribution-spec/pull/296/files 
=> ci: pin oci test to a specific sha

.github/workflows/CI.yaml, notifications/notificationmethod.py, requirements-osbs.txt, requirements.txt
Cherrypicks:
- a126ad06
- c7c4c0dc
- 45f3687b (Addressed by PROJQUAY-2570)
=> notification: check certs exists for webhooks (PROJQUAY-2424) (#886)

.github/workflows/CI.yaml, requirements-osbs.txt, requirements.txt
Aplly patch by kleesc, see https://github.com/quay/quay/commit/c7c4c0dc4ca9681482a100a831950355634c3b61
~@kleesc do we also need to apply the changes relating to [quay/mockldap](https://github.com/quay/quay/commit/c7c4c0dc4ca9681482a100a831950355634c3b61#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R4)?~ the test run answered it(👍
=> fix: update funcparserlib and oci check

scripts/app_sre_post_deploy_rhel7.sh
Update to use `docker-archive` for skopeo as `docker-daemon` is
not supported in rhel8 build nodes
=> build: Use docker-archive for post-deploy script  (PROJQUAY-2372)

conf/nginx/server-base.conf.jnj
This should ameliorate PROJQUAY-1228.
Signed-off-by: Hank Donnay <hdonnay@redhat.com>
**Issue:** https://issues.redhat.com/browse/PROJQUAY-1228
**Changelog:** yes
**Docs:** no
**Testing:** yes please
**Details:** Not totally sure how to test.
=> PROJQUAY-1228: nginx: use bigger http/2 chunks for blobs

data/billing.py
Type hints have become built-in since python 3.5
Python 3 code crashes here
```
Traceback (most recent call last):
File "/quay-registry/conf/init/data_migration.py", line 3, in <module>
from app import app
File "/quay-registry/app.py", line 34, in <module>
from data.billing import Billing
File "/quay-registry/data/billing.py", line 1
from __future__ import annotations
^
SyntaxError: future feature annotations is not defined
```
=> billing: Remove annotations for type hints in billing (PROJQUAY-2777)

data/migrations/versions/04b9d2191450_add_oci_content_types.py
Skip inserts during migration if the mediatypes were already added previously.
=> migration: skip existing mediatype inserts (PROJQUAY-2811)

requirements.txt
Addresses https://github.com/gevent/gevent/issues/1513. Upgrades
gevent, greenlet and gunicorn.
=> chore: bump gevent related packages' version (PROJQUAY-2821)

config.py, storage/basestorage.py, storage/cloud.py, storage/distributedstorage.py, storage/test/test_cloud_storage.py, util/config/schema.py, workers/blobuploadcleanupworker/blobuploadcleanupworker.py, workers/blobuploadcleanupworker/test/test_blobuploadcleanupworker.py
Currently blobs leftover in the uploads directory during cancelled uploads do not get cleaned up since they are no longer tracked. This change cleans up the uploads storage directory directly.
=> blobuploadcleanupworker: Add cleanup for orphaned blobs (PROJQUAY-2313)

Dockerfile
- Fix symlink in upstream dockerfile
E2E tests are failing because this is missing from `redhat-3.6` branch
=> dockerfile: Update symlink in upstream dockerfile (PROJQUAY-2550) (#889)

setup.cfg
Downstream build uses Cachito which needs setup.cfg for
installing python dependencies
originally added on redhat-3.7, see https://github.com/quay/quay/pull/946
=> build: Add required setup.cfg for downstream build (PROJQUAY-2713)

setup.cfg
Downstream build uses Cachito which needs setup.cfg for
installing python dependencies
originally added on redhat-3.7, see https://github.com/quay/quay/pull/946
=> (3.6 backport) build: Add required setup.cfg for downstream build (PROJQUAY-2713)

setup.cfg
Downstream build uses Cachito which needs setup.cfg for
installing python dependencies
originally added on redhat-3.7, see https://github.com/quay/quay/pull/946
=> (3.5 backport) build: Add required setup.cfg for downstream build (PROJQUAY-2713)

requirements-osbs.txt
it's already on requirements-dev.txt (and not on requirements.txt), so
it shouldn't be on the osbs requirements either.
=> chore: remove fakeredis from osbs requirements

requirements-osbs.txt
it's already on requirements-dev.txt (and not on requirements.txt), so
it shouldn't be on the osbs requirements either.
can't build downstream with fakeredis present.
=> remove fakeredis from osbs requirements (#996)

conf/init/nginx_conf_create.py, conf/nginx/http-base.conf, conf/nginx/nginx.conf.jnj
Support client ip from x-forwarded header. This is needed if one of
the intermediate proxy between the client and Quay does not support
proxy protocol.
If set, FEATURE_PROXY_PROTOCOL will use the L4 feature. If not, say,
when a L7 proxy is used, fallback to using x-forwarded-for, and allow
specifying trusted ip/cidr for Nginx.
=> nginx: support client ip through x-forwarded-for header (PROJQUAY-2883)

deploy/openshift/quay-app.yaml, deploy/openshift/quay-py3-app.yaml
This is required to support ALB. Without this service, the
default ELB endpoints forces the L4 proxy procotol which makes
Nginx see all the remote client IP as the IP of ALB. If the
request goes through an ELB without proxy-protocol enabled,
Nginx will parse the X-Forwarded-For header to get the remote
IP
=> deploy: Add LB service with no proxy-protocol (PROJQUAY-2883)

config.py, storage/basestorage.py, storage/cloud.py, storage/distributedstorage.py, storage/test/test_cloud_storage.py, util/config/schema.py, workers/blobuploadcleanupworker/blobuploadcleanupworker.py, workers/blobuploadcleanupworker/test/test_blobuploadcleanupworker.py
Currently blobs leftover in the uploads directory during cancelled uploads do not get cleaned up since they are no longer tracked. This change cleans up the uploads storage directory directly.
=> blobuploadcleanupworker: Cleanup for orphaned blobs (PROJQUAY-2313)

data/model/oauth.py
AuthorizationProvider uses explicit parameter names when it calls its methods. Therefore methods of derivative classes, i.e. the methods of the class DatabaseAuthorizationProvider, should have the same parameter names.
=> oauth: Fix OAuth authorization code grant type (PROJQUAY-781)

data/model/oauth.py, endpoints/web.py
OAuth Authorization Code Flow is broken in quay. Code
Flow is more secure than implicit flow and is used
by server side applications to get the access token
=> auth: Fix oauth code flow (PROJQUAY-781)

data/buildlogs.py
single_connection_client keeps a connection open to the pool on init
which may cause issues if the master changes
=> builders: Make single_connection_client conifgurable (PROJQUAY-3025)

requirements.txt
These outdated packages were preventing the upstream image from
starting correctly.
=> deps: upgrade upstream requirements.txt package versions

Dockerfile, Dockerfile.deploy, requirements.txt
Dockerfile.deply is used for quay.io
=> build: Update pyrsistent to fix Dockerfile.deploy (PROJQUAY-3125)

storage/cloud.py, storage/test/test_cloud_storage.py
Boto3 behaves unexpectedly when the resource client is not set to use
the correct region. Boto3 can't seem to correctly set the
X-Amz-Credential header when generating presigned urls if the region
name is not explicitly set, and will always fall back to us-east-1.
To reproduce this:
- Create a bucket in a different region from us-east-1 (e.g
eu-northeast-1)
- Create a boto3 client/resource without specifying the region
- Generate a presigned url
This seems to be a DNS issue with AWS that only happens shortly after
a bucket has been created, and resolves itself eventually. 
Ref:
- https://github.com/boto/boto3/issues/2989
- https://stackoverflow.com/questions/56517156/s3-presigned-url-works-90-minutes-after-bucket-creation
To workaround this, one can specify the bucket endpoint,
either …
=> storage: allow configuration of storage region for cloud storage (PROJQUAY-3082)

Dockerfile, data/model/repo_mirror.py, endpoints/api/mirror.py, endpoints/api/test/test_mirror.py, static/directives/repo-view/repo-panel-mirroring.html, static/js/directives/repo-view/repo-panel-mirroring.js, static/js/directives/ui/logs-view.js, util/repomirror/skopeomirror.py, workers/repomirrorworker/__init__.py, workers/repomirrorworker/test/test_repomirrorworker.py
Currently when attempting to mirror a registry containing unsigned images the mirror will fail due to not finding the source signature. This is caused by the updated version of Skopeo blocking unsigned images by default. This allows users to specify the ability to pull unsigned images per-repository. The Skopeo version is also now pinned.
=> imagemirror: Add unsigned registries mirror option (PROJQUAY-3106)

requirements.txt
There is a bug in botocore which causes issues with signing
requests with awsv4. Latest version of Boto fixes it
https://github.com/boto/botocore/issues/2358 gives more context
=> builders: Update boto to fix signature error (PROJQUAY-2542)

Dockerfile, requirements.txt
- Specify Python38
- bump Pillow to 9.0.1
=> dockerfile: ubi8 requires python38, otherwise installs 3.6 by default (PROJQUAY-3148)

requirements-osbs.txt
also remove testing related dependencies
backports https://github.com/quay/quay/pull/1069
=> [cherry-pick 3.6] requirements-osbs.txt: remove ipython and related deps (#1069)

buildman/manager/executor.py
These username + password are only necessary if the quay-builder image is private, and should be optional
=> buildman: allow use of public builder image (PROJQUAY-3179)

storage/cloud.py
This parameter causes signature validation errors on the client side.
We don't store encrypted blobs so we don't really need this param.
=> Remove ServerSideEncryption param from presigned URL (PROJQUAY-3180)

requirements-osbs.txt
* Adds previously removed but required downstream dependencies
=> requirements-osbs.txt: Add missing deps for Cachito (PROJQUAY-3177)

data/userevent.py
This fixes the crash in the `/realtime` endpoint for testing user
events
=> realtime: decode byte to string before using split (PROJQUAY-3180)

CHANGELOG.md
Changelog has only been updated on `redhat-3.6` branch since automation was introduced. This PR brings `master` up to date.
=> Bump changelog to 3.6.2

deploy/openshift/quay-py3-app.yaml
Add an environment variable to the deployment to disable config
validation
=> deploy: Add ignore validation for py3 deployment (PROJQUAY-2542)

setup.py
Allows for exporting Quay modules via source to be reused in other tools. Current exported packages only support exporting database modules to keep package size low.
=> setup: Export Quay modules (PROJQUAY-3181)

data/secscan_model/datatypes.py, data/secscan_model/secscan_v2_model.py
Omit metadata field if not defined.
=> secscan: ClairV2 datatype compatibility (PROJQUAY-3279)

buildman/manager/ephemeral.py, buildman/orchestrator.py
Allow the build to move forward if it is already in the desired
phase/state. When a build fails, ang gets retried from the queue, its
phase doesn't get updated back to WAITING. So it is possible that it
is already in a phase such as SCHEDULED, which could prevent the
buildman from marking the new attempt as scheduled, as there would be
no aparent changes made to the build phase.
=> buildman: fix multiple build retries phase (PROJQUAY-3281)

buildman/buildmanagerservicer.py, buildman/interface.py, buildman/manager/ephemeral.py
Make sure the build token doesn't expire before the builder instance does.
=> buildman: Set build token expiration to builder's lifetime (PROJQUAY-3281)

app.py, image/docker/schema1.py, image/oci/manifest.py, image/oci/test/test_oci_manifest.py, util/security/v2_signing_key.py
Currently if an image with an OCI manifest is requested and the client does not support Docker Schema 2 or OCI manifests it will default to returning an unsigned Docker V2 Schema 1 manifest. Older clients who send a `application/vnd.docker.distribution.manifest.v1+prettyjws` media type header expect a signed Docker V2 Schema 1 manifest and break when an unsigned manifest is recieved. This change defaults to returning a signed manifest for OCI images if the `application/vnd.docker.distribution.manifest.v1+prettyjws` is present before falling back to an unsigned manifest.
=> schema1: Permit signed schema1 manifests during conversion (PROJQUAY-3285)

buildman/manager/executor.py, buildman/templates/cloudconfig.json
If not set, TimeoutStartSec for the Docker service is set to
600. Since it's a service of type oneshot, this should either not be
set, or at least the length of the machine's lifetime.
=> buildman: prevent systemd oneshot service from timing (PROJQUAY-3304)

config.py, util/config/schema.py
The flag `CREATE_REPOSITORY_ON_PUSH_PUBLIC` is not referenced anywhere in the code. This PR removes it along with its entry in the schema.
=> chore: Remove unneeded flags fromt he config schema (PROJQUAY-3309)

data/secscan_model/secscan_v4_model.py
For larger databases like quay.io the default batch
size is too high to complete the job in a resonable
time. Make the batch_size configurable so we can
adjust how many scans can be in-flight for a worker
=> secscan: make batch_size configurable (PROJQUAY-3287)

config.py
Handle nested transaction when trying to catch InterfaceError from
pymsql/mysql's idle connections. If the connection is already in a
transaction, then we'll assume it doesn't need to be closed
beforehand, as it's probably in-use, and unlikely to be cleaned up.
=> database: handle nested transaaction when trying to close before transaction (PROJQUAY-3303)

.github/workflows/build-and-publish.yaml
- Enable workflow dispatch for the build and publish job
- This is a requirement to call the workflow from releases repository
=> ci: Enable workflow dispatch for build and publish (PROJQUAY-3310)

data/cache/redis_cache.py, static/directives/repo-view/repo-panel-tags.html, static/js/directives/repo-view/repo-panel-tags.js
Display individual manifest size in manifest list view.
Also fixes a non-cluster Redis cache bug.
TODO: This requires making extra individiual requests to get the
children manifests. They should probably be cached.
=> ui: display manifest list manifest sizes (PROJQUAY-3196)

buildman/manager/executor.py, buildman/templates/cloudconfig.json, buildman/templates/dockersystemd.json
Changes made to allow use of a single quay-builder image for kubernetes and kubernetesPodman builds.
Implements the following changes:
- Added EXECUTOR env var to kubernetsPodman job configuration
- Updated the builder ignition config to overwrite the registry.conf file to set short name mode to permissive
- Always run the quay-builder in the VM as root
=> buildman: Add EXECUTOR parameter (PROJQUAY-3278)

requirements-osbs.txt, requirements.txt
Upgrade to py3 broke py-bitbucket which is the
bitbucket API wriapper. This was fixed in
https://github.com/quay/py-bitbucket/pull/2
=> builders: Update py-bitbucket to fix bitbucket triggers (PROJQUAY-3362)

util/invoice.py
Migrating to py3 broke invoices. xhtml2pdf returns `bytes` instead of `str`
=> billing: use BytesIO when rendering invoice (PROJQUAY-3267)

buildman/jobutil/buildjob.py, buildman/manager/ephemeral.py, buildman/manager/executor.py
Making the following changes:
- Adding JOB_REGISTRATION_TIMEOUT to take effect on generating the build registration token. 
- Adding the DEBUG option to the kubernetesPodman executor.
- Fixed issue logging out cached tag
=> builders: Add DEBUG and JOB_REGISTRATION_TIMEOUT options (PROJQUAY-3395)

conf/nginx/rate-limiting.conf.jnj
The values are based on the traffic numbers on quay.io for specific
endpoints
=> nginix: update rate limit values for quay based on traffic (PROJQUAY-3283)

endpoints/api/superuser_models_interface.py, endpoints/api/superuser_models_pre_oci.py
Build logs in the superuser admin panel do not show up. Errors out due to some syntax errors on the backend which this PR resolves.
- Checks for presence of `resource_key` before constructing archive URL
- Correctly passes a `RepositoryBuildTrigger` object to `BuildTriggerHandler.get_handler()`
=> superuser: Fix display of build logs (PROJQUAY-3404)

config.py
Media type required for pushing cosign attestations to the registry as described in the following document.
https://github.com/sigstore/cosign/blob/92ce88e0fa077b50de9f9fe8772cdc893d58ca38/specs/ATTESTATION_SPEC.md#overall-layout.
=> config: Allow envelope mediatype (PROJQUAY-3386)

Dockerfile
- Update config-tool version from v0.1.10 to v0.1.11
=> config: Update config-tool to v0.1.11 (PROJQUAY-3318)

static/directives/repo-tag-history.html, static/directives/tag-operations-dialog.html, static/js/directives/repo-view/repo-panel-tags.js, static/js/directives/ui/manifest-link/manifest-link.component.html, static/js/directives/ui/repo-tag-history.js, static/js/directives/ui/tag-operations-dialog.js
Remove docker id references from ui. Tags should now be referencing
the manifest it is pointing to
.
=> ui: remove deprecated docker-image-id references from ui (PROJQUAY-3418)

static/directives/build-logs-view.html, static/directives/super-user-build-logs.html, static/partials/build-view.html
Currently when viewing the build logs and selecting `Copy Logs` the copy to clipboard will fail. This is because the content of the logs was being passed to the copy-clipboard function when it requires the ID of the element containing the text to copy. This passes the selector of the ID of the element containing the build logs.
=> ui: Copy build logs error fix (PROJQUAY-3405)

data/registry_model/registry_proxy_model.py, endpoints/v2/test/test_blob.py, proxy/__init__.py, proxy/fixtures.py, proxy/test_proxy_e2e.py
also uses blob uploader to upload the blob to storage.
[PROJQUAY-3459](https://issues.redhat.com/browse/PROJQUAY-3459)
=> proxy: don't store entire blob in memory when caching

bill-of-materials.json, requirements-osbs.txt, requirements.txt
* Removes `aiowsgi`, which required `waitress`
* Follow up to https://github.com/quay/quay/pull/1202
```
vagrant@ibm-p8-kvm-03-guest-02 ~/git/forks/quay/quay (fix/remove_aiowsgi) $ docker exec -it -u root quay-quay bash -c "pip3 freeze | grep aiowsgi"
vagrant@ibm-p8-kvm-03-guest-02 ~/git/forks/quay/quay (fix/remove_aiowsgi) $ docker exec -it -u root quay-quay bash -c "pip3 freeze | grep waitress"
```
=> chore: Remove unused dep (PROJQUAY-3437) 

data/cache/cache_key.py, endpoints/v2/__init__.py, proxy/__init__.py
also add upstream registry to proxy cache key. if a user changes their
mind about what registry to proxy, we shouldn't try to reuse the token.
----
this can be tested by setting up a proxy org and specifying the wrong credentials for the proxied registry. see https://gist.github.com/flavianmissi/48a7bd19270fd12876c488fa3332fb3b#proxy--auth-for-quayio-namespace for step-by-step setup
the client should see something like:
```
Error: initializing source docker://quay:8080/fmissi-cache/busybox-v2s1:latest: reading manifest latest in quay:8080/fmissi-cache/busybox-v2s1: unknown: Error requesting upstream registry: Failed to get token from 'https://quay.io/v2/auth?service=quay.io&scope=repository:fmisse/busybox-v2s1:pull', 429
```
(in my case I'm getting a 429 due to too many attempts to login …
=> endpoints/v2: handle generic proxy related errors

buildman/orchestrator.py
This fixes the crash:
DataError: Invalid input of type: 'NoneType'. Convert to a bytes, string, int or float first.
This is happening because we access a value of a key which has expired
=> builders: add a check for expired key (PROJQUAY-3489)

Makefile, requirements-osbs.txt, requirements.txt
* First step in getting rid of `requirements-osbs.txt`
* Updates versions in `requirements-osbs.txt` to match `requirements.txt`
* Adds support for docker-compose v1 to `make local-docker-rebuild`
* Removes `funcparserlib` - looks unused
* Adds some additional build dependencies
=> chore: Align requirements files (PROJQUAY-3184)

requirements-osbs.txt, requirements.txt
* Fixes Cachito issue with PyPDF2 `PyPDF2-1.26.0.tar.gz does not include metadata (there is no PKG-INFO file)`
=> chore: Fix cachito issue with pypdf (PROJQUAY-3184)

requirements-osbs.txt, requirements.txt
* Bumps Cython version as required by `wheel` `ERROR: Could not find a version that satisfies the requirement Cython>=3.0a9 (from versions: 0.29.23)`
=> chore: Bump cython version (PROJQUAY-3184)

conf/nginx/rate-limiting.conf.jnj
Current rate limits for list tags is too high and causing
issues in quay.io reduce it to saner limits
=> nginx: Update rate limiting for tags API (PROJQUAY-3283)

data/secscan_model/secscan_v4_model.py, data/secscan_model/test/test_secscan_v4_model.py
Have the securityworker send an abort signal in the case where the
conditions for indexing a manifest are not met after running the
candidate query. This could be when:
- a manifest has a reference to a manifestsecuritystatus instance
- the manifestsecuritystatus reindex threshold is no longer
valid (because it was recently updated)
This signals that another worker overlapped, and allows the current
worker to move on to the next set.
=> secscan: fix database manifest allocator for securityworker (PROJQUAY-3501)

data/model/namespacequota.py
for non-cache orgs, get_namespace_size will almost never be called for
an org with no manifests.
for cache orgs, get_namespace_size is garanteed to be called once when
the org doesn't have any manifests: a first pull from a cache org will
ensure that.
this change does not negatively affect callers, as no callers rely on
get_namespace_size to return None.
fixes [PROJQUAY-3538](https://issues.redhat.com/browse/PROJQUAY-3538)
=> namespacequota: return 0 when namespace has no size yet

proxy/__init__.py
Example trying to pull a private image after having configured a proxy org without any credentials:
fixes [PROJQUAY-3553](https://issues.redhat.com//browse/PROJQUAY-3553)
=> proxy: make upstream related error message more actionable

data/database.py, data/migrations/versions/d94d328733e4_increase_repomirrorconfig_char_size.py
Increases the maximum length of `external_registry_username` and
`external_registry_password` fields from `2048` to `4096`. Some registries,
e.g ECR, issue a token to be used as password, whose length is longer
than 2048 after being encrypted and base64 encoded. Since JWT's specs
do not specify a maximum length, we set the combined max length of
these fields to approximately 8K, the default header size on most
servers (including nginx), since these credentials will be passed in a
auth header during the auth flow.
=> mirror: increased registry user/pass max length (PROJQUAY-2712)

data/secscan_model/secscan_v4_model.py, util/metrics/prometheus.py, util/secscan/v4/api.py
Add histogram for request duration on indexer service. Add random
batch to manifest iterator to reduce duplicate work while manifests
are being backfilled.
=> secscan: add indexer service request duration metric (PROJQUAY-3501)

buildman/manager/executor.py
Setting the backoffLimit to 1 for kubernetes and kubernetesPodman builds. Prevents subsequent attempts from failing due to the token expiring. Having the job recreate pods is unnecessary as the build manager already has the retry logic.
=> builders: Set backoffLimit to 1 (PROJQUAY-3587)

conf/nginx/nginx.conf.jnj, conf/nginx/rate-limiting.conf.jnj
There are scripts calling the v1/tags API for helium miner
causing an DB load
=> nginx: block v1/tag for helium miner curl calls (PROJQUAY-3594)

requirements-osbs.txt, requirements.txt
Bumps:
* boto3
* botocore
* oslo.utils
* pypdf2
* requests
* urllib3
Resolves the following CVEs
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-26137
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-0718
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-33503
=> chore: Bump python dependencies (PROJQUAY-2175)

storage/azurestorage.py, storage/test/test_azure.py
Allows Azure endpoints other than global, such as `accountname.blob.core.usgovcloudapi.net`.
=> storage: allow arbitrary endpoint url for azure storage (PROJQUAY-891)

data/secscan_model/secscan_v4_model.py, data/secscan_model/test/test_secscan_v4_model.py, requirements-osbs.txt, requirements.txt, setup.py, util/locking.py, workers/securityworker/securityworker.py
Acquire lock on recent manifests batch to prevent multiple workers
from working on the same set.
=> secscan: optimize deduplicating manifests for indexing in securityworker (PROJQUAY-3501)

data/secscan_model/__init__.py, data/secscan_model/interface.py, data/secscan_model/secscan_v2_model.py, data/secscan_model/secscan_v4_model.py
Add `index_manifests` as part of secscan interface. `index_manifests` is
a superset of perform_indexing, but also indexes a batch of recent manifests.
=> secscan: update the secscan model interface (PROJQUAY-3501)

app.py
fixes [PROJQUAY-3591](https://issues.redhat.com//browse/PROJQUAY-3591)
----
```
quay-quay  | gunicorn-web stdout | 2022-04-20 08:20:46,917 [194] [DEBUG] [app] Ending request: 
urn:request:327c9b42-841b-464b-8970-ab063f199b59 (/api/v1/organization/cache-quayio/validateproxycache) 
{'endpoint': 'api.proxycacheconfigvalidation', 'request_id': 'urn:request:327c9b42-841b-464b-8970-ab063f199b59', 
'remote_addr': '172.23.0.1', 'http_method': 'POST', 'original_url': 'http://quay/api/v1/organization/cache-quayio
/validateproxycache', 'path': '/api/v1/organization/cache-quayio/validateproxycache', 'parameters': {}, 'json_body': 
{'org_name': 'cache-quayio', 'expiration_s': 86400, 'insecure': False, 'upstream_registry': 'quay.io', 
'upstream_registry_username': '[FILTERED]', …
```
=> app.py: filter proxy cache login details from debug logs

buildman/manager/executor.py
In the previous kubernetes executor the build job was persisted in DEBUG mode due to the virtual machine in the pod never exiting. This kept the job alive for users to view the debug information. The `kubernetesPodman` executor does not run the VM so it will be cleaned up due to `ttlSecondsAfterFinished` being set on the job. This change prevents the `ttlSecondsAfterFinished` field from being set when DEBUG is true, allowing the pod to stay alive to retrieve the logs.
=> builders: Persist build pod when DEBUG is true (PROJQUAY-3710)

_init.py, docker-compose.yaml
* Configures version to be pulled from an environment variable. Falls back to existing behavior if variable isn't set.
=> init: Add support for QUAY_VERSION env variable (PROJQUAY-3514)

data/registry_model/registry_proxy_model.py, proxy/__init__.py, proxy/test_proxy.py
The distribution spec does not require the docker-content-digest header
to be set in response to a manifest GET/HEAD request.
This changes both the proxy client and the registry proxy model to
correctly check whether a manifest is up-to-date with the upstream
registry or not when no digest header is received.
NOTE: when checking staleness against registries that do not return the
docker-content-digest header, Quay will make a GET request to the
registry and calculate the digest from the manifest itself. GET requests
usually count towards rate-limiting.
This change also sets the accept-encoding header to 'identity'. The python
requests library seems to automatically set the accept-encoding header to
'gzip'. Dockerhub ignores that header when serving blobs, but some
registries don't (namely …
=> PROJQUAY-3750: support registries that do not return a digest header

static/js/pages/superuser.js, static/partials/super-user.html
=> Quota UI: Adding Overall storage consumption for Super users panel page (PROJQUAY-3639)

endpoints/v2/test/test_v2auth.py, endpoints/v2/v2auth.py
Currently when Quay is set to automatically create organizations it will check the user table for a matching username with organization set to true. This causes conflicts when a user already exists with the same username, where the check will fail and Quay will attempt to create an organization with the same name as the user. This change checks for only a matching username.
=> v2auth: Check for user before creating org (PROJQUAY-3766)

oauth/services/rhsso.py
- Do not pass certificate in verify parameter, instead load automatically from extra_ca_certs dir
=> sso: Use trusted cert from extra_ca_certs directory (PROJQUAY-2056)

util/secscan/api.py
Update the https proxy scheme from "https" to "http". The scheme was
ignored prior to urllib3 1.26, which is why it was working.
https://github.com/psf/requests/issues/5943#issuecomment-926615360
https://github.com/quay/quay/pull/1250/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R131
=> secscan: update https proxy scheme

data/registry_model/registry_proxy_model.py, data/registry_model/test/test_registry_proxy_model.py, data/registry_model/test/testdata.py
the previous code relied on manifests always having a single manifest
list as their parent, which is false.
fixes https://issues.redhat.com/browse/PROJQUAY-3818
---
NOTE: pull by digest of a manifest that is not part of a manifest list does not update related tag(s). I'll confirm with PM that we also want to update the tag expiration in this cases, and if so report it as a bug separately.
=> pull-thru: bump expiration of all parent manifest lists on pull

_init.py, docker-compose.yaml
* Cherry pick of https://github.com/quay/quay/pull/1298
* Enables `QUAY_VERSION` environment variable
=> [redhat-3.6] chore: Add support for QUAY_VERSION env variable (PROJQUAY-3514)

Dockerfile, docker-compose.yaml
Also add nginx module before installing it, without this dnf won't find it.
Note that we're using ubi8/node-10, which is deprecated - but this is
the version previously installed (before the nodejs package disappeared
on us).
=> Dockerfile: use nodejs ubi8 image to build frontends

conf/init/certs_install.sh
Make sure the script still works when mounting certs as a read-only fs.
=> init: ensure a newline is present before appending certs (PROJQUAY-3881)

static/directives/manage-users-tab.html, static/js/directives/ui/manage-user-tab.js, static/js/directives/ui/quota-management-view.js
Should resolve [PROJQUAY-3920](https://issues.redhat.com/browse/PROJQUAY-3920).
Logged in as Superuser - `admin`
Logged in as Superuser - `admin2`
When `QUOTA_MANAGEMENT` feature is enabled:
When `QUOTA_MANAGEMENT` feature is disabled:
=> UI: Superuser user panel settings icon permissions fix (PROJQUAY-3905)

requirements.txt
fixes some warnings as well as adds supports for flask 2.
---
Changelogs: https://github.com/flask-restful/flask-restful/blob/v0.3.9/CHANGES.md#versopn-039
=> requirements.txt: bump flask-restful from 0.3.7 to 0.3.9

static/css/core-icons.css, static/css/directives/repo-view/repo-panel-tags.css, static/directives/repo-view/repo-panel-tags.html, static/js/directives/repo-view/repo-panel-tags.js, static/js/directives/ui/cosign-link/cosign-link.component.html, static/js/directives/ui/cosign-link/cosign-link.component.ts, static/js/pages/repo-view.js, static/js/quay.module.ts
This adds basic UI support for handling cosign-style signature artifacts separately from regular tags. Filters cosign signature tags from the tag view by default but allows them to be revealed. Visually annotates signed images and provides additional links and information about to the signature artifact in the expanded manifest view. Also allows to select signed vs. unsigned tags and cosign signature artifacts from the tag dropdown filter.
=> ui: basic support for cosign in the UI (PROJQUAY-3965)

workers/blobuploadcleanupworker/blobuploadcleanupworker.py, workers/buildlogsarchiver/buildlogsarchiver.py, workers/chunkcleanupworker.py, workers/expiredappspecifictokenworker.py, workers/exportactionlogsworker.py, workers/gc/gcworker.py, workers/globalpromstats/globalpromstats.py, workers/gunicorn_worker.py, workers/logrotateworker.py, workers/manifestbackfillworker.py, workers/namespacegcworker.py, workers/notificationworker/notificationworker.py, workers/queuecleanupworker.py, workers/repomirrorworker/repomirrorworker.py, workers/repositoryactioncounter.py, workers/repositorygcworker.py, workers/securityscanningnotificationworker.py, workers/securityworker/securityworker.py, workers/servicekeyworker/servicekeyworker.py, workers/storagereplication.py, workers/teamsyncworker/teamsyncworker.py
Quay uses GunicornWorker to run background workers in the development environment. It is not expected to serve any HTTP server.
=> Remove app from GunicornWorker

test/helpers.py, test/registry/liveserverfixture.py
Tests that rely on multiprocessing to spawn liveserver fail on macOS:
Can't pickle local object 'liveserver_app.<locals>._spawn_live_server.<locals>.<lambda>'
Changing the start method to "fork" addresses the problem.
=> Fix unit tests on macOS

quay-entrypoint.sh
The startup script still references the `certs_create.sh` file due to which config-tool startup fails.
This PR removes the reference.
=> chore: Fix startup script

static/css/core-ui.css, static/css/quay.css, static/js/pages/repo-view.js, static/partials/repo-view.html
This adds another link to the repository view that leads to the user account or organization containing the repository. Adds convenience to navigate one level up in the hierarchy of Quay's data model to explore other content in the same account or organization.
=> ui: add parent navigation link to repository view (PROJQUAY-3981)

requirements.txt
Fix warning about deprecated import:
html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
=> Bump html5lib to remove warning about Python 3.10

requirements.txt
* Resolves downstream build issue related to `azure-core`
```
2022-06-30 16:43:49,821 - atomic_reactor.plugins.imagebuilder - INFO - ERROR: Could not find a version that satisfies the requirement typing-extensions>=4.0.1 (from azure-core) (from versions: none)
2022-06-30 16:43:49,821 - atomic_reactor.plugins.imagebuilder - INFO - ERROR: No matching distribution found for typing-extensions>=4.0.1
```
=> chore: Add missing downstream dependency (PROJQUAY-4033)

requirements.txt
* Required by `typing-extensions`
* Should resolve downstream error:
```
2022-06-30 19:19:13,357 - atomic_reactor.plugins.imagebuilder - INFO -   ERROR: Could not find a version that satisfies the requirement flit_core<4,>=3.4 (from versions: none)
2022-06-30 19:19:13,357 - atomic_reactor.plugins.imagebuilder - INFO -   ERROR: No matching distribution found for flit_core<4,>=3.4
```
=> chore: Add flit_core to deps (PROJQUAY-4033)

buildman/manager/executor.py, buildman/manager/test/test_executor.py
Allows the quay-builder to use user provided certificates.
=> builders: Add cacert's to build agent (PROJQUAY-3819)

data/secscan_model/secscan_v4_model.py, data/secscan_model/test/test_secscan_v4_model.py
Currently if Clair returns errors Quay will delete the security
status for that manifest, meaning it will revert to a "Queued"
status and needs to be reindexed. This in-turn means that the
functionality is not immediately recovered when Clair becomes
healthy. It is also generally a bad idea (except in specific
use-cases to have a data modification in a read path).
=> secscan: Don't delete manifest security status on error (PROJQUAY-4060) 

data/model/__init__.py, data/model/repo_mirror.py, workers/repomirrorworker/__init__.py
Previous logic for claiming mirror ("locking") relied on the value
returned from updating the database row. Since this was always being
updated with a new expiration time, it would always succeed, even when
another process had already claimed the same mirror.
=> mirroring: fix mirror claims for multiple processes (PROJQUAY-3982)

app.py, endpoints/web.py, requirements.txt, util/request.py
werkzeug 1.0.0 allows us to set samesite policy to "None" for CORS
requests from quay-ui
=> api: Update werkzeug to 1.0.0 and add valid CORS methods (PROJQUAY-4163)

oauth/oidc.py, util/security/jwtutil.py, util/security/test/test_jwtutil.py
Allow the use of RS384 for jwt and oidc.
=> auth: allow rs384 in jwt (PROJQUAY-4148)

util/request.py
Fixes issue where we send large header on CORS
=> api: fix CORS headers, use concat instead of extend (PROJQUAY-4163)

data/registry_model/registry_proxy_model.py, data/registry_model/test/test_registry_proxy_model.py
Respect `CREATE_PRIVATE_REPO_ON_PUSH` flag when creating repositories via proxy cache
=> Proxy cache - respect CREATE_PRIVATE_REPO_ON_PUSH flag (PROJQUAY-3743)

static/directives/plans-display.html
Remove the "30-day free trial" node from the bottom of plans
=> ui: Remove trial from larger plans for quay.io (PROJQUAY-4197)

oauth/oidc.py
* Resolves issue with `oidc` erroneously requiring `nbf`
=> deps: Fix nbf and oidc (PROJQUAY-4267)

Makefile
this way the tests can be run in parallel with a quay instance running locally.
=> Makefile: use non-standard port for postgres test container

util/config/schema.py, workers/repomirrorworker/__init__.py, workers/repomirrorworker/test/test_repomirrorworker.py
Adds the `REPO_MIRROR_ROLLBACK` option to specify whether the mirror will rollback the state of the repo on failure of any one of the tags. Defaults to false. Adds additional `PARTIAL_SYNC` error status which logs the tags that failed to sync to the console.
=> mirror: Default mirror rollback to false (PROJQUAY-4296)

conf/nginx/nginx.conf.jnj
* Adds IPv6 listeners to `nginx.conf`
Test by spinning up an instance and attempting to curl an IPv6 address and port:
```
$ curl http://localhost:8080/health/instance
{"data":{"services":{"auth":true,"database":true,"disk_space":true,"registry_gunicorn":true,"service_key":true,"web_gunicorn":true}},"status_code":200}
$ curl http://[::1]:8080/health/instance
{"data":{"services":{"auth":true,"database":true,"disk_space":true,"registry_gunicorn":true,"service_key":true,"web_gunicorn":true}},"status_code":200}
```
=> feature: Enable IPv6 Listeners (PROJQUAY-272)

workers/repomirrorworker/__init__.py, workers/repomirrorworker/test/test_repomirrorworker.py
Currently Quay creates tags for Docker V2 schema 1 manifests in manifest lists. This makes it appear a tag was mirrored successfully when it had actually failed. This change rolls back those failed tags when the sync fails.
=> mirror: Rollback failed tags (PROJQUAY-4322)

app.py
Previously, we didn't check for the presence of `QUAY_DISTRIBUTED_STORAGE_PREFERENCE` when `FEATURE_STORAGE_REPLICATION` was set to `true`. In certain situations, this would cause issues with what storage backend is being used during pushes. With this change, Quay will not allow execution unless preferred storage engine is explicitly defined.
=> chore: Add georeplication variable check (PROJQUAY-4363)

data/model/health.py
- The database health check is currently not using the db_kwargs and not using ssl settings
- This is causing health check failures for MySQL behind SSL
=> healthcheck: Use db_kwargs in health check (PROJQUAY-4222)

conf/nginx/server-base.conf.jnj
* Updates nginx to always route `/signin` to the current UI
This is the server side of the work. A second PR in `quay-ui` will be created to handle client side routing.
=> ui: Force /signin to use current UI (PROJQUAY-4345)

conf/nginx/server-base.conf.jnj, static/js/directives/ui/new-ui-toggle/new-ui-toggle.component.ts
Second part of https://github.com/quay/quay-ui/pull/82
* Prevents browser from caching nginx redirect to `/` by passing query args in replace request.
=> ui: Invalidate browser cache on new ui toggle (PROJQUAY-4423)

conf/init/nginx_conf_create.py, conf/nginx/nginx.conf.jnj, util/config/schema.py
* Provides a toggle for enabling IPv6, helps resolve issue with nginx failing to start in an IPv4 only environment
=> net: Add feature flags for IPv6 (PROJQUAY-131)

.github/workflows/cut-release.yml
* Replaces https://github.com/actions/create-release with https://github.com/ncipollo/release-action
=> ci: Update release workflow to use new release action (PROJQUAY-4444)

docker-compose.static, docker-compose.yaml
* Updates Clair to 4.4.4
* Limits `clair` and `clair-db` to 2 CPU each
=> dev: Update Clair for dev (PROJQUAY-4461)

data/users/__init__.py
* Fixes issue with new `LDAP_SUPERUSER_FILTER` feature
```
<pre>Running init script &apos;/quay-registry/conf/init/nginx_conf_create.sh&apos;
Running init script &apos;/quay-registry/conf/init/runmigration.sh&apos;
Traceback (most recent call last):
File &quot;/quay-registry/conf/init/data_migration.py&quot;, line 3, in &lt;module&gt;
from app import app
File &quot;/quay-registry/app.py&quot;, line 262, in &lt;module&gt;
superusers = SuperUserManager(app, authentication)
File &quot;/quay-registry/data/users/__init__.py&quot;, line 342, in __init__
self.state = self.init_app(app, authentication)
File &quot;/quay-registry/data/users/__init__.py&quot;, line 347, in init_app
manager = FederetedSuperUserManager(app, authentication)
NameError: name &apos;FederetedSuperUserManager&apos; is not …
```
=> superuser: Fix typo (PROJQUAY-3924)

data/users/__init__.py
* Fixes `super()` formatting for python 3. 
```
Running init script '/quay-registry/conf/init/nginx_conf_create.sh'
Running init script '/quay-registry/conf/init/runmigration.sh'
Traceback (most recent call last):
File "/quay-registry/conf/init/data_migration.py", line 3, in <module>
from app import app
File "/quay-registry/app.py", line 262, in <module>
superusers = SuperUserManager(app, authentication)
File "/quay-registry/data/users/__init__.py", line 342, in __init__
self.state = self.init_app(app, authentication)
File "/quay-registry/data/users/__init__.py", line 347, in init_app
manager = FederatedSuperUserManager(app, authentication)
File "/quay-registry/data/users/__init__.py", line 365, in __init__
super().__init__(self, app)
TypeError: __init__() takes 2 positional arguments but …
```
=> superuser: Fix super (PROJQUAY-3924)

data/model/test/test_user.py, data/model/user.py, initdb.py
The function `get_quay_user_from_federated_login_name` is used by the Self Service Tool to fetch quay.io users based on RH SSO username. RH SSO username is stored as a JSON blob with key `service_username`.
=> Export Compliance: Fetching quay user data from federated login username (PROJQUAY-0000)

storage/cloud.py, storage/test/test_cloudfront.py, util/ipresolver/__init__.py, util/ipresolver/test/test_ipresolver.py
This optimization ensures that we return the direct S3 URL for CloudFront storage only for requests from the same region. This ensures we don't get charged for cross-region traffic to S3
=> storage: return S3 url only for ip ranges in the same region (PROJQUAY-4498)

data/model/test/test_user.py, data/model/user.py
Added `get_public_repo_count` function to fetch a users total public repositories. This function will be used by the Self-Service Tool when displaying user data. 
Related Jira - https://issues.redhat.com/browse/PROJQUAY-3292
=> User: Added function to fetch users public repositories count (PROJQUAY-0000)

endpoints/api/__init__.py
The format created by `email.utils.formatdate` is RFC 2822, not RFC 822.
=> Clarify date format created by format_date

static/css/directives/ui/new-ui-toggle.css, static/js/directives/ui/new-ui-toggle/new-ui-toggle.component.html
Recent CSS changes caused the font size in the superuser panel to increase. The `active` and `inactive` CSS classes were added and overrode the existing `active` and `inactive` definitions.
=> ui: Fix font size in superuser page (PROJQUAY-4407)

.github/workflows/CI.yaml, .github/workflows/build-and-publish.yaml, Dockerfile, requirements.txt
Add ppc64le support to quay image
=> arch: add ppc64le support to quay (PROJQUAY-4595)

storage/cloud.py
RadosGW did not support multipart copying from keys so we needed to do a local join and reupload of the whole blob. This creates issues for very big blobs where timeouts can occur. Since the issue was fixed in 2015. on the Rados side, we no longer need this part of legacy code.
See [here](https://github.com/ceph/ceph/pull/5139) for more information.
=> chore: Add server side assembly of chunked metadata for RADOSGW driver (PROJQUAY-4592)

storage/__init__.py, storage/cloudflarestorage.py
This adds CloudFlare as a CDN provider for quay for any storage backed
by S3. This requires a worker script that needs to be setup seperately
on CloudFlare. More details on the worker at
https://github.com/quay/quay-cloudflare-cdn-worker
=> storage: Add Cloudflare as a CDN provider for an S3 backed storage (PROJQUAY-3699)

requirements.txt
* Updates `beautifulsoup4` to latest version to bypass `error in beautifulsoup4 setup command: use_2to3 is invalid` error during downstream build
* Error most likely stems from `setuptools` update in https://github.com/quay/quay/pull/1558
* [Newer version](https://bazaar.launchpad.net/~leonardr/beautifulsoup/bs4/revision/606) of `beautifulsoup4` removes `use_2to3` from `setup.py`
=> deps: Update bs4 (PROJQUAY-4605)

endpoints/api/user.py
- Currently, the /api/v1/user endpoint will check if the user is an admin for every org
- This only needs to happen once per call to the endpoint
=> auth: Speed up permissions loading (PROJQUAY-4004)

config.py
Allow conftest policies to be stored on Quay
=> config: Add conftest mediatypes to default Quay configuration (PROJQUAY-4614)

data/secscan_model/secscan_v4_model.py, data/secscan_model/test/securityinformation_deduped.json, data/secscan_model/test/test_secscan_v4_model.py, data/secscan_model/test/vulnerabilityreport_duplicates.json
Currently Quay is displaying the Clair response with no interpretation meaning when Clair reports on vulns per repo they appear to be duplicated (RHEL based images with multiple repos and packages existing in more than one). The correct way to fix this is via an interpretation layer in Quay, this change is a stop-gap to improve readability for the user.
=> secscan: Generate key to reduce vulnerabilities (PROJQUAY-4562)

storage/cloudflarestorage.py
We are passing extra params like `username` which need to be accepted by
the CloudFlare storage provider
=> storage: Add **kwargs to get_direct_download_url for CloudFlare storage (PROJQUAY-3512)

proxy/__init__.py
Azure registry uses OAuth 2.0 for registry authentication which will also accept token under the name `access_token`. The change adds this field
=> Update auth flow to add "access_token" response field (PROJQUAY-4431)

config.py
White space in the mediatype config is preventing conftest policies containing data from being pushed.
=> config: Remove whitespace from config (PROJQUAY-4666)

app.py, auth/permissions.py, config.py, data/users/__init__.py, data/users/apptoken.py, data/users/database.py, data/users/externaljwt.py, data/users/externalldap.py, data/users/federated.py, data/users/keystone.py, endpoints/api/__init__.py, endpoints/api/build.py, endpoints/api/manifest.py, endpoints/api/organization.py, endpoints/api/repository.py, endpoints/api/robot.py, endpoints/api/superuser.py, endpoints/api/superuser_models_interface.py, endpoints/api/tag.py, endpoints/api/test/test_security.py, endpoints/api/trigger.py, endpoints/decorators.py, endpoints/v2/__init__.py, endpoints/v2/blob.py, endpoints/v2/manifest.py, endpoints/v2/v2auth.py, test/test_ldap.py, util/config/schema.py, util/config/superusermanager.py, util/config/test/test_superusermanager.py
Similar to LDAP_SUPERUSER_FILTER, add a specific filter to define
restricted users, based on the LDAP_USER_FILTER
- restrict writes on restricted users' own namespace. Normal
permissions applies on organization membership
- add global readonly superuser GLOBAL_READONLY_SUPER_USERS (PROJQUAY-2604)
- Removes RESTRICTED_USER_INCLUDE_ROBOTS, FEATURE_RESTRICTED_READ_ONLY_USERS
=> users: add restricted users' filter (PROJQUAY-1245)

scripts/app_sre_build_deploy_rhel7.sh, scripts/app_sre_post_deploy_rhel7.sh
Change order to push to ecr first when deploying quay.io - fixes the problem of needing a newer build when deploying quay.io but cannot get it because quay.io itself is down.
=> scripts: push to ecr backup when building quay.io (PROJQUAY-3273)

buildman/manager/ephemeral.py
i.e Failed api calls caused by the external builder servic (expired certificate, network issues, ...)
=> buildman: allow fallback on non-exception build failures (PROJQUAY-4609)

Dockerfile
Building the image on Fedora arm64 fails without this change.
`uname -m` prints `aarch64` on my machine. I have never seen `arm_64` (with an underscore) anywhere before.
=> arch: Map aarch64 to arm64 in ARCH variable (PROJQUAY-4679)

endpoints/api/__init__.py
Missing wraps decorator on disallow_for_user_namespace prevents some API endpoints from being discovered on the frontend.
=> auth: Adding wraps to user namespace decorator (PROJQUAY-4694)

endpoints/api/organization.py, proxy/__init__.py
When authenticating against a registry, if the `www-authenticate` header doesn't specify a `service` parameter, it should be excluded from the registry auth url.
Eg:
```
$  curl -I -L https://registry.ci.openshift.org/v2/
HTTP/2 401
content-type: application/json; charset=utf-8
docker-distribution-api-version: registry/2.0
www-authenticate: Bearer realm="https://registry.ci.openshift.org/openshift/token"
```
the `www-authenticate` header doesn't specify a `service` parameter. Prior to this change, the malformed url request failed with a `401`
```
$ curl https://registry.ci.openshift.org/openshift/token\?service\=None\&scope\=repository:something-totally-fake:pull
{"details":"repository name \"something-totally-fake\" invalid: it must be of the format \u003cproject\u003e/\u003cname\u003e"} …
```
=> proxy: Modify registry auth url for proxy cache validation (PROJQUAY-4585)

static/js/pages/repo-view.js, static/partials/repo-view.html
The previous implementation of org check uses `UserService.getOrganization` which checks for logged in users orgs and returns true only if org matches to users orgs as [here](https://github.com/quay/quay/blob/master/static/js/services/user-service.js#L99-L113)
This PR fixes to use the `is_organization` flag returned by the repository response which is irrespective of user belonging to the org. 
Before:
After:
Here `Fedora123` org is created by a different user but admin has superuser perms and can view it.
=> UI: Fix redirection to user/org page (PROJQUAY-4667)

storage/cloudflarestorage.py
This will be used by the CloudFlare worker to redirect to the correct S3 origin bucket
=> storage: Add S3 Region to CloudFlare URL (PROJQUAY-3512)

endpoints/api/robot.py, endpoints/v2/v2auth.py
Also addresses [PROJQUAY-4732](https://issues.redhat.com//browse/PROJQUAY-4732), disabling robot creation on account's namespaces when FEATURE_RESTRICTED_USER is set.
=> users: fix create repo on push on orgs for restricted users (PROJQUAY-4732)

storage/cloud.py
This reverts commit cdb52ed023c8222f2eeb95a1c71c403a06655ed8. Noobaa has issues assembling big blobs from keys so this needs to be reverted to resolve a problem of pushing big blobs to the registry.
=> Revert "chore: Add server side assembly of chunked metadata for RADOSGW driver (PROJQUAY-4592)

data/users/externalldap.py, test/test_ldap.py
When LDAP is used and FEATURE_RESTRICTED_USERS is set, if LDAP_RESTRICTED_USER_FILTER is set, then, by default, all ldap users are restricted.
=> users: default to true if LDAP_RESTRICTED_USER_FILTER is not set (PROJQUAY-4776)

util/request.py
The PUT method has not been added to the list of cors methods, causing PUT requests to fail.
=> cors: Adding missing method type (PROJQUAY-4800)

static/directives/manifest-vulnerability-view.html, static/js/services/vulnerability-service.js
Use first link in the "array", don't display link icon when no links exist.
=> secscan: Correct links (PROJQUAY-2164)

.github/workflows/CI.yaml, Makefile, conf/nginx/server-base.conf.jnj, static/js/quay-routes.module.ts, test/integration/test_nginx.py
* Adds new Make target, `integration-test`
* Requires running `npm run quay:seed` from `quay-ui` repo
* The following legacy paths should now work when loaded in the new UI
* `/user/<user>/`
* There's no corresponding path in the new UI so this redirect back to the old UI and requires a refresh to retoggle the new UI
* `/search`
* There's no corresponding path in the new UI so this redirect back to the old UI and requires a refresh to retoggle the new UI
* `/organization/<org>/`
* `/repository/`
* `/repository/<org>/<repo>`
* Splits out docker builds based on architecture and adds an integration test to `amd64` builds
```
$ make integration-test
TEST=true PYTHONPATH="." py.test \
--verbose --ignore=buildman/ \
test/integration/*
Test session starts (platform: darwin, Python 3.9.15, pytest …
```
=> conf: Update nginx config (PROJQUAY-4554)

templates/base.html
* Adds cookie consent for `stage.quay.io` and `quay.io` 
Should be visible in a private tab.
=> ui: Add cookie consent for quay.io (PROJQUAY-4555)

.github/workflows/CI.yaml, .github/workflows/oci-distribution-spec.yaml
* Revert ubuntu runner to 20.04 to address changes introduced in 22.04 https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/
* This is a temporary fix until we figure out why conformance tests fail on 22.04
=> ci: Set ubuntu runner to be 20.04 (PROJQUAY-4825)

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
Api success rate was previously calculated by only looking at `2XX`s as successful and everything else as an error. This adjusts the query so only `5XX`s are considered errors and `4XX`s are not being incorrectly grouped as issues with the service.
=> deploy: fix api panels in dashboard (PROJQUAY-4485)

Dockerfile
`RUN rm -rm` doesn't delete data from previous layers, but it creates a new layer that marks which files should be deleted. So it increases the size of the image.
`RUN chmod` creates a new layer with a copy of the files with new permissions.
To reduce the size of the final image, these commands are moved into intermediate images.
=> chore: Update Dockerfile to reduce size of image (PROJQUAY-4837)

oauth/services/rhsso.py
SSO username can be different from quay username. Use the subject returned from the token and parse the SSO username from the subject
=> login: Use the correct username for export compliance (PROJQUAY-4844)

deploy/openshift/quay-py3-app.yaml
Adds pod anti-affinity in `quay-py3-app.yaml` according to https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
Trying to address alert received for quay.io where pod anti-affinity is not set for deployment.
=> deploy: add podAntiAffinity to deployment (PROJQUAY-3684)

deploy/openshift/quay-py3-app.yaml, deploy/openshift/quay-py3-cloudflare-app.yaml
fixing error on deploy:
`spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].weight: Invalid value: 0: must be in the range 1-100`
=> deploy: add weight to anti-affinity (PROJQUAY-3684)

.github/workflows/CI.yaml, Dockerfile
It takes >2 hours to build a Quay image for linux/arm64 by GitHub Actions. Caching should help us speed things up a bit.
=> chore: Use GitHub Actions cache for Docker Build jobs (PROJQUAY-4970)

Makefile, bill-of-materials.json, requirements.txt
Yapf is a formatter for Python files that is no longer used by Quay. It was replaced by black.
=> chore: remove yapf (PROJQUAY-4865)

requirements.txt
A follow-up of #1718. We can remove dependencies that are not needed anymore.
=> chore: Remove appr dependencies (PROJQUAY-4992)

config.py
If quay doesn't clean up temporary files under `uploads` folder by default, that means it is very possible for customer to pay more money for storage usage.  A lot of  important customers are money-sensitive,  so it doesn't make sense to set CLEAN_BLOB_UPLOAD_FOLDER as false by default.
=> config: clean upload folder by default (PROJQUAY-4395)

.github/workflows/oci-distribution-spec.yaml, Dockerfile, requirements.txt
- switch to ubi-minimal to get rid of subscription-manager and associated old urllib3 versions
- remove older pip version part of python39 appstream
- bump python dependencies
Signed-off-by: dmesser <dmesser@redhat.com>
=> build(deps): reduce CVEs in dependencies and runtime environment (PROJQUAY-4777)

storage/__init__.py, storage/distributedstorage.py
Add config option to validate all configured storages, and not just the first preferred one during healthcheck.
=> storage: add option to validate all configured storages (PROJQUAY-5074)

Dockerfile
=> chore: bump config-tool version to latest (PROJQUAY-5048)

data/users/externalldap.py, data/users/federated.py, test/test_ldap.py
Previously, on installations where LDAP is used, we were telling users whether the username or password was failing when login attempts were made. This might pose a security risk, a malicious user could, via the returned message, identify which users have access to Quay and which don't. 
With this change, we return a general message saying the user used wrong credentials instead of providing any details.
=> security: Change error messages in UI during LDAP login (PROJQUAY-4845)

Dockerfile, requirements.txt
See https://github.com/quay/quay/pull/1748 for details.
=> chore: Bump pyOpenSSL and cryptography (PROJQUAY-5120)

static/js/services/trigger-service.js
Gitlab requires scope to be part of the initial Oauth call to authorize the build trigger Oauth app access to the repo
=> builders: Add scopes to the oauth call to gitlab for build trigger (PROJQUAY-5181)

static/js/services/trigger-service.js
api write_repository is required to create a webhook on the repo
=> builders: Update scope for gitlab to include write access (PROJQUAY-5181)

config.py
We forgot to add the default value to `config.py` when we enabled this change. This PR adds the default value along with the flag description.
=> repomirror: Add default value for REPO_MIRROR_ROLLBACK to config (PROJQUAY-4296)

requirements.txt
Quay downstream build system cannot build new versions of the package `cryptography` as they use Rust. Unless downstream is fixed, we should use the latest available version that does not depend on Rust.
=> chore: Downgrade cryptography to 3.3.2 (PROJQUAY-5120)

scripts/app_sre_build_deploy_frontend.sh
The backup ECR needs correct IAM rules for pushing. Disabling it until we get that
=> build: disable push to backup repo for quayio-frontend (PROJQUAY-5229)

web/src/libs/axios.ts, web/src/routes/PluginMain.tsx
For standalone flow, redirect to /signin
=> ui: Refresh auth token for plugin flow on 401 (PROJQUAY-5390)

web/src/routes/NavigationPath.tsx, web/src/routes/RepositoriesList/RepositoriesList.tsx, web/src/routes/RepositoryDetails/Tags/SecurityDetails.tsx, web/src/routes/RepositoryDetails/Tags/TagsTable.tsx, web/src/routes/TagDetails/TagDetailsTabs.tsx, web/src/tests/fake-db/data/repository/repository.ts
window.location causes issues when running in beta or preview on console
=> ui: use route location instead of window.location (PROJQUAY-5392)

data/migrations/versions/a648ab200ab7_add_org_auditing.py, data/model/oci/tag.py, data/registry_model/registry_oci_model.py, endpoints/api/organization.py, endpoints/api/superuser.py, endpoints/api/tag.py, endpoints/api/user.py, endpoints/web.py, initdb.py, static/js/directives/ui/logs-view.js, static/js/services/string-builder-service.js
This adds several new action log event types, entries and corresponding UI support for the following activities:
- user/organization creation
- user/organization deletion
- user enable / disable via superuser
- organization rename via superuser
- change of an user/organization's email address, invoicing and time machine settings
- change of a users's password
- user creation via registration
- user Docker CLI password generation
Changes have been tested and verified with the table-based log model as well as the log list view UI.
=> logs: Add audit logs for organization and user namespace activities (PROJQUAY-3482)

workers/storagereplication.py
Allow the replication worker to retry immediately without having to wait and exhaust the queueitem's retries. This addresses transient unreliable storage service issues.
=> storagereplication: add retry logic without exhausting queue retries (PROJQUAY-4793)

util/marketplace.py
remove `/auth` from path to marketplace cert
secrets are mounted to `/conf/stack` by default
=> marketplace: fix path to api cert (PROJQUAY-5409)

conf/init/supervisord_conf_create.py, config.py, data/registry_model/quota.py, data/registry_model/test/test_quota.py, workers/quotatotalworker.py, workers/test/test_quotatotalworker.py
Add's checks to make sure the total being calculated isn't for a robot account.
Add's the `quotatotalworker` to the list of workers for the config tool.
=> quota: excluding robots from quota total (PROJQUAY-5469)

config.py, data/migrations/versions/0246c2d0e750_add_login_logout_logentrykind.py, endpoints/api/user.py, endpoints/v1/index.py, endpoints/v2/v2auth.py, initdb.py, static/js/directives/ui/logs-view.js, static/js/services/string-builder-service.js, util/config/schema.py, web/cypress/test/quay-db-data.txt
Based on @harishsurf 's work in #1822 this is adding audit events for :
- login/ logout of quay (e.g. via the Web UI)
- login via registry docker v2/OCI protocol (e.g. via docker/podman CLI)  with metadata covering robots and app-specific tokens
It also adds visualization in the current log view UI. The behavior is on by default and can be controlled by the `ACTION_LOG_AUDIT_LOGINS` config flag.
Note: No call is made to docker registry API during a logout from docker/podman CLI, hence no audit events are logged
Testing: verified with a local instance and database audit logging
=> logs: add audit log events for login/logout to Quay (PROJQUAY-2344)

data/model/oci/manifest.py, data/model/oci/tag.py, data/model/oci/test/test_oci_manifest.py, data/model/oci/test/test_oci_tag.py, data/registry_model/registry_proxy_model.py, data/registry_model/test/test_registry_proxy_model.py
The tagged JIRA contains most of the details. Moves the resetting of child manifest temporary tags to happen on deletion instead of on push/pull. Resetting child manifest temporary tags caused issues in other portions of the code like proxy cache where temporary tags were deleted too early.
=> quota: moving resetting of child manifest temporary tags to delete endpoint (PROJQUAY-5512)

endpoints/api/billing.py, endpoints/api/user.py, util/marketplace.py, workers/reconciliationworker.py
* Allowed number of private repos should be a sum of stripe plans and marketplace subscriptions.
* Make sure subscriptions are not expired when fetching from marketplace.
* Check subscription returned from stripe api is non-null value when performing reconciliation.
=> marketplace: fixing allowed repo count (PROJQUAY-5513)

endpoints/api/organization.py, proxy/__init__.py, static/js/directives/ui/proxy-cache-view.js
Currently anonymous pulls from registries are blocked since some registries like `gcr.io` require a `repo/image name` as part of `scope` to get a token or they return a `401`.  Since the `reponame` is not known at the time of initial proxy cache configuration, this change allows `401` as an accepted response to allow proxy config to be saved
=> proxy: Allow anonymous pulls from registries (PROJQUAY-5273)

data/model/oci/manifest.py, data/model/oci/tag.py, data/registry_model/interface.py, data/registry_model/registry_oci_model.py, data/registry_model/registry_proxy_model.py, endpoints/v2/manifest.py, test/registry/protocol_fixtures.py, test/registry/registry_tests.py
Prevent manifests pushed by digest from being hidden. Lets newer versions of conftest push to quay, since it expects to be able to pull the policy by digest when performing a push.
=> api: allow manifests to be pulled by digest (PROJQUAY-5467)

data/model/oci/tag.py, data/model/oci/test/test_oci_tag.py, data/registry_model/registry_proxy_model.py
Adds the following changes:
- Allows `remove_tag_from_timemachine` to expire tags even if the time machine window is set to 0, immediately marking them for deletion. This allows the quota proxy pruner to expire tags with the same method call. This wasn't required for normal push/pulls as the user would just call the `DELETE /tag` endpoint.
- Remove `hidden = true` when expiring tags. For proxy Quay will attempt to lookup the tag referenced by the manifest in order to extend it's `lifetime_end_ms`. Hiding this tag prevents that logic from running correctly.
=> proxy: allowing expiring tags with timemachine set to 0 (PROJQUAY-5558)

static/js/directives/ui/manage-user-tab.js, static/js/pages/superuser.js
Lowering the page limit allows for more operations to be done per requested user. Specifically in the scenario where for each user a LDAP lookup is done to check whether the user in the list is a superuser or not. This allows time for the request to complete and load the user list without error.
=> superuser: lowering page limit (PROJQUAY-5178)

static/js/directives/ui/repo-tag-history.js
If a tag has been permanently deleted it shouldn't be shown in the tag history panel with the ability to be reverted or permanently deleted again.
=> ui: remove permanently deleted tags from tag history (PROJQUAY-5574)

data/logs_model/logs_producer/splunk_logs_producer.py, data/logs_model/test/test_splunk.py
When the Splunk instance uses a certificate from a well-known CA, ssl_ca_path is not needed.
=> logs: ssl_ca_path should be optional (PROJQUAY-4993)

data/users/__init__.py, data/users/externalldap.py
LDAP referrals grant LDAP servers to distribute load and or migrate parts of the directory to another LDAP Server. 
The LDAP protocol does not specify how authentication is passed onwards and by default an `anonymous bind` is send. 
Depending on the configuration of the referral LDAP Server we see either an Authentication exception or nothing is returned (ACI based)
The patch provides the possibility to set, if we want to follow referrals or not by specifying the config.yaml variable: 
- LDAP_FOLLOW_REFERRALS=0  # do not follow
- LDAP_FOLLOW_REFERRALS=1 # to follow (default)
with the default set to what was hard coded, this patch is not expected to break any behavior
=> authentication(LDAP): allow LDAP referrals to not be followed (PROJQUAY-5291) 

data/database.py, data/migrations/versions/46980ea2dde5_change_removed_tag_expiration_s_to_.py, web/cypress/test/quay-db-data.txt
This addresses https://issues.redhat.com/browse/PROJQUAY-2462.
In this case we see garbage collection stopping due to too large values in the removed_tag_expiration_s column of the user table. This column is currently set to integer which is fine for most use cases, but becomes problematic with garbage collection since we multiply this value by 1000. The maximum allowed number for a signed integer is [(1/2)*2^32]-1 or 2147483647, any number over this value will lead to errors. For example 4 weeks of time machine window will lead to this field overflowing.
Signed-off-by: dmesser <dmesser@redhat.com>
=> db: change removed_tag_expiration_s  to bigint (PROJQUAY-2462)

static/js/directives/ui/manage-user-tab.js, static/js/pages/superuser.js
Need to merge [1923](https://github.com/quay/quay/pull/1923/files) before this PR.
Lowering the page limit allows for more operations to be done per requested user. Specifically in the scenario where for each user a LDAP lookup is done to check whether the user in the list is a superuser or not. This allows time for the request to complete and load the user list without error.
=> [redhat-3.7] superuser: lowering page limit (PROJQUAY-5178)

.github/workflows/build-and-publish.yaml
Updated builder for IBM/Z 
-  Verified the Building and publishing docker build through [workflow](https://github.com/ksdeekshith/quay/actions/runs/5174142121/jobs/9320128036) 
-  Updated **set-output** command, which is being deprecated, to **GITHUB_OUTPUT**
-  Removed **QEMU**
-  Added on-the-fly **creation of ZVSI for s390x builder** and **deletion post build-and-publish-s390x**
=> chore: updated s390x builder

static/js/directives/ui/quota-management-view.js
All byte units in the UI are base 1000 except for the quota configuration. This changes the configuration to also be base 1000 for consistency.
=> ui: changing quota configuration byte units to base 1000 (PROJQUAY-5595)

util/removelocation.py
- This removes first the ImageStoragePlacements that are associated with the location
- Once those are cleaned up, the ImageStorageLocation itself is removed from the database
- To run this command use `python -m util.removelocation <location_name>`
=> geo-rep: Add util script to remove geo-rep location and corresponding image locations (PROJQUAY-4995)

data/registry_model/datatypes.py, data/secscan_model/secscan_v4_model.py
Catch possible exception thrown when looking up tag `lifetime_start_ms` and set `created_at` property for a manifest to None.
If `created_at` is None, don't calculate indexing SLI for manifest.
=> data: Fix error getting tag while calculating scan results SLO (PROJQUAY-5600)

util/removelocation.py
- Features must be initialized in order to check if storage replication is enabled, so we need to import and intialize the config from inside the util script
=> geo-rep: Initialize features from config in util script (PROJQUAY-5627)

.github/workflows/build-and-publish.yaml
=> [redhat-3.9] chore: Use buildx v0.11.0-rc2

data/logs_model/table_logs_model.py, util/audit.py
This addresses https://issues.redhat.com/browse/PROJQUAY-5598
When the registry is in read-only mode, all writes to the database are suspended. Subsequently all log audit entry attempts will fail if the log model is based on the database. To avoid dealing with related exceptions from the database / model layer across the code base this PR adds handling at the relevant table logs model directly. This doesn't effect other log models where the log storage is an external system (ElasticSearch, Splunk, Document, etc)
Signed-off-by: dmesser <dmesser@redhat.com>
=> audit: ignore errors due to read-only mode in audit logs (PROJQUAY-5598)

requirements.txt
Reverts quay/quay#1976
New tzlocal causes issues like this:
```
notificationworker stderr |   File "/quay-registry/workers/worker.py", line 60, in __init__
notificationworker stderr |     self._sched = BackgroundScheduler()
notificationworker stderr |   File "/app/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
notificationworker stderr |     self.configure(gconfig, **options)
notificationworker stderr |   File "/app/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 126, in configure
notificationworker stderr |     self._configure(config)
notificationworker stderr |   File "/app/lib/python3.9/site-packages/apscheduler/schedulers/background.py", line 29, in _configure
notificationworker stderr |     super(BackgroundScheduler, …
```
=> Revert "chore: Bump dependencies that cause syntax warnings (PROJQUAY-5650)"

data/model/repository.py
This addresses https://issues.redhat.com/browse/PROJQUAY-4854. The code path is hit by the UI and will cause errors when trying to review repositories. In this implementation of repository size calculation a cache is maintained and updated when repos are listed. The cache update will cause errors when trying to hit the database with the registry in read-only mode.
=> db: handle readonly mode when updating repo size cache (PROJQUAY-4854)

storage/multicdnstorage.py, storage/test/test_multicdnstorage.py
This is used for cases where there can be multiple hostnames for the registry which can point to different CDNs and only some of them are opened by a customer behind a firewall.
Common use cases is for customers who don't want to open quay.io in their environment and can be provided with a different endpoint that has access to only specific namespaces
=> storage: Add Host header matching for multi CDN storage (PROJQUAY-5415)

data/model/user.py, util/validation.py
This is for usecases where we want to explicitly create a robot token with a pre-defined token in case of migration events when we migrate from one quay to another, we can re-use the same robot token to avoid resetting it in all places it is used
=> api: allow robot token creation with a pre-defined token (PROJQUAY-5414)

config.py, data/secscan_model/test/test_secscan_interface.py, data/secscan_model/test/test_secscan_v4_model.py, util/config/schema.py
Change the default from `False` to `True` for
`FEATURE_SECURITY_SCANNING_NOTIFY_ON_NEW_INDEX`.
Since this flag addresses a bug, it should be enabled by default.
=> config: Enable notifications for new indexes by default (PROJQUAY-5682)

storage/cloud.py, storage/test/test_cloud_storage.py
When completing a chunked upload, if the chunk list is empty do not attempt to assemble anything.
Using oras to copy an artifact from an outside registry to quay results in a 5XX error. This is because at some point the upload chunk list is empty and attempting to complete the chunked upload causes an exception. Not trying to write to storage if there are no chunks allows the copy operation to successfully complete.
=> storage: Do nothing when completing chunked upload if chunk list is empty (PROJQUAY-5489)

data/model/modelutil.py
Superuser logs are sorted on datetime field. The next page token contains the value of the start_index of the datetime field for the next page. datetime column on the LogEntry table is not unique, so in some cases,  multiple entries can have the same datetime field. 
For example, logs have a page limit of 20 entries. If 25 entries have the same datetime - d1, the start_index of the next page is again d1. With the current logic, the same query is run for the next page too. This PR addresses such issues and adds an offset in such cases where (the first 20 entries of page 1 and 1 or more entries of page 2 have the same datetime).
=> Pagination: Fixing paginate for /api/v1/superuser/logs API

storage/multicdnstorage.py
The download_url function is also used by the security worker which doesn't have an app context when it calls.
=> storage: Check for request context before getting host header (PROJQUAY-5860)

requirements.txt
Cython is required to build PyYAML from sources, and it depends on Cython<3.0.
=> chore: Use stable Cython

data/model/oci/test/test_oci_tag.py, web/cypress/e2e/repository-details.cy.ts, web/cypress/test/quay-db-data.txt, web/src/atoms/AlertState.ts, web/src/hooks/UseAlerts.ts, web/src/hooks/UseTags.ts, web/src/resources/TagResource.ts, web/src/routes/Alerts.tsx, web/src/routes/RepositoryDetails/Tags/TagsActions.tsx, web/src/routes/RepositoryDetails/Tags/TagsActionsAddTagModal.tsx, web/src/routes/RepositoryDetails/Tags/TagsList.tsx, web/src/routes/RepositoryDetails/Tags/TagsTable.tsx, web/src/routes/StandaloneMain.tsx
Adds tag options dropdown and the create tag option. Also adds generic alerts through the `useAlerts` hook.
=> ui: adding create tag option and generic alerts (PROJQUAY-5290)

.github/dependabot.yml
This PR enables dependabot for this repository. It updates dependencies to the latest versions (even when there are no CVEs). Example of PRs - https://github.com/dmage/quay/pulls?q=is%3Apr+author%3Aapp%2Fdependabot
=> chore: Add config for dependabot

Dockerfile
Follow-up to fix build errors caused by #2000.
```
Collecting lxml==4.9.2
Downloading https://.../packages/lxml/4.9.2/lxml-4.9.2.tar.gz (3.7 MB)
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'error'
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [3 lines of output]
Building lxml version 4.9.2.
Building without Cython.
Error: Please make sure the libxml2 and libxslt development packages are installed.
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```
=> chore: Add build dependencies for lxml 4.9.2

data/model/modelutil.py
When the database time is altered or explicitly set, the dateutil library adds the offset - `±HH:MM` to the set datetime. This is not identified by the query language and hence gets ignored when the query is complied. `ignoretz` flag in the [parse function](https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.parse) when set to `True` does not add this offset to the datetime and thus the start_index from the page_token is identified and complied.
=> api: Adding ignore timezone flag when parsing datetime (PROJQUAY-5360)

Dockerfile
Without the freetype-devel package installed, the build process fails:
```
Collecting reportlab==3.6.13
Downloading https://.../packages/reportlab/3.6.13/reportlab-3.6.13.tar.gz (4.0 MB)
Preparing metadata (setup.py): started
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [10 lines of output]
!!!!! cannot find ft2build.h
[end of output]
```
=> chore: Add build dependency for reportlab

.github/workflows/CI.yaml, .pre-commit-config.yaml, web/.eslintrc.js
This change runs all [pre-commit checks](https://github.com/quay/quay/blob/master/.pre-commit-config.yaml) in a GitHub job. This job will be informing until we agree to make it required.
=> chore: Run pre-commit checks on pull requests

util/backfillreplication.py
The `image` table is deprecated and also not used in the backfill replication script. This PR removes the reference left from the previous PR.
=> chore: Remove reference to Image table from the backfill replication script (PROJQUAY-5929)

Dockerfile
PyYAML 5.4.1 is the latest (at the moment) version that can be installed with Cython 3.0 (3.0b9).
As gevent requires Cython 3.0+, we cannot use PyYAML 6.0 that depends on Cython 0.x (<3.0).
As PyYAML 5.4.1 doesn't restrict the version of Cython that can be used to build it, pip selects Cython 3.0 when it creates an isolated build environment and fails to build PyYAML. To fix that, we preinstall build dependencies and disable the build isolation for PyYAML.
=> chore: fix build of PyYAML on linux/ppc64le

web/package-lock.json, web/package.json
husky, when installed via `npm install` in web/, replaces pre-commit, which is undesirable for this repository, as it essentially disables all pre-commit checks for Python code.
pre-commit already has all checks that are privded by husky.
=> chore: remove husky

conf/init/supervisord_conf_create.py
Quota worker incorrectly runs during config editor start up.
=> quota: disabling quotatotalworker when running config editor (PROJQUAY-5925)

.github/workflows/CI-nightly.yaml
Nightly tests for ppc64le and Z are failing with the below errors. Need to install required packages.
```err:   × python setup.py egg_info did not run successfully.
err:   │ exit code: 1
err:   ╰─> [5 lines of output]
err:       /tmp/pip-install-nylqgj2z/lxml_f64d41d75f61487f8b32a0164c470fee/setup.py:67: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
err:         import pkg_resources
err:       Building lxml version 4.9.2.
err:       Building without Cython.
err:       Error: Please make sure the libxml2 and libxslt development packages are installed.
err:       [end of output]```
=> chore: fix nightly test failures

.github/workflows/CI-nightly.yaml
Use PyYAML==6.0.1 which requires Cython<3.0 just for running tests.
Preinstall rustc cargo pkg-config required for building cryptography on ppc64le.
=> chore: fix ppc64le nightly test run

.github/workflows/CI-nightly.yaml
```
Failed to build cryptography
error: can't find Rust compiler
```
ref: https://github.com/quay/quay/actions/runs/5915637333/job/16042083379
=> chore: fix s390x nightly ci

deploy/openshift/quay-py3-app.yaml
This is for cases where we have a long running
migraiton and we don't want to kill the pod mid migration
=> deploy: Add a startup probe to the py3 deployment (PROJQUAY-522)

conf/init/client_certs.sh, quay-entrypoint.sh
add init script to prep Postgres Client certificates with proper permission if secret is populated through quay-operator PR (https://github.com/quay/quay-operator/pull/796)
This PR depends on successful merge of:
PR config-tool (https://github.com/quay/config-tool/pull/214)
PR quay-operator (https://github.com/quay/quay-operator/pull/796)
to work as expected.
=> init(postgresclientcerts): add Postgresql client certificate authentication (PROJQUAY-2417)

storage/cloud.py
Users are currently using the `S3storage` option to use the IBM storage solution. The final copy of an image push from the `uploads` to the `sha256` storage directory currently fails for large image layers (10gb). This is due to the 10gb layer being chunked into 5gb ranges that causes delays in the IBM copy operation. This PR adds performance by removing an unnecessary copy and adds the `maximum_chunk_size_gb` option to reduce the size of the copy.
=> storage: adding maximum_chunk_size_gb storage option (PROJQUAY-2679)

buildtrigger/basehandler.py, static/js/services/documentation/documentation.service.impl.ts
The documentation link on the build trigger tag template screen is currently pointing to the location of the `schema` directly in the code. 
This is not really useful or user friendly. This will repoint that documentation link to the KCS article written for this purpose.
=> documentation: Change tag template link location for build triggers (PROJQUAY-6044)

Dockerfile
This should speed up the build of the container on macOS a bit.
=> chore: don't chmod on every file in Dockerfile

.dockerignore
The `RUN npm run build` fails in `build-ui` step of quay's dockerfile because `web/node_modules` is not ignored. This changes add the folder to .dockerignore
=> chore: add **/node_modules to dockerignore

endpoints/api/repository.py, endpoints/api/repository_models_interface.py, endpoints/api/repository_models_pre_oci.py, endpoints/api/test/test_repository_models_pre_oci.py
When quota is enabled and an API call is made to `GET /api/v1/repository` a query is made to fetch the namespace quota limit for each repository in the list. Most often, specifically when loading the repositories list page, the result of this call will be the same and can cause up to 99 duplicated calls with the default limit. This stores the result of the call in memory to prevent the duplicate queries.
=> quota: removing extra calls to get namespace quotas (PROJQUAY-6048)

Dockerfile
This PR deletes about 656 MB of cached data from the Quay image.
=> chore: remove cached data from the final image

data/model/test/test_blob.py
This test reveals that Quay has issues with hashlib on UBI9: https://github.com/kislyuk/rehash/issues/6
=> chore: add tests for blobupload

conf/init/supervisord_conf_create.py, conf/supervisord.conf.jnj, config.py, data/database.py, data/migrations/versions/222debc16e18_autoprune.py, features/__init__.pyi, initdb.py, test/testconfig.py, util/config/schema.py, web/cypress/test/quay-db-data.txt, workers/autopruneworker.py
Adds the auto-prune worker, database models, and feature flag.
=> autoprune: add initial setup for the autoprune feature (PROJQUAY-6094)

config.py, static/js/quay-run.ts, util/config/schema.py
This is useful for cases where reads and writes are going to different DBs and there is a replication lag between them
=> ui: Add delay after write operations (PROJQUAY-6146)

data/model/autoprune.py
The task status should be updated to running when it is ran. Also dropping the level of the log for pruning a repository with a specific policy to debug to prevent flooding the logs.
=> autoprune: updating task status to running (PROJQUAY-6213)

requirements.txt
This reverts commit adbe34be671fba7c67f692d7abb35d3aec04c1e1.
tldextract 3.6.0+ uses md5, which is not allowed in FIPS-enabled environments. Possibly will be fixed by https://github.com/john-kurkowski/tldextract/pull/309.
=> Revert "build(deps): bump tldextract from 2.2.2 to 3.6.0 (#2310)"

web/package-lock.json, web/package.json, web/src/App.css, web/src/index.tsx, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/createTeamWizard/AddTeamMember.tsx
Using an older version of https://github.com/RedHatInsights/frontend-components, some styles in the patternfly v5 wizard were not being respected. Updating that package (and adding appropriate resolutions since it has a dependency on react v18), moving the import of patternfly css, and adding appropriate resolutions in the package.json seems to have remedied the styling conflicts.
Also, there was 1 page section that needed to remove padding still, which was leftover rework from the removal of deprecated patternfly components.
https://github.com/quay/quay/assets/96431149/16002d8a-2fe6-4727-adb6-01cecbfb0cc8
=> ui: Fix styling conflict with RedHatInsights (PROJQUAY-6085)

endpoints/api/__init__.py, endpoints/api/robot.py, endpoints/api/test/test_robot.py
Since all the parameters are optional a body isn't required. With the updated Flask package an empty body now returns a 415 when it didn't before. Quay should go back to accepting an empty body.
=> api: accepting empty body for create robot endpoints (PROJQUAY-6224)

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
SLO dashboard previously showed 100% availability during quay.io outage for `Push Operations` and `Pull Operations`
Fixing dashboard so that the stat panels show the average instead of latest value.
Attached screenshots showing updated dashboard:
=> deploy: update configmap for slo dashboard (PROJQUAY-6221)

web/cypress/e2e/teams-and-membership.cy.ts, web/src/hooks/UseMembers.ts, web/src/hooks/UseTeams.ts, web/src/libs/utils.ts, web/src/routes/OrganizationsList/Organization/Organization.tsx, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/createPermissionDrawer/CreatePermissionDrawer.tsx, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/createPermissionDrawer/CreateTeamModal.tsx, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/createTeamWizard/CreateTeamWizard.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/CollaboratorsView/CollaboratorsViewList.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/CollaboratorsView/CollaboratorsViewToolbar.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/MembersView/MembersViewList.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/MembersView/MembersViewToolbar.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsAndMembershipList.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/TeamsViewList.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/TeamsViewToolbar.tsx, web/src/routes/RepositoryDetails/RepositoryDetails.tsx
Adds create new team button under teams and membership tab:
=> ui: Add create new team button (PROJQUAY-5685)

web/cypress/e2e/manage-team-members.cy.ts, web/cypress/e2e/teams-and-membership.cy.ts, web/src/components/EntitySearch.tsx, web/src/components/modals/DeleteModalForRowTemplate.tsx, web/src/hooks/UseMembers.ts, web/src/hooks/UseTeams.ts, web/src/resources/MembersResource.ts, web/src/resources/TeamResources.ts, web/src/routes/OrganizationsList/Organization/Organization.tsx, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/DefaultPermissionsToolbar.tsx, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/createPermissionDrawer/CreatePermissionDrawer.tsx, web/src/routes/OrganizationsList/Organization/Tabs/DefaultPermissions/createTeamWizard/CreateTeamWizard.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/ManageMembers/AddNewTeamMemberDrawer.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/ManageMembers/ManageMembersList.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/ManageMembers/ManageMembersToolbar.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/ManageMembers/css/ManageMembers.css, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/TeamViewKebab.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/TeamsRoleDropDown.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/TeamsViewList.tsx
This PR adds the following changes to manage team members view under Teams and membership tab:
- An editable team description section
- A reusable generic delete modal template when deleting a team or a team member
- A drawer to add a member to the team
https://github.com/quay/quay/assets/39300150/0288cad4-6485-4bd1-b829-4b4b7535acfd
=> ui: Implement drawer to add a new team member (PROJQUAY-6032)

data/model/autoprune.py, data/test/test_namespace_autoprune.py
Prevent prune of mirror or readonly repositories even if a auto-prune policy is configured.
=> autoprune: preventing prune of mirror or readonly repos (PROJQUAY-6235)

util/marketplace.py, util/test/test_marketplace.py
For all methods that make a request to the subscription watch API, if the request times out then there should be `None` returned.
=> marketplace: return None if subscription api times out (PROJQUAY-5363)

endpoints/api/robot.py, endpoints/api/test/test_robot.py, web/src/components/modals/CreateRobotAccountModal.tsx, web/src/hooks/useRobotAccounts.ts
This PR takes care of graceful error handling instead of raising an exception for create robot account endpoint. Added the same error to propagate on the new UI too.
=> api: graceful error handling for robot acct already exists (PROJQUAY-6261)

config-tool/pkg/lib/fieldgroups/database/database.go
* scenario1: config-tool empty configuration ** expectation: empty config for DB_CONNECTION_ARGS
```
$ curl -s http://localhost/api/v1/config | jq -r '."config.yaml".DB_CONNECTION_ARGS'
{}
```
* scenario2: config-tool with populated DB_CONNECTION_ARGS ** expectation: values are returned in DB_CONNECTION_ARGS
```
$ curl -s http://localhost/api/v1/config | jq -r '."config.yaml".DB_CONNECTION_ARGS'
{
"autorollback": true,
"keepalives": 1,
"keepalives_count": 5,
"keepalives_idle": 3,
"keepalives_interval": 4,
"max_connections": 30,
"sslcompression": 1,
"stale_timeout": 300,
"tcp_user_timeout": 1000
}
```
* scenario3: config-tool with populated DB_CONNECTION_ARGS wrong type ** expectation: config-tool validate will bailout the wrong type in the parameter
```
$ podman run -ti --rm --name …
```
=> federationuser(ldap): fixing keepalive settings for LDAP connections (PROJQUAY-5137)

web/cypress/e2e/repository-details.cy.ts, web/src/routes/RepositoryDetails/Tags/TagsActionsEditExpirationModal.tsx
Adds the following fixes to editing tag expiration:
- Allows for selecting the current date
- Allows for selecting by the minute
- Adds additional validation when selecting date.
=> ui: allow current day to be selected for tag expiration (PROJQUAY-6262)

storage/__init__.py, storage/cloud.py
Adds the `IBMCloudStorage` driver. This allows multipart uploads to be used for IBM Cloud storage, therefore increasing performance for large image pushes.
=> storage: adding IBM COS storage option (PROJQUAY-2679)

web/cypress/e2e/repository-details.cy.ts, web/src/atoms/TagListState.ts, web/src/components/Table/ImageSize.tsx, web/src/components/Table/ManifestListSize.tsx, web/src/hooks/UseImageSize.ts, web/src/routes/RepositoryDetails/Tags/TagsTable.tsx, web/src/routes/TagDetails/Details/Details.tsx
Instead of displaying `N/A` or `Unknown` in the size column, a tag pointing to a manifest list should display size information. Since clients by default select only a specific child manifest of a manifest list, I opted here for a display of the size of the smallest and the largest child manifest.
https://github.com/quay/quay/assets/12664117/b42c3e78-8ae1-4592-9262-41c4c5a9d768
=> ui: display manifest list size range (PROJQUAY-6393)

requirements.txt
psycopg2-binary is for dev only in prod we should use psycopg2
=> database: use psycopg2 instead of psycopg2-binary (PROJQUAY-6453)

data/cache/cache_key.py, data/cache/impl.py, data/registry_model/interface.py, data/registry_model/registry_oci_model.py, data/registry_model/registry_proxy_model.py, data/registry_model/test/test_interface.py, endpoints/v2/manifest.py
Adds caching to `model.repository.get_repository` func called from api/v2/manifest endpoints.
=> api: add caching for get_repository method (PROJQUAY-6472)

util/marketplace.py
add log statements for debugging reconciler
=> marketplace: add logging for user api (PROJQUAY-233)

data/migrations/versions/8d47693829a0_auto_prune_policy_audit_logs.py, endpoints/api/policy.py, endpoints/api/test/test_policy.py, initdb.py, static/js/directives/ui/logs-view.js, web/cypress/test/quay-db-data.txt
Add's audit logs to the CRUD endpoints for both user and organization namespace auto-prune policies.
=> autoprune: adding audit logs to namespace autoprune policy API (PROJQUAY-6229)

deploy/openshift/quay-py3-deploy-template.yaml
Update deploy template to use proxy-protocol port on the pods for cases where we want to reach the LB directly
=> deploy: update deploy template add proxy port (PROJQUAY-6456)

deploy/openshift/quay-py3-deploy-template.yaml
variable is not expanded in health check. Use port directly
=> deploy: fix health check endpoint for quay deployment (PROJQUAY-6456)

oauth/services/rhsso.py
Adding error log instead of raising exception when we get unknown response/error from export compliance service. `exc_info` should send the error log to sentry.
=> sso: adding error log for export compliance (PROJQUAY-6486)

static/js/directives/repo-view/repo-panel-info.js
This fixes a bug while trying to update the repository description by explicitly calling the `updateRepo` endpoint.
=> ui: fix broken update of repo description (PROJQUAY-6243)

web/src/routes/OverviewList/RecommendedContent.tsx
Due to the addition of dedicated Quay.io docs, the Documentation link on Quay.io needs updated to redirect directly to the Quay.io docs, instead of the more general upstream docs
https://issues.redhat.com/browse/PROJQUAY-6473
=> ui: updates Quay.io documentation redirect link (PROJQUAY-6473)

config.py, util/config/schema.py, web/cypress/e2e/builds.cy.ts, web/cypress/fixtures/builds.json, web/cypress/fixtures/config.json, web/cypress/fixtures/testorg.json, web/cypress/fixtures/testrepo.json, web/src/components/LinkOrPlainText.tsx, web/src/hooks/UseBuilds.ts, web/src/resources/BuildResource.ts, web/src/routes/RepositoryDetails/Builds/Builds.tsx, web/src/routes/RepositoryDetails/RepositoryDetails.tsx
Adding panel for viewing previously ran builds.
**How to test with test data**
1. Enable the `FEATURE_UI_V2_BUILDS` config option
2. Open cypress `npx cypress open`
3. Run the `builds.cy.ts` spec
=> ui: implementing build history page (PROJQUAY-6293)

static/directives/header-bar.html
Prevents the beta UI toggle from rendering for anonymous users and users who need to confirm their profile details.
=> ui: Prevent switch to beta UI toggle from rendering if user is anonymous (PROJQUAY-6526)

web/src/components/header/QuayHeader.tsx
Now using the Redhat logo for Quay.io.
=> ui: updating logo for quay.io (PROJQUAY-6531)

data/billing.py, workers/reconciliationworker.py, workers/test/test_reconciliationworker.py
Add exception handling for stripe api if it receives a bad request for a user's stripe id.
=> marketplace: add exception handling for reconciler (PROJQUAY-233)

web/cypress/fixtures/builds.json, web/src/routes/RepositoryDetails/Builds/Builds.tsx
Sets the image size for avatars shown in the build history table. 
How to test:
1. Run the `Displays build status` test in `web/cypress/e2e/builds.cy.ts`
2. Verify the row with build id `build008` displays the avatar with the correct size
=> ui: adding build avatar image size (PROJQUAY-6575)

data/billing.py, data/model/entitlements.py, endpoints/api/test/test_superuser.py, initdb.py, static/js/directives/ui/plan-manager.js, test/test_api_usage.py, util/marketplace.py, util/test/test_marketplace.py, workers/reconciliationworker.py, workers/test/test_reconciliationworker.py
* fix reconciler where it was incorrectly using the ebsAccountNumber to create subscriptions
* add job to reconciler so that it reconciles different ids between the database and the user api
* separate skus to be used by billing and skus to be used by reconciler
=> marketplace: update reconciliationworker to use webCustomerId instead of ebsAccountNumber (PROJQUAY-233)

util/marketplace.py, util/test/test_marketplace.py, workers/test/test_reconciliationworker.py
Make sure when parsing data from user api that the customer id is returned as an integer type. Fixes problem with reconciler where it thinks two of the same id are different.
=> marketplace: make sure customer id from api is returned as an int (PROJQUAY-233)

data/cache/cache_key.py, data/registry_model/interface.py, data/registry_model/registry_oci_model.py, data/registry_model/registry_proxy_model.py, data/registry_model/test/test_interface.py, endpoints/api/test/test_tag.py, endpoints/v2/manifest.py
This PR caches the response of `model.repository.get_repository` as a json object instead of picking as done in https://github.com/quay/quay/pull/2515.
=> cache: adding caching on look_up repository (PROJQUAY-6472)

storage/cloud.py
Current uploads of large images usually fail on Ceph/RADOS compatible implementations (including Noobaa) because during the last assembly, copy is done all at once. For large layers, this takes a long while and Boto times out. With this patch, we limit the size of the used chunk to 32 MB so the final copy is done in parts of up to 32 MB each. The size can be overridden by specifying the parameter `maximum_chunk_size_mb` in the driver settings, for example:
~~~
DISTRIBUTED_STORAGE_CONFIG:
default:
- RadosGWStorage
- ...
maximum_chunk_size_mb: 100
~~~
=> storage: Fix big layer uploads for Ceph/RADOS driver (PROJQUAY-6586)

util/marketplace.py, util/test/test_marketplace.py
Currently `lookup_subscription` only returns the most recent subscription found in subscription watch. For the new skus it should return an array of valid subscriptions.
=> marketplace: return array of valid subscriptions when looking up subscription (PROJQUAY-6551)

config-tool/pkg/lib/editor/controllers.go
We are missing this commit in the 3.8 release. This fixes the config editor UI to send the auth token to the reconfigure endpoint.
=> reconfigure: Add auth to comit to operator endpoint (PROJQUAY-6598)

data/database.py, data/migrations/versions/41d15c93c299_add_quantity_field_to_orgrhskus.py, data/model/organization_skus.py, endpoints/api/billing.py, endpoints/api/organization.py, static/directives/org-binding.html, static/js/directives/ui/billing-management-panel.js, static/js/directives/ui/org-binding.js, test/test_api_usage.py, util/marketplace.py, util/test/test_marketplace.py, web/cypress/test/quay-db-data.txt
Adds handling for when a subscription returned from the subscription watch api has a `quantity` greater than 1. Number of private repos should be correctly calculated using the quantity. 
Updates ui so that subscriptions can only be added to an org as a group, i.e. a subscription with `quantity` = 2 cannot be split across organizations.
=> marketplace: add support for quantity from subscriptions api (PROJQUAY-6551)

image/oci/config.py, image/oci/test/test_oci_config.py
Artifacts can have empty config defined
skip parsing if the config is empty
=> manifest: support empty config for artifacts (PROJQUAY-6658)

web/src/components/NewUserEmptyPage.tsx, web/src/components/errors/404.tsx, web/src/routes/OrganizationsList/Organization/Organization.tsx, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/TeamsViewToolbar.tsx, web/src/routes/OrganizationsList/OrganizationsList.tsx, web/src/routes/RepositoryDetails/RepositoryDetails.tsx, web/src/routes/RepositoryDetails/Tags/TagsList.tsx, web/src/routes/RepositoryTagRouter.tsx, web/src/routes/Search/Search.tsx, web/src/routes/TagDetails/Details/Details.tsx, web/src/routes/TagDetails/Packages/PackagesFilter.tsx, web/src/routes/TagDetails/Packages/PackagesTable.tsx, web/src/routes/TagDetails/SecurityReport/SecurityReportFilter.tsx, web/src/routes/TagDetails/TagDetails.tsx, web/src/routes/TagDetails/TagDetailsArchSelect.tsx, web/src/routes/TagDetails/TagDetailsTabs.tsx
This PR fixes:
- the duplicate scrollbars and jumpy scrolling experience in some of the UI screens due to the nesting of `Page` components
- superfluous CSS padding settings
- consistent use of bottom shadow for top-level navigation screens
- incorrect vertical alignment of the filter bars in packages and vulnerabilities report
- lack of margin between architecture select drop-down and tag name in the title
- lack of margin between bottom-level pagination toolbar in the packages table
- consistent use of page insets for top-level tab navigation bars
- placing the action kebap in the "Teams and membership" screen right from the primary "Create Repository" button for consistency with the rest of the UI
This PR also adds:
- displaying the entire image tag spec (`repo:tag`) in the tag detail …
=> ui: fix scrollbars and various layout issues (PROJQUAY-6619)

static/directives/quay-service-status.html, static/js/services/notification-service.js, static/js/services/status-service.js, templates/500.html, web/.eslintrc.js, web/cypress/e2e/service-status.cy.ts, web/cypress/fixtures/registry-status.json, web/src/components/errors/SiteUnavailableError.tsx, web/src/hooks/UseServiceStatus.ts, web/src/index.html, web/src/routes/RegistryStatus.css, web/src/routes/RegistryStatus.tsx, web/src/routes/StandaloneMain.tsx
Updates references from `status.quay.io` to `status.redhat.com`. Uses responses based on the [status page API documentation](https://dn6mqn7xvzz3.statuspage.io/api). 
Gotchas:
- The `500.html` uses an imported status page script to display Quay status. Updating the page ID to use `status.redhat.com` causes the UI to display the overall RedHat status rather than specifically the Quay UI status. 
- There's the assumption that the `incidents` field contains a `components` parameter, like the `scheduled_maintenances` field.
=> ui: updating references to status.redhat.com (PROJQUAY-6654)

Dockerfile
According to the [app stream lifecycle](https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle), Quay's nginx 1.20 has been retired as of November 2023. The last version of nginx that is available is 1.22 and is supported till November 2025 for RHEL 8.
=> task: Upgrade Quay nginx (PROJQUAY-6685)

.github/workflows/CI-nightly.yaml
Error from logs:
```
Error: pg_config executable not found.
```
=> chore: amd64 nightly: add libpq-dev to fix issue while installing psycopg2

web/src/routes/PluginMain.tsx
Adds overview nav to `PluginMain.tsx` so it doesn't return a 404 when viewed from console dot.
=> ui: add overview to plugin (PROJQUAY-5460)

docker-compose.static, docker-compose.yaml
chore: update local development clair to 4.7.2
=> chore: update local development clair to 4.7.2

data/model/repository.py, data/model/test/test_repository.py
During quota verification, Quay fetches the size of the image currently being uploaded. That method incorrectly added the repository size to the size of the image being uploaded. That total returned was then added to the namespace size resulting in the following check: `repo_size + namespace_size + uploaded blob > quota_size_limit`. This causes the repo_size to be counted twice and images to be blocked early.
=> quota: removing repo size from quota verification (PROJQUAY-6637)

web/src/hooks/UseLogDescriptions.tsx
In usage logs description one of the entries in the `useLogDescriptions` hook is as string when it should be a function. This causes an exception when trying to view logs that contain the event `change_repo_state`
Makes `change_repo_state` to be a function so this exception does not happen.
=> ui: fix bug in usage logs description (PROJQUAY-6755)

data/users/externaloidc.py, test/test_external_oidc.py
This PR should fix the 500 error when trying to login via username/password:
=> oidc: display error msg when signing in via username password (PROJQUAY-6740)

data/users/externaloidc.py, test/test_external_oidc.py
When login_config has prefix "rhsso", it uses [RHSSOOAuthService](https://github.com/quay/quay/blob/master/oauth/loginmanager.py#L35) which is different from [UserAuthentication](https://github.com/quay/quay/blob/master/data/users/__init__.py#L142). Team syncing assumes UserAuthentication as login_service while OIDC team sync, uses login OAuthLoginManager.services when fetching teams (in this case RHSSOOAuthService).
The PR fixes login_service for OIDC team sync to read from UserAuthentication.
=> oidc: use federated login service to sync quay teams (PROJQUAY-6741)

storage/cloud.py
Currently, Boto GCP timeout is set to 60 seconds which causes a problem in pushing big layers. This change will allow users to configure `boto_timeout` manually. The parameter itself is optional and if not defined will default to 60 seconds. Connection settings:
~~~
DISTRIBUTED_STORAGE_CONFIG:
gcs:
- GoogleCloudStorage
- access_key: "access_key_here"
bucket_name: bucket_here
secret_key: "secret_key_here"
storage_path: /datastorage/registry
boto_timeout: 120           # new parameter added
~~~
Result with `boto_timeout: 600`:
~~~
root@cyberdyne:~# time { docker push quay.skynet/ibazulic/gcp-test; } Using default tag: latest
The push refers to repository [quay.skynet/ibazulic/gcp-test] 4335316598de: Pushed
d101c9453715: Pushed
latest: digest: …
=> storage: Increase GCP timeout (PROJQUAY-6819)

data/migrations/versions/cead4183265c_recreate_index_for_repository_autoprune_.py, web/cypress/test/quay-db-data.txt
Remove unique constraint on `repositoryautoprunepolicy_namespace_id` index to avoid duplicate key violation error
=> autoprune: add alembic script to remove unique constraint on index (PROJQUAY-6782)

web/cypress/e2e/team-sync.cy.ts, web/cypress/fixtures/teamsynced-members-superuser.json, web/src/routes/OrganizationsList/Organization/Tabs/TeamsAndMembership/TeamsView/ManageMembers/ManageMembersList.tsx
When Teamsync is enabled:
When Teamsync is disabled:
=> ui: show delete option for robot accounts when team is synced with external group (PROJQUAY-6828)

conf/nginx/server-base.conf.jnj
Upload of dockerfile for dockerfile builds currently hits the `/userfiles/<id>` endpoint in certain scenarios. From the new UI this routes to the react index.html resulting in a 405 method not found. This change routes all paths matching `^/userfiles/(.*)` to the API.
=> ui: updating nginx routing rule for userfiles (PROJQUAY-6841)

endpoints/api/billing.py, endpoints/api/organization.py, test/test_api_usage.py, util/marketplace.py, util/test/test_marketplace.py
* Refactor function that fetches subscription sku based on subscription id to also fetch the subscription end date
* Check for end date in subscription when performing operations with org attached subscriptions (looking up private repos allowed, etc.) and if the subscription is expired remove it from the org attachment table
* Asserts that subscription does not stay attached to an org past its expiry date
=> marketplace: add expiration check to org subscription operations (PROJQUAY-6716)

data/model/_basequery.py, data/model/oci/tag.py, data/model/permission.py, data/readreplica.py, data/test/test_readreplica.py
We add a new param `can_use_read_replica` to the `select` query. This allows us to choose which queries we want to send to the read replica. This is useful in cases where the read replica lags behind the primary and some queries need the latest data
=> db: use read replica for selected queries (PROJQUAY-6397)

web/src/routes/UsageLogs/UsageLogsGraph.tsx
Adjusts the padding of the usage log domain based on the length of log data available. 
Should prevent overlap between the chart bars and the legend.
=> logs: adjust graph padding dynamically (PROJQUAY-6857)

data/database.py, util/config/schema.py
adding `DB_CONNECTION_POOLING` param to enable/disable connection pooling for primary and replica DBs
=> db: add config variable for DB pooling (PROJQUAY-6397)

data/billing.py, test/test_api_usage.py, util/marketplace.py
Adds the reconciler SKUs to list of RH SKUs used for org attachment, and validates the reconciler SKUs based on if they're created by the reconciler or purchased from the AWS marketplace.
Old marketplace SKUs will be added to AWS listing. However, these SKUs are also used by the reconciler to create entitlements for paying stripe customers. In order to allow these SKUs to also be used in the marketplace, use `masterEndSystemName` property in the subscription API response. This will let us know whether the SKU can be assigned to an org or if it was created by the reconciler (`masterEndSystemName == SUBSCRIPTION`) and we should ignore it.
=> marketplace: add a check for masterEndSystemName when fetching subscriptions (PROJQUAY-6905)

data/model/repository.py, data/model/test/test_repository.py, endpoints/api/repository.py, endpoints/api/repository_models_interface.py, endpoints/api/repository_models_pre_oci.py, endpoints/api/test/test_repository_models_pre_oci.py
Reducing the number of DB calls in the repo list endpoint with quota enabled by:
- Adding the id to `RepositoryBaseElement` when the repositories are initially fetched, removing the need to fetch the repository ID's again
- Fetching the repository sizes with a single DB call using the `IN` operator
=> api: reducing db calls in repo list endpoints with quota enabled (PROJQUAY-6895)

util/marketplace.py
Adds clause to filter out skus with `masterEndSystemName=SUBSCRIPTION` to also be reconciler skus. This allows new skus used for purchase orders to still work.
=> marketplace: consider new skus in exclusion (PROJQUAY-6905)

web/cypress/e2e/robot-accounts.cy.ts, web/src/components/modals/RobotTokensModal.tsx
This changes the UI screen for the Kubernetes pull secret creation to allow the scope of the pull secret to be set. What is normally 
```
.dockerconfigjson:
{
"auths": {
"<quay-server-hostname>": { "auth": "TOKEN",  "email": ""}
}
} 
```
now becomes
```
.dockerconfigjson:
{
"auths": {
"<quay-server-hostname>/<organization>": { "auth": "TOKEN",  "email": ""}
}
} 
```
This makes using this pull secret in an OpenShift project easier when a cluster-wide global pull secret scoped to the same registry is already available. This requires support from the container runtime to scope the pull secret to a certain namespace only, e.g. CRI-O via c/image: https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md - other runtimes may ignore this scope.
The PR also aligns the …
=> ui: Allow to configure the Kubernetes pull secret scope for Robot Tokens (PROJQUAY-7012)

web/cypress/e2e/repositories-list.cy.ts, web/src/resources/RepositoryResource.ts
This change batches requests when trying to fetch all repositories the current user has access too. Otherwise the UI will make simultaneous requests equal to the number of organizations, where if the number is great enough it will exhaust the browser resources and cause the page to crash.
=> ui: batching requests in repository list page (PROJQUAY-6972)

endpoints/v2/blob.py, storage/cloudflarestorage.py, storage/test/test_cloudfront.py
Adds repo_name parameter to requests to Cloudflare and Cloudfront to associate repositories with egress traffic.
=> storage: add repo_name to direct download url parameter (PROJQUAY-7020)

web/cypress/e2e/builds.cy.ts, web/cypress/e2e/repository-details.cy.ts, web/src/components/DateTimePicker.tsx, web/src/libs/utils.ts, web/src/routes/RepositoryDetails/Tags/TagsActionsEditExpirationModal.tsx
This addresses a broader issue with hard-coded locale in the UI in some places of the UI vs. locale-dependent formatting of date and time output in other areas. Now, all parts of the UI leverage the browser's locale. This also means that the Cypress tests now expect locale-specific date and time formatting.
This addresses a more specific issue where the time picker in the tag expiration modal is causing error messages because it does not switch to the 24-hour mode when the locale demands it. This PR also addresses UI layout glitches in this modal and cleans up the error state visualization and enhances the guidance to valid inputs for expiration time by using the `minTime` property of the `TimePicker` component if the expiration time is on the same day as the current day.
Lastly, because …
=> ui: fix locale and layout issues with the time picker in tag expiration modal (PROJQUAY-7069)

util/marketplace.py, util/test/test_marketplace.py, workers/reconciliationworker.py, workers/test/test_reconciliationworker.py
Changes marketplace api handler to now return a list of all web customer ids for a user.
Allows quay.io to keep track of all web customer ids instead of just personal types.
=> marketplace: change api call to return array of customer ids (PROJQUAY-7129)

config-tool/utils/scripts/dumpschema.py, data/logs_model/logs_producer/splunk_hec_logs_producer.py, data/logs_model/logs_producer/splunk_logs_producer.py, data/logs_model/splunk_logs_model.py, data/logs_model/test/test_splunk.py, util/config/schema.py
This adds a producer to the Splunk log model for [Splunk HTTP Event Collectors](https://docs.splunk.com/Documentation/SplunkCloud/9.1.2312/Data/UsetheHTTPEventCollector#Set_up_and_use_HTTP_Event_Collector_in_Splunk_Web). HECs are available on Splunk Cloud and on Splunk Enterprise, whereas our existing implementation is for Splunk Simple Receivers which are only available on Splunk Enterprise. It seems HECs are more commonly used with our users.
This adds a new config schema to configure the Splunk HEC producer:
```
LOGS_MODEL: "splunk"
LOGS_MODEL_CONFIG: {
"producer": "splunk_hec",
"splunk_hec_config": {
"host": "prd-p-aaaaaq.splunkcloud.com",
"port": "8088",
"hec_token": "12345678-1234-1234-1234-1234567890ab",
"url_scheme": "https",
"verify_ssl": False,
"index": "quay",
"splunk_host": …
```
=> logs: adding support for Splunk HTTP Event collectors as producers (PROJQUAY-7124)

data/users/__init__.py, data/users/apptoken.py, data/users/database.py, data/users/externaljwt.py, data/users/externalldap.py, data/users/externaloidc.py, data/users/federated.py, data/users/keystone.py, test/test_ldap.py
Allows the global readonly superuser to be specified via a ldap filter `LDAP_GLOBAL_READONLY_SUPERUSER_FILTER`.
=> ldap: allow global readonly superuser to be filtered (PROJQUAY-7044)

static/directives/org-binding.html
Change angular marketplace UI to show private repo count instead of SKU. Remove "Monthly" from section heading.
=> ui: show repo count in marketplace UI (PROJQUAY-7185)

storage/cloud.py, storage/cloudflarestorage.py
This adds the optimization in CloudFlare where if a request is from the primary region then instead of redirecting to the CDN, we return the S3 URL to save egress cost
=> storage: Add S3 optimization for CloudFlare provider (PROJQUAY-7267)

endpoints/api/billing.py, endpoints/api/organization.py, test/test_api_usage.py, util/marketplace.py, util/test/test_marketplace.py
If a subscription is deleted in the subscription watch API it will set the field `terminatedDate` for the subscription object. This should be taken into consideration when fetching a subscription's details and the subscription should be removed from an org if it is terminated like how we already do for expired subscriptions.
=> marketplace: check for terminated subscriptions when fetching details (PROJQUAY-7035)

static/directives/billing-management-panel.html
Since the unlimited sku returns a private repo count equal to a max integer, the ui should show 'unlimited' instead of the actual number.
=> ui: show 'unlimited' if private repo count is over max number (PROJQUAY-7016)

util/http.py
Per recommendation from the W3C, we add `Vary: Origin` header to the 404 responses to instruct browsers (and other utilities) to cache various requests properly (based on their origin) in order to avoid cache poisoning. See the [W3C security details](https://www.w3.org/TR/2020/SPSD-cors-20200602/#resource-security) for more information.
=> security: Add Vary header to 404 responses (PROJQUAY-7304)

config.py, data/secscan_model/secscan_v4_model.py, events/vulnerability_found.html, util/config/schema.py
This fixes the Slack and e-mail notifications when images are indexed on initial push, where `tags` information was missing. If an image is a manifest child, instead of the tag, we provide a full SHA digest to the client.
Also adds the ability to filter security vulnerabilites depending on their severity. If the `NOTIFICATION_MIN_SEVERITY_ON_NEW_INDEX` is not set in the `config.yaml` file, we will automatically create notifications only for vulnerabilities marked "high" or "critical". This variable can take values defined [here](https://github.com/quay/quay/blob/3248a72da68ee70f4bd2b00dd03adaf76719269c/util/secscan/__init__.py#L1).
Example:
```
NOTIFICATION_MIN_SEVERITY_ON_NEW_INDEX: Medium
```
=> secscan: Fix Slack notification creation on initial index (PROJQUAY-7037)

data/cache/cache_key.py, data/model/oci/tag.py, data/model/oci/test/test_oci_tag.py, data/registry_model/interface.py, data/registry_model/registry_oci_model.py, data/registry_model/test/test_interface.py, endpoints/v2/__init__.py, endpoints/v2/errors.py, endpoints/v2/tag.py, test/registry/protocol_v2.py, workers/repomirrorworker/__init__.py
This aligns Quay's v2 tag listing endpoint to the most current tag listing specification: https://github.com/opencontainers/distribution-spec/blob/main/spec.md#content-discovery
It solves three problems:
- the tag order returned is not alphabetical ([PROJQUAY-2806](https://issues.redhat.com/browse/PROJQUAY-2806))
- the `last` parameter cannot be used to manually paginate through the result set ([PROJQUAY-6931](https://issues.redhat.com/browse/PROJQUAY-6931))
- we silently retrieve less than `n` tags if it exceeds the maximum configured v2 pagination size in the registry config
Now we:
- return tags in lexical order
- interpret the `last` parameter as the name of a tag in previous result page to indicate that there are more pages and to allow clients to continue to the next page beginning …
=> api: OCI compliant tag listing and pagination (PROJQUAY-6931)

endpoints/v2/__init__.py, endpoints/v2/tag.py, test/registry/registry_tests.py
This corrects the behavior when requesting a list of tags with a an `n` parameter set to 0. Whereas before at least one tag was returned, now, an empty list is returned.
Signed-off-by: dmesser <dmesser@redhat.com>
=> api: OCI-compliant tag listing behavior with limit = 0 (PROJQUAY-7327)

config-tool/utils/scripts/dumpschema.py, config.py, data/logs_model/document_logs_model.py, data/logs_model/splunk_logs_model.py, data/logs_model/test/test_elasticsearch.py, data/logs_model/test/test_splunk.py, data/model/_basequery.py, data/model/log.py, data/model/test/test_log.py, util/config/schema.py
This introduce the config option `ALLOW_WITHOUT_STRICT_LOGGING` which when set to `True` will make any error encountered during writing logs to remote systems non-fatal and logged to stdout instead.
This is useful, when an external log storage system like Splunk or ElasticSearch is intermittently down and the user favors the uptime of the registry more than audit log coverage.
Defaults to false.
=> logs: allow without strict logging (PROJQUAY-7116)

storage/cloud.py
We do a multi-part copy from the staging location to the final blob location in 5GB chunks sequentially. For large layers this is extremely slow. Use managed `copy` to move the blob to the final location faster
=> storage: use managed copy for single chunk uploads (PROJQUAY-7328)

config.py, data/cache/impl.py, data/cache/test/test_cache.py
This addresses the problem described here: https://access.redhat.com/solutions/7071210
First, we don't add output the value of object to be cached anymore unless in debug mode (actually for both redis and memcached), to avoid spamming the logs
Second, we are introducing the ability to control the maximum value size for memcached values with the default being 1MiB
Third, we are failing early (but still non-fatally) when the size of the value to be cached is higher than the configured maximum
=> cache: handle cache value size limit in memcached (PROJQUAY-7239)

data/database.py, data/migrations/versions/0cdd1f27a450_add_subject_backfilled_index.py, web/cypress/test/quay-db-data.txt
Adds the `manifest_repository_id_subject_backfilled` to the manifest table to improve lookup of manifests that require subject backfill.
=> database: adding subject_backfilled index to manifest table (PROJQUAY-7360)

data/database.py, data/migrations/versions/2664723e1b4b_add_last_ran_ms_to_repository_.py, data/migrations/versions/66147b81aad2_create_repo_image_expiry_notification_.py, data/migrations/versions/f67fe4871771_create_tag_notification_sent_table.py, initdb.py, web/cypress/test/quay-db-data.txt
database migrations for image expiry notification ([PROJQUAY-7075](https://issues.redhat.com//browse/PROJQUAY-7075))
seeding db changes for cypress
=> db: updates for image expiry notification (PROJQUAY-7075)

storage/cloud.py
Red Hat/IBM Ceph Storage provides multi-zone setups for on prem and geo-replication of Buckets. 
The RadosGWStorage Class in quay does not provide capability to configure `region_name` which is mandator for S3v4 signature in such scenarios. 
The default behavior is not changed as boto3 anyway sets `us-east-1` as default region 
```
>>> import boto3
>>> client = boto3.client("s3", endpoint_url="https://s3.example.com", aws_access_key_id="user1", aws_secret_access_key="user1")
>>> boto3.set_stream_logger(name='botocore')
>>> client.list_buckets()
...
2024-06-10 06:42:41,550 botocore.hooks [DEBUG] Event request-created.s3.ListBuckets: calling handler <function add_retry_headers at 0x7fb041ca9820>
2024-06-10 06:42:41,550 botocore.endpoint [DEBUG] Sending http request: <AWSPreparedRequest …
```
=> storage(RadosGWStorage): add Region to RadosGWStorage for multi-zone setups (PROJQUAY-7300)

templates/oauthorize.html
Adding check for `assignment_uuid`, otherwise sends value to API as the string `'None'` and breaks.
=> oauth: adding check for assignment uuid when creating token (PROJQUAY-7457)

util/migrate/allocator.py
1) Changing logger.info to logger.debug to stop too many INFO log lines from displaying in Quay logs 
2) Adding the missing worker name that print those log lines 
The idea of the log is to tell you which block is being procesed by worker that is processing it. These logs are missing the worker names
```
2023-11-27 15:24:05,825 [80] [INFO] [util.migrate.allocator] No candidates, marking entire block completed 210690-213109
2023-11-27 15:24:05,832 [80] [INFO] [util.migrate.allocator] No candidates, marking entire block completed 131657-134076
[sbhavsar-mac:~ sayalibhavsar]$ grep "No candidates, marking entire block completed" quay | wc -l
5300
```
For huge registries above logs  could be a bit noisy. We could hide it as a debug message rather than as an info message.
@sayalibhavsar
=> logging: reduce noise in quay logs and add missing worker names (PROJQUAY-6562)

web/cypress/e2e/usage-logs.cy.ts, web/src/hooks/UseLogDescriptions.tsx, web/src/routes/UsageLogs/UsageLogsTable.tsx
Adds search bar to the usage logs page that allows user to filter logs in the table based on description.
=> ui: add search bar for usage logs (PROJQUAY-7109)

notifications/notificationmethod.py
`urllib` requires that certs be parsed as tuple, not as a list. This small fix addresses that issue.
=> webhook: Fix failure in sending webhook POST requests (PROJQUAY-7468)

config-tool/pkg/lib/fieldgroups/autoprune/autoprune_validator.go
If DEFAULT_NAMESPACE_AUTOPRUNE_POLICY.method is number_of_tags, the integer should be greater than 0.
=> configtool: default namespace autoprune policy validation (PROJQUAY-7407)

data/database.py, data/migrations/versions/3f8d7acdf7f9_add_artifact_type_column.py, data/model/oci/manifest.py, web/cypress/test/quay-db-data.txt, workers/manifestsubjectbackfillworker.py
Previous assumption made use of the config media type only, which is not the case if a manifest's artifact type is explicitly set. i.e the config's media type and artifact type are different, and the artifact type take precedence for filtering.
=> registry: index manifest artifact type for filtering (PROJQUAY-7471)

data/database.py, data/migrations/versions/a32e17bfad20_increase_upstreamregistry_s_password_.py
Increased password length from 4096 to 9000 chars for upstream registry password.
=> mirror: increase char length in repo mirror config for externalregistrypassword (PROJQUAY-7430)

endpoints/v2/referrers.py
Referrers with only a temp tag (hidden) still need to be listed to validate that they exist when listing referrers.
=> registry: hidden tag should be included when checking a manifest's referrers (PROJQUAY-7519)

data/model/autoprune.py
This fixes an issue where the autoprune logic would not use the logs data model proxy but directly reach into the table-based audit logs model, leading to log coverage gaps when using another backend for audit logs.
=> audit: fix auto-prune audit logging (PROJQUAY-7423)

config-tool/pkg/lib/shared/storage_validators.go, config-tool/pkg/lib/shared/structs.go, storage/cloud.py
Pre-signed URL's are only on the `S3Storage` Class configured vor `s3v4` (hard coded).
This PR adds the attribute `signature_version` to all StorageClass definitions to be configured individually.
The behavior when not set defaults back to `v2` for all StorageClasses except `S3Storage` which defaults to `s3v4` 
Manual verification has been documented in https://issues.redhat.com/browse/PROJQUAY-7491 as  we do not have any validation tests as presigning is `client-local only` and therefor only would validate the string returned by the underlying function of botocore.
=> storage(StorageClasses): support changing signature version for pre-signed URL (PROJQUAY-7491)

endpoints/v2/referrers.py
Given that a repository is found, the request must not return a 404.
=> registry: return 400 instead of 404 for manifest errors on referrers api (PROJQUAY-7523)

conf/nginx/server-base.conf.jnj
Description: dropping x-forwared-host from the request ensures S3 signatures are valid
With Hitachi Vantara S3 Buckets integration, the `x-forwarded-host` invalidated the Signature in v4 mode.
Removing it accordinlgy in the nginx `_storage_proxy` location match enables us to use HCP Buckets.
=> nginx: dropping x-forwarded-host (PROJQUAY-7563)

CHANGELOG.md
The previous changelog was pointing to Red Hat Quay 3.7 release instead of the real 3.12 release.
=> docs: Point CHANGELOG.md to proper release notes (PROJQUAY-7578)

CHANGELOG.md
The previous changelog was pointing to Red Hat Quay 3.7 release instead of the real 3.11 release.
=> docs: Point CHANGELOG.md to proper release notes (PROJQUAY-7604)

.gitignore, data/model/repository.py, data/model/test/test_repository.py, docs/getting-started.md
[Jira Ticket ](https://issues.redhat.com/browse/PROJQUAY-7244?orderby=priority+ASC%2C+updated+DESC) has more details
It is currently not possible to search for repositories under a specific organization (e.g: fedora/python-311). The search only uses the `Repository.name` to do a search. 
Allow users to specify an organization in their search query
1. Added `.venv` to the `.gitignore`
2. Fixed the broken link to the `Contributing.md` document in the Getting Started guide
1. There are some repositories with `/` in their name on [quay.io](quay.io). One example would be `start/ingiress/controller`, where the org is `start` and the name is `ingress/controller`. If one were to search `ingress/controller` it would (with this change) not find the right repo. One would have to do …
=> api: allow refining search with an organization (PROJQUAY-7244)

.github/workflows/prepare-release.yml
Previous version of the workflow created a changelog whose URL pointed to an old Quay release. This should set the changelog URL to the branch version that the changelog is generated for.
=> chore: Fix prepare-release.yaml to properly modify changelog URL

data/model/storage.py
during manifest push, we generate a map of blobs which are part of the manifest layers. This is done using a UNION query which can overload the worker if the
number of layers is too large. Instead, run each
query individually to prevent the crash
use the attached file to test
=> storage: prevent registry worker crash for large layers (PROJQUAY-7603)

conf/init/nginx_conf_create.py, conf/nginx/server-base.conf.jnj, config.py, util/config/schema.py
reverting this change because we won't use keepalive with gunicorn workers
=> nginx: revert #3098 (PROJQUAY-7573)

web/src/libs/utils.ts
If you PUT against /api/v1/organization/mirrors/team/CAPITAL-LETTERS you'll get a different regex back.
Invalid team name CAPITAL-LETTERS: Namespace must match expression
^([a-z0-9]+(?:[._-][a-z0-9]+)*)$
Let's use this more permissive regex in the web-ui instead.
=> bug: too strict validateTeamName regex (PROJQUAY-7606)

static/css/directives/ui/manifest-vulnerability-view.css, static/directives/manifest-vulnerability-view.html
Old manifest vulnerability status page, still in use, would cause artifacts on long URLs and huge horizontal scroll bars. This fix limits the size of the displayed link thus eliminating horizontal scrolls. Tested on up to 150% zoom on 4k resolution.
=> oldui: Fix horizontal scrolling on vulnerability reports (PROJQUAY-7686)

.github/workflows/oci-distribution-spec.yaml, endpoints/v2/manifest.py, test/registry/registry_tests.py, test/specs.py
The deletion of tags was previously not supported by the Docker v2 API. Current versions of both the OCI spec and Docker v2 API provide this ability, hence adding it to Quay as well. See [OCI spec](https://github.com/opencontainers/distribution-spec/blob/main/spec.md) for more details.
=> api: Add tag deletion endpoint for v2 api (PROJQUAY-7599)

config-tool/pkg/lib/shared/storage_validators.go, storage/cloud.py
fixing the error seen with signature_v2/v4 patch https://github.com/quay/quay/pull/3041 when using STSS3Storage
Explanation:
the `STSS3Storage` Class is using the `connect_kwargs` dictionary to initialze the `S3Storage` Class where all other use that dict for the connection parameters which is misleading and I did not catch that when submitting the patch for the signature v2/v4 
```
File "/quay-registry/storage/__init__.py", line 62, in __init__
self.state = self.init_app(
File "/quay-registry/storage/__init__.py", line 71, in init_app
storages[location] = get_storage_driver(
File "/quay-registry/storage/__init__.py", line 48, in get_storage_driver
return driver_class(context, **parameters)
File "/quay-registry/storage/[cloud.py](https://cloud.py/)", line 1271, in __init__ …
```
=> storage(StorageClasses): Presign v2/v4 stsfix (PROJQUAY-7689)

util/secscan/v4/api.py, util/secscan/v4/test/test_secscan.py
Changes the timeout value for non-indexing requests to clair from 600 to 30.
Because the timeout for a vulnerability report request is so high, heavy traffic to the security enpdoint results in database connections being exhausted. Lowering the timeout value should allow requests to complete and connections to the database to close.
=> security: change timeout for vulnerability requests (PROJQUAY-7751)

data/database.py, data/model/autoprune.py, data/model/oci/tag.py, data/text.py, endpoints/api/policy.py, endpoints/api/test/test_policy.py, web/cypress/e2e/autopruning.cy.ts, web/cypress/e2e/repository-autopruning.cy.ts, web/src/resources/NamespaceAutoPruneResource.ts, web/src/resources/RepositoryAutoPruneResource.ts, web/src/routes/OrganizationsList/Organization/Tabs/Settings/AutoPruning.tsx, web/src/routes/RepositoryDetails/Settings/RepositoryAutoPruning.tsx, workers/test/test_autopruneworker.py
Allows users to specify a regex tag pattern when creating namespace/repository autoprune policies via the new UI. Users will have the option to prune tags that only match the tag pattern or exclude tags that match the tag pattern.
=> api: adding tag_pattern to autoprune API (PROJQUAY-7668)

data/model/health.py
Currently, our query to check team roles (part of the db health check) does not time out after a certain period but runs indefinitely. This causes worker timeouts after 30 seconds, which ends up in worker being killed by the master gunicorn process. We limit the maximum execution time of the query to 5000 ms so that proper exception is raised if that timeout is reached.
PostgreSQL logs:
~~~
2024-09-16 09:38:56.431 EDT [115775] testuser@quayclone2 LOG:  duration: 0.011 ms  statement: BEGIN 
2024-09-16 09:38:56.431 EDT [115775] testuser@quayclone2 LOG:  duration: 0.034 ms  statement: SET statement_timeout=5000 
2024-09-16 09:38:56.431 EDT [115775] testuser@quayclone2 LOG:  duration: 0.010 ms  statement: COMMIT 
2024-09-16 09:38:56.432 EDT [115775] testuser@quayclone2 LOG:  duration: 0.004 …
=> health: Add statement timeout to health check (PROJQUAY-7950)

quay-entrypoint.sh
`client_certs.sh` set's the correct permissions on the postgres certificates if they're found. This script was missing from the `migrate` command which would cause the migration to fail when using postgres certificate authentication.
=> init: adding Postgres cert install to entrypoint (PROJQUAY-7694)

data/database.py, data/migrations/versions/5b8dc452f5c3_add_tag_immutability_column_and_logentry_kinds.py, web/cypress/test/quay-db-data.txt
Database schema changes required to implement immutable tags as described in [PROJQUAY-7653](https://issues.redhat.com/browse/PROJQUAY-7653). Adds the `immutable` column as well as required indexes.
This is the first commit of 4 from the [original pull request](https://github.com/quay/quay/pull/1927).
Co-Authored-By: dmesser <dmesser@redhat.com>
=> db: adding immutable column to tag table (PROJQUAY-7777)

Makefile, conf/nginx/server-base.conf.jnj
From [nginx documentation](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering):
> When buffering is enabled, nginx receives a response from the proxied server as soon as possible, saving it into the buffers set by the proxy_buffer_size and proxy_buffers directives.
> If the whole response does not fit into memory, a part of it can be saved to a temporary file on the disk.
> Writing to temporary files is controlled by the proxy_max_temp_file_size and proxy_temp_file_write_size directives.
>
> When buffering is disabled, the response is passed to a client synchronously, immediately as it is received. nginx will not try to read the whole response from the proxied server.
> The maximum size of the data that nginx can receive from the server at a time is set by the …
=> nginx: Increase the number and size of proxy buffers (PROJQUAY-6950)

data/model/oci/tag.py, data/text.py, workers/test/test_autopruneworker.py
We have the offset being applied before querying for tag_pattern. This is returning wrong results. So, moved offset to be applied on `db_regex_search` if tag_pattern exists.
=> autoprune: fix tags returned by autoprune worker (PROJQUAY-8070)

data/model/_basequery.py, data/model/repository.py, data/model/test/test_visible_repos.py, endpoints/api/__init__.py, endpoints/v2/catalog.py
Allows for the full access and global readonly superuser to read all repositories from the `/v2/_catalog` endpoint.
=> api: allowing superuser to read catalog endpoint (PROJQUAY-8023)

endpoints/api/__init__.py, endpoints/decorated.py, endpoints/test/test_request_redirect.py
Handling exception when a request with the wrong method is made to quay without a trailing slash:
```
gunicorn-web stdout | 2024-10-18 18:56:31,053 [171] [ERROR] [gunicorn.error] Error handling request /oauth2/exchange
gunicorn-web stdout | Traceback (most recent call last):
gunicorn-web stdout |   File "/app/lib/python3.9/site-packages/gunicorn/workers/base_async.py", line 55, in handle
gunicorn-web stdout |     self.handle_request(listener_name, req, client, addr)
gunicorn-web stdout |   File "/app/lib/python3.9/site-packages/gunicorn/workers/ggevent.py", line 128, in handle_request
gunicorn-web stdout |     super().handle_request(listener_name, req, sock, addr)
gunicorn-web stdout |   File "/app/lib/python3.9/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request …
```
=> api: override flask application function to catch error (PROJQUAY-8026)

web/cypress/e2e/account-settings.cy.ts, web/cypress/e2e/org-settings.cy.ts, web/cypress/fixtures/config.json, web/src/libs/utils.ts, web/src/resources/UserResource.ts, web/src/routes/OrganizationsList/Organization/Tabs/Settings/GeneralSettings.tsx
This adds support for user-supplied tag expiration values from `TAG_EXPIRATION_OPTIONS` via config.yaml in the new UI. In the current code, these values weren't properly processed and led to the bug described in https://issues.redhat.com/browse/PROJQUAY-6700
This implementation also adds a number of additional improvements:
- conditional display of the time machine configuration depending on the `CHANGE_TAG_EXPIRATION` feature in the account settings
- actualy support for setting the time machines' default tag expiration in the account settings UI
- improved logic to set the currently selected expiration value in the dropdown list (based on the value in seconds instead of the human readable form)
- improved human-readable output of custom durations that prevent excessive rounding, e.g. …
=> ui: conditionally support custom tag expiration durations (PROJQUAY-6700)

web/cypress/e2e/repositories-list.cy.ts, web/src/components/modals/CreateRepoModalTemplate.tsx
Fixes the issue where namespaces were not being displayed via the dropdown under Create Repository modal
=> ui: Render namespace values for <SelectOption> dropdown under Create Repository modal (PROJQUAY-8118)

web/cypress/fixtures/config.json, web/src/libs/utils.ts
Adds support for yearly values as tag expiration options with the `y` suffix.
=> ui: tag expiration settings support year values (PROJQUAY-8171)

conf/nginx/server-base.conf.jnj
According to HCP support, the Ingress Load Balancer rejects requests with a `host=...;` in the `forwarded` Header.
The PR changes that only the originating Client ($remote_addr) is injected in the request as
```
Host: ....
Forwarded: for=127.0.0.1;
...
```
Reference: https://datatracker.ietf.org/doc/html/rfc7239#section-5.3
=> conf(nginx): change forwarded header removing host (PROJQUAY-8024)

requirements.txt
This change aims to get rid of "SyntaxWarning" messages during the initialization of netaddr.
=> build(deps): bump netaddr from 0.7.19 to 1.3.0 in requirements.txt (PROJQUAY-8222)

Dockerfile
Adds child labels to Dockerfile in order to comply with enterprise contract for [inherited labels](https://enterprisecontract.dev/docs/ec-policies/release_policy.html#labels__disallowed_inherited_labels)
=> chore: Add labels to Dockerfile to avoid inheriting them from base image (PROJQUAY-0000)

data/users/__init__.py, data/users/externaljwt.py, data/users/externaloidc.py, data/users/keystone.py, endpoints/api/organization.py, endpoints/api/repository.py, endpoints/api/test/test_organization.py, endpoints/api/test/test_repository.py, test/test_external_jwt_authn.py, test/test_external_oidc.py, test/test_keystone_auth.py
Currently, if any federated auth system is set as an authentication mechanism and restricted users is set, Quay will return a `501 Not Implemented` on invocation. Now, Quay will properly check the restricted user whitelist for federated users. 
Additionally, if user restriction is in place and super user's username was **not** explicitly whitelisted, super users would not be able to create new content inside the registry. Now, the username is explicitly checked in the UI to allow super users to create both organizations and repos regardless of restricted users whitelist.
=> auth: Implement is_restricted_user for federated auth systems (PROJQUAY-8208)

auth/scopes.py
Removes references from the Oauth scopes page concerning robot accounts. Oauth tokens currently cannot be assigned to robot accounts so current wording creates confusion.
=> auth: Remove robot references from scopes list (PROJQUAY-8269)

web/cypress/e2e/proxy-cache.cy.ts, web/cypress/fixtures/config.json, web/cypress/test/quay-db-data.txt, web/src/hooks/UseAlerts.ts, web/src/hooks/UseProxyCache.ts, web/src/resources/ProxyCacheResource.ts, web/src/routes/OrganizationsList/Organization/Tabs/Settings/ProxyCacheConfig.tsx, web/src/routes/OrganizationsList/Organization/Tabs/Settings/Settings.tsx
Adds proxy cache config UI to organization settings tab
Follow up:
- show proxy cache configuration during org creation (separate PR)
=> ui: Add proxy cache config UI to org settings (PROJQUAY-7697)

data/logs_model/elastic_logs.py, data/logs_model/logs_producer/elasticsearch_logs_producer.py, data/logs_model/test/fake_elasticsearch.py, data/logs_model/test/mock_elasticsearch.py, data/logs_model/test/test_elasticsearch.py, requirements.txt
Addresses [CVE-2024-23450](https://access.redhat.com/security/cve/CVE-2024-23450) via elasticsearch upgrade:
* Upgrade of elasticsearch packages from 7.6.0 to 8.13.0
* Update tests and elasticsearch logs to handle new major version
Should also resolve the following trackers:
* [PROJQUAY-6944](https://issues.redhat.com/browse/PROJQUAY-6944)
* [PROJQUAY-6943](https://issues.redhat.com/browse/PROJQUAY-6943)
=> cve: upgrade elasticsearch and elasticsearch-dsl to 8.13.0 (PROJQUAY-6962)

package-lock.json, package.json
* upgrade elliptic version to 6.5.7 
* elliptic, by default comes as a dependency of webpack. adding elliptic explicitly with fix containing version
=> cve: upgrade elliptic version to 6.5.7 (PROJQUAY-7595)

package-lock.json, package.json
Async <= 2.6.4 and <= 3.2.5 are vulnerable to ReDoS (Regular Expression Denial of Service) while parsing function in autoinject function. Updating the async version to the most recent release
- e2e tests
- manual testing
=> cve: updated async version and dependencies to 3.5.6 (PROJQUAY-7469)

requirements-build.txt, requirements.txt
43.0.3 requires maturin which breaks downstream builds. Downgrading to 42.0.5 which still resolves CVE's but doesn't require maturin.
=> deps: downgrading cryptography

package-lock.json, package.json, web/package-lock.json, web/package.json, web/webpack.plugin.js
This commit should fix the Webpack 5 breaking changes with axios:
```
ERROR in ./node_modules/axios/lib/utils.js 698:42-49
Module not found: Error: Can't resolve 'process/browser' in '/container_workspace/node_modules/axios/lib'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
```
=> dep: adding fallback for process/browser as dependency of axios update (PROJQUAY-7657)

requirements.txt
43.0.3 requires maturin which breaks downstream builds. Downgrading to 42.0.5 which still resolves CVE's but doesn't require maturin. Cherrypick of https://github.com/quay/quay/pull/3492
=> deps: downgrading cryptography (#3492)

requirements.txt
Downstream builds require `setuptools-rust==1.7.0`
=> Updating setuptools-rust

web/cypress/e2e/repository-permissions.cy.ts
There's a flake in the web/cypress/e2e/repository-permissions.cy.ts test where it is intermittently unable to type in the "Search for user, add/create robot account" search dropdown which occasionally fails the test. Since updating cypress the test fails consistently.
This changes waits and clicks on the input allowing the type to complete and the dropdown to populate.
=> ui: fixing cypress flake (PROJQUAY-8352)

requirements.txt
Required for downstream builds.
=> updating pyyaml to 6.0.1

.github/workflows/cut-release.yml
actions/download-artifact@v2 has been deprecated and has broken the release pipelines. It needs to be updated to v4 to get the pipelines running again.
=> dep: upgrading actions/download-artifact to v4 (PROJQUAY-8379)

data/model/team.py, data/model/test/test_team.py, data/users/externaloidc.py, test/test_external_oidc.py
This issue should fix [PROJQUAY-7747](https://issues.redhat.com/browse/PROJQUAY-7747) and [PROJQUAY-8130](https://issues.redhat.com/browse/PROJQUAY-8130). Adding `IntegrityError` to the try except block to skip adding existing user to team.
=> teamsync: peewee integrity error check on teamsync (PROJQUAY-7747)

data/model/user.py, workers/reconciliationworker.py, workers/test/test_reconciliationworker.py
Adds an `include_orgs` param to the active users query used by the reconciler and sets it to true for reconciler runs
Reconciler is not including orgs as a candidate for creating corresponding RH entitlements. As a result it misses users with stripe billing that are considered orgs.
=> worker: include orgs in reconciler runs (PROJQUAY-8431)

.github/workflows/CI-nightly.yaml
Fixed the issue with the blocked state of zvsi creation
- [Tested with Build and Publish in Private repo](https://github.com/ksdeekshith/quay/actions/runs/12697607985/job/35394281539)
=> chore: Fix for ci-nightly failure for s390x

conf/nginx/nginx.conf.jnj
Add `real_ip_recursive` directive to nginx config to properly get client IP addresses
=> util: parse forwarded headers for ip (PROJQUAY-8444)

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
Updates the quay SLO dashboard with some fixes for push SLIs and error budgets.
Adds new panels for tracking SLIs based on 5xx responses from the ALB
Preview of updated dashboard:
=> dashboard: update quayio slo dashboard with new 5xx panels (PROJQUAY-8455)

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
Adds adjustments to the SLO dashboard:
- error budget calculations are now done based on an SLO of 99.9 instead of 99.999
- ALB SLI is calculated based on a ratio of 5XX/2XX instead of 5XX/total # reqs
=> grafana: update the slo dashboard (PROJQUAY-8455)

endpoints/api/repository_models_pre_oci.py, endpoints/api/test/test_repository.py
When setting repositories in the Quay UI as starred, a 500 error occurs and renders the UI use-less due to starred queries are not paged.
Details are in the Jira accordingly.
=> endpoints(repository): fixing repository return with starred repos to paged response (PROJQUAY-8450)

static/js/services/status-service.js, web/cypress/support/e2e.ts, web/src/hooks/UseServiceStatus.ts
Status indicator on the old and new UI does not account for `under_maintenance` state, causing the lookup for icon and description to fail with `Cannot read properties of undefined (reading 'indicator')`.
=> ui: adding under_maintenance state to status indicator (PROJQUAY-8507)

data/registry_model/test/test_registry_proxy_model.py
added test for proxy cache. This test validates current proxy behavior. This test would fail once we implement the fix.
Note: This is not a expected behavior. This is how current proxy cache behavior looks like. The fix expected in this Jeera would rectify this behavior. 
https://issues.redhat.com/browse/PROJQUAY-8440
=> chore: added test for proxy cache (PROJQUAY-8440)

workers/reconciliationworker.py, workers/test/test_reconciliationworker.py
If there is no subscription in the customer object found by stripe an `AttributeError` will be thrown. This should be caught and handled as if there is no subscription present so that the reconciler can continue its work for other users/orgs
=> marketplace: handle exception thrown by stripe when customer has no subscription (PROJQUAY-8431)

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
Update the thresholds for the error budget display so the colors are more accurate. Changing so that anything below 0.005 (0.5%) for the error budget is yellow and anything below 0% is red.
=> chore: update thresholds for SLO error budgets (PROJQUAY-0000)

package-lock.json, package.json
updating jquery to 3.5.0. Cherrypick of https://github.com/quay/quay/pull/3629
=> deps: updating jquery to 3.5.0 (PROJQUAY-8522) (#3629)

config.py, endpoints/api/discovery.py, templates/base.html, util/config/schema.py
Previous iteration only allowed changes to the terms of service. With this push, all footer links should be customizable through the `FOOTER_LINKS` object. Example:
~~~
FOOTER_LINKS:
TERMS_OF_SERVICE_URL: "some_url"
PRIVACY_POLICY_URL: "some_url"
SECURITY_URL: "some_url"
ABOUT_URL: "some_url"
~~~
Missing entries should not be printed out in the UI.
Example:
~~~
FOOTER_LINKS:
"TERMS_OF_SERVICE_URL": "https://www.index.hr"
"PRIVACY_POLICY_URL": "https://www.jutarnji.hr"
"SECURITY_URL": "https://www.bug.hr"
"ABOUT_URL": "https://www.zagreb.hr"
~~~
shows the following in the UI:
=> ui: Expand support for customized footer links (PROJQUAY-5648)

app.py, util/test/test_log_util.py
Filter the repeatPassword key while creating the new user. 
'repeatPassword': '[FILTERED]'
```
============================================================================ test session starts =============================================================================
platform linux -- Python 3.9.20, pytest-8.3.4, pluggy-1.5.0 -- /usr/bin/python
cachedir: .pytest_cache
rootdir: /quay-registry
configfile: tox.ini
collected 1 item                                                                                                                                                             
util/test/test_log_util.py::test_filter_logs PASSED 
```
=> chore: Filtering repeatPassword in debuglogs (PROJQUAY-8559)

deploy/dashboards/grafana-dashboard-quay-usage.configmap.yaml
Adds a grafana dashboard that parses quay nginx logs to show useful visualizations on usage such as namespaces and repos with the most requests.
=> dashboard: add usage dashboard for grafana (PROJQUAY-8509)

health/services.py, storage/__init__.py, storage/distributedstorage.py
- `HEALTH_CHECKER_INSTANCE_CHECK_PREFERRED_STORAGE`: If set, instance health check will include the storage status of the first preferred storage 
- DISTRIBUTED_STORAGE_VALIDATE_ENDTOEND: Validate all storage during endtoend health checks
- DISTRIBUTED_STORAGE_REQUIRES_ALL_AVAILABLE: Requires all storages be available when during endtoend health checks and `DISTRIBUTED_STORAGE_VALIDATE_ENDTOEND` is set
=> healthcheck: add option to check preferred storage during instance check (PROJQUAY-5074)

endpoints/api/manifest.py, endpoints/api/test/test_manifest.py
Fixes a bug where the annotation is required at the manifest level even if artifactType is present. The modelcard should only be indicated by the artifact type and layer annotation for oci artifacts.
=> api: looking up layer by artifact type (PROJQUAY-8644)

build.sh, config-tool/pkg/lib/fieldgroups/distributedstorage/distributedstorage.go, config-tool/pkg/lib/shared/storage_validators.go, config-tool/pkg/lib/shared/structs.go, storage/cloud.py
When deploying Quay in a Secure AWS environment, we can't use IAM Access Keys or Secrets since these credentials are often blocked for multiple reasons (credentials are long-lived, can be shared / stolen, etc.). So the preferred deployment method is to use an alternative method, like the Web Identity Token files that are automatically created in a Kubernetes cluster that has a federation link with IAM using the OIDC provider federation.
The current code of Quay force the use of an IAM account that is then used to assume another role that has S3 access to store the image files. The current pull request removes the need to use that IAM account and allows to directly assume the correct role using Web Identity Tokens while retaining compatibility with the old method of using IAM credentials. …
=> [Feature] storage: Modify the STS S3 implementation of the storage backend to use Web Identity Tokens when available (PROJQUAY-8576)

requirements.txt
Pip installed from requirements.txt breaks the release pipeline.
=> chore: removing pip from requirements.txt file

requirements.txt
Required for supporting s390x builds in the release pipeline.
=> bumping gevent and greenlet

templates/base.html
Fixes the wrong name of the variable for the security link in the base template. All links should show properly now.
=> bug: Fix security url template variable (PROJQUAY-8650)

data/registry_model/registry_proxy_model.py, data/registry_model/test/test_registry_proxy_model.py
When an image is pulled by digest, a temp tag is created to prevent the manifest from being garbage collected. This is true when a manifest list is pulled by tag as well. However, if this temporary tag expires (default is 1 day for proxied organizations) and the same manifest is pulled again by digest, the system attempts to create the manifest again, leading to an integrity error because the manifest already exists in the database.
- manually tested push and pull from proxy repo
- manually tested push and pull from non proxy repo
=> bug: Adding allow hidden flag while looking up for manifests (PROJQUAY-8536)

.github/workflows/build-and-publish.yaml, requirements.txt
Because the cpaas pipeline is now failing due to the removal of pip in requirements.txt. I reverted the removal in #3714 and I am now removing it during the GitHub workflow instead.
=> chore: revert #3714 and remove pip from requirements.txt in workflow

deploy/dashboards/grafana-dashboard-quay-slo.configmap.yaml
- Current ALB based time series only describes ALB 2xx. This change add ELB errors to the metric of availability to display true state of the service.
=> operations: added ELB calculations to ALB based SLO timeseries (PROJQUAY-8508)

storage/cloud.py
This PR removes the `_stream_write_internal` function override that caused excessive memory consumption and defaults to the old one which chunks uploads. Server assembly is still not suppored by GCS, so we have to assemble everything locally. However, GCS does support the copy function, so a reupload is not needed.
~~~
REPOSITORY                                        TAG         IMAGE ID      CREATED      SIZE
registry.fedoraproject.org/fedora                 latest      ecd9f7ee77f4  2 days ago   165 MB
quay.skynet/ibazulic/big-mirror-test              size138gb   8e6ba9ff13c0  3 days ago   148 GB
quay.skynet/quay-mirror/big-mirror-test           size138gb   8e6ba9ff13c0  3 days ago   148 GB
quay.skynet/ibazulic/mfs-image-test               latest      ab14f2230dd9  7 days ago   5.96 GB …
=> storage: Enable multipart upload for Google Cloud Storage (PROJQUAY-6862)

data/billing.py, util/marketplace.py, util/test/test_marketplace.py, workers/reconciliationworker.py, workers/test/test_reconciliationworker.py
Adds the following changes for integrating a free tier SKU to the reconciler:
- Adds remove method to marketplace api class to allow for the removal of free tier SKUs
- Refactors reconciliationworker to account for the actions of creating free/paid SKUs for users and removing free SKUs when users obtain paid subscriptions
- Adds test coverage for free tier cases to reconciliationworker
=> marketplace: free tier integration for reconciler (PROJQUAY-5698)

scripts/app_sre_build_deploy_frontend.sh
Add a cleanup step before running the container in our build and deploy frontend script. Addresses an error in build pipelines where resources are not cleaned up:
```
16:12:07 Error: creating container storage: the container name "quay" is already in use by 6c07a1019b5d00203a6366ba5ce2add24ba44f7949303b148b32a1b38a1be282. You have to remove that container to be able to reuse that name: that name is already in use, or use --replace to instruct Podman to do so.
```
=> scripts: clean up old container in frontend build script (PROJQUAY-0000)

data/billing.py, workers/reconciliationworker.py, workers/test/test_reconciliationworker.py
Fixes an error reported in sentry during the reconciliation `AttributeError: module 'stripe.error' has no attribute 'InvalidRequestException'`. This is because the actual exception is `InvalidRequestError`
=> reconciler: fix typo in exception type (PROJQUAY-0000)

workers/reconciliationworker.py, workers/test/test_reconciliationworker.py
The user api seems to now give an error response when a lookup is called with email = `""`
```
{
"code": "validation_error",
"detail": "com.redhat.services.user.domain.validation.ConstraintViolationException: path=emailStartsWith rejectedValue= errorCode=required properties={}",
"validationErrors": [
{
"path": "emailStartsWith",
"value": "",
"code": "required"
}
]
}
```
This causes problems during the reconciliation loop and prevents it from completing. Adds a check for `""` as well as `None` that prevents lookup from happening. Also increases logging level for certain operations for better observability
=> reconciler: fix exception when user api is called with empty email (PROJQUAY-5698)

workers/reconciliationworker.py, workers/test/test_reconciliationworker.py
Remove adding/updating web customer ids in database during the reconciler run. Using the database to reference web customer ids was removed in https://github.com/quay/quay/pull/3302
=> reconciler: Remove database calls for storing/changing web customer ids (PROJQUAY-0000)

.github/workflows/CI-nightly.yaml, .github/workflows/CI.yaml
* chore: move github runners to ubuntu-22.04
* use docker image with openssl 1.1 preinstalled
* using non-interactive mode for github actions
* remove starting docker
* remove starting docker service
* install openssl 1.1 on ubuntu-22.04
* minor fixes
* compiling from source
* check openssl version
* check openssl version before running tox
* use exports when running tox
* fix typo
* overwrite OPENSSL_VERSION var
* minor fixes
* use python3.9 before installing openssl-1.1
* download python and configure openssl1.1
* adding sudo to configure
* use sudo for make
* minor fixes
* using python venv to run tox
* Apply changes to all tests
=> chore: move github runners to ubuntu-22.04 (#3783)

Dockerfile
Adds following adjustments to the Dockerfile necessary for hermetic builds on Konflux:
- Update base nodejs-10 images to nodejs-16 to make use of npm lockfile version 2
- Use `CYPRESS_INSTALL_BINARY` flag to prevent downloading the cypress binary when building frontend
- External curl requests that fail should then try to find the dependency at the output directory generated by Konflux's prefetch dependencies step
=> dockerfile: dockerfile changes for konflux (PROJQUAY-8804)

data/model/permission.py, endpoints/api/test/test_tag.py
it uses a union query which doesn't invoke the replica selection logic. Make this into 2 seperate queries
=> db: optimize _get_user_repo_permissions to send to read replica (PROJQUAY-8839)

Dockerfile
Konflux uses cachi2 to fetch dependencies for our build. Cachi2 will inject environment variables in every `RUN` step of the dockerfile so it can use the prefetched dependencies. This will cause problems during build because the `GOPATH` is overwritten for the config editor. Explicitly setting the default `GOPATH` during the go install step fixes this problem
=> dockerfile: set GOPATH env var before running go build in dockerfile (PROJQUAY-8789)

deploy/openshift/quay-py3-app.yaml
the registry proxy pods compete for CPU resources. Make sure we don't schedule them with the quay pods
=> deploy: add anti-affinity for registry-proxy pods (PROJQUAY-8839)

storage/downloadproxy.py
The current JWT expiry time of 30 seconds is sometimes inadequate, especially for scanning purposes when download is not as quick as one expects. This will increase the expiry time to 10 minutes allowing downloading of layers even in slower environments.
=> storage: Increase proxy JWT expiry to 10 minutes (PROJQUAY-8894)

util/metrics/otel.py
Fixes exception when using dynatrace:
```
AttributeError: 'BatchSpanProcessor' object has no attribute 'export'
File "/app/lib/python3.9/site-packages/opentelemetry/sdk/trace/export/__init__.py", line 362, in _export_batch
self.span_exporter.export(self.spans_list[:idx])  # type: ignore
```
=> otel: fix dynatrace issue (PROJQUAY-8902)

config-tool/pkg/lib/editor/package-lock.json, config-tool/pkg/lib/editor/package.json, package-lock.json, package.json, web/package-lock.json, web/package.json
Syncing this CVE fix with `master`
- deps: update cross-spawn from 6.0.x to 6.0.6
- deps: update cross-spawn from 7.0.x to 7.0.6
=> cve: bumping cross-spawn to 6.0.6 and 7.0.6 (PROJQUAY-8210)

artifacts.lock.yaml
Adds an artifacts lock file for hermetic builds on konflux
Following documentation [here](https://konflux-ci.dev/docs/building/prefetching-dependencies/#generic)
=> build: add artifacts lockfile (PROJQUAY-8931)

data/model/repository.py, data/model/test/test_repository.py, data/registry_model/registry_proxy_model.py
To fix the CVE-2025-4374 reported default permission assignment of  `admin` even to unprivileged and Organization wide assigned none `admin` users, the `create_repository` method get's extended to understand if a PROXY_CACHE_FEATURE requested pull creating a repository is happening and only `read` permissions should be assigned to the user who first pulls the repo/image.
=> proxycache(permissions): CVE-2025-4374 (PROJQUAY-8892)

requirements-build.txt
Updating gevent also requires updating cython to >= 3.0.11
=> deps: updating cython

requirements-build.txt
required for builds to work with gevent update
=> deps: updating cffi

.tekton/quay-test-pull-request.yaml
enable source image build in pipeline
should fix `[Violation] source_image.exists`
=> chore: enable source build image (PROJQUAY-0000)

workers/reconciliationworker.py
Lock ttl should match the frequency of the worker so only one worker runs at a time
=> chore: reconciler lock match frequency (PROJQUAY-8933)

Dockerfile
Testing out a fix for issue in 3.12 and up CI with oci check:
```
> [build-python 1/7] RUN set -ex	; microdnf -y --setopt=tsflags=nodocs install 		gcc-c++ 		git 		openldap-devel 		python39-devel 		libffi-devel         openssl-devel         diffutils         file         make         libjpeg-turbo         libjpeg-turbo-devel 		wget 		rust-toolset 		libxml2-devel 		libxslt-devel 		freetype-devel 	; microdnf -y clean all:
2.564  Problem 1: package rust-toolset-1.84.1-2.module+el8.10.0+23064+1bf4ac64.noarch from ubi-8-appstream-rpms requires rust = 1.84.1-2.module+el8.10.0+23064+1bf4ac64, but none of the providers can be installed
2.564   - package rust-1.84.1-2.module+el8.10.0+23064+1bf4ac64.x86_64 from ubi-8-appstream-rpms requires rust-std-static(x86-64) = …
```
=> ci: Oci fix (PROJQUAY-0000)

data/migrations/env.py, storage/cloud.py, workers/reconciliationworker.py
The `logging.warn()` method is deprecated since Python2.7 and replaced with `logging.warning()`.
=> fix: migrate to logging.warning (PROJQUAY-8996)

requirements-build.txt
This version is required specifically for cryptography 44.0.1
=> deps: downgrading maturin to 1.7.5

quay-entrypoint.sh
Currently, we don't install certs when starting alembic migrations on the db. This poses a problem when Quay is behind a proxy and proxy HTTPS connection is needed to connect to the database. This small fix will make alembic migrations take into account certificates installed in `extra_ca_certs` folder.
=> alembic: Install certs during alembic migrations (PROJQUAY-9135)

conf/nginx/http-base.conf.jnj, conf/nginx/rate-limiting.conf.jnj, conf/nginx/server-base.conf.jnj
Should extract the namespace from auth scope param and implement rate limits based on that. Should fall back to auth header if namespace cannot be extracted for some reason
=> nginx: rate limit on namespace (PROJQUAY-9203)

conf/nginx/http-base.conf.jnj
Removing rate limit key from nginx logs as it was only needed to test behavior in stage
=> nginx: remove rate_limit_key from nginx logs (PROJQUAY-9203)

.tekton/quay-v3-14-pull-request.yaml, .tekton/quay-v3-14-push.yaml
Fixes improper use of the hermetic parameter for the oci run script task. Should fix conforma test on konflux
=> chore: add hermetic param to run oci script (PROJQUAY-0000)

.tekton/quay-v3-14-pull-request.yaml, .tekton/quay-v3-14-push.yaml, rpms.lock.yaml, ubi.repo
This is to address the following conformance failure on konflux where repo ids do not match what is in the allowlist
```
RPM repo id check failed: An RPM component in the SBOM specified an unknown or disallowed repository_id: pkg:rpm/redhat/acl@2.2.53-3.el8?arch=x86_64&checksum=sha256:a22d3f42d7a49ab2e8e7d1c831a80fca159a649a8969ab0617ab93b24df5fa20&repository_id=ubi-8-baseos-rpms (283 additional similar violations not separately listed)
```
Updated `ubi.repo` with proper repo ids:
``` 
sed -i '' 's/\[ubi-8/[ubi-8-for-$basearch/' ubi.repo 
sed -i '' 's/\ubi-8-codeready-builder/codeready-builder-for-ubi-8-$basearch/' ubi.repo
```
Then regenerated lockfile:
```
docker run --rm -v ${PWD}:/work localhost/rpm-lockfile-prototype:latest \
--image registry.access.redhat.com/ubi8/ubi-minimal:latest …
```
=> konflux: update rpm lock file (PROJQUAY-0000)

.tekton/quay-v3-14-pull-request.yaml, .tekton/quay-v3-14-push.yaml
Addresses the following conformance test by adding parameter to tekton task to add script runner image to sbom.
```
Pre-Build-Script task runner image "registry.access.redhat.com/ubi8/ubi:latest@sha256:a91cd157f699b48c7d15a8b38c77163cc8b4a1bdd7d510fcf1aa59e54c99c953" is not in the SBOM
```
=> konflux: add additional base images (PROJQUAY-9279)

Dockerfile, package-lock.json
Still receiving errors on konflux about our nodejs base image being deprecated. Updating to nodejs-22 which seems like the most up to date image on the Red Hat catalog.
=> dockerfile: update to nodejs-22 (PROJQUAY-9279)

deploy/openshift/rosa/quay-py3-deploy-template.yaml
* Move service annotations to a template parameter. This adds flexibility to modify the NLB features through the saas file instead of changing the template.
* Change the LOADBALANCER_ parameter names to HTTPS_LB_ for consistency. 
[APPSRE-12251](https://issues.redhat.com/browse/APPSRE-12251)
=> fix: ROSA deployment template improvements (PROJQUAY-0000)

package-lock.json, web/package-lock.json
- **on root**
```
➜  quay git:(update-sha-js-master) ✗ npm list sha.js  
```
- **on web**
```
➜  web git:(update-sha-js-master) ✗ npm list sha.js  
└─┬ webpack@4.46.0
└─┬ crypto-browserify@3.12.0
└── …
```
=> deps: update sha.js to 2.4.12 (PROJQUAY-9332)

package-lock.json, web/package-lock.json
- **on root**
```
(.venv) ➜  quay git:(update-sha-js-3.14) ✗ npm list sha.js
```
- **on web**
```
(.venv) ➜  web git:(update-sha-js-3.14) ✗ npm list sha.js
└─┬ webpack@4.46.0
└─┬ crypto-browserify@3.12.0
└── …
```
=> [redhat 3.14] deps: update sha.js to 2.4.12 (PROJQUAY-9340)

package-lock.json, web/package-lock.json
- **on root**
```
(.venv) ➜  quay git:(update-sha-js-3.11) ✗ npm list sha.js
```
- **on web**
```
(.venv) ➜  web git:(update-sha-js-3.11) ✗ npm list sha.js
└─┬ webpack@4.46.0
└─┬ crypto-browserify@3.12.0
└── …
```
=> [redhat 3.11] deps: update sha.js to 2.4.12 (PROJQUAY-9343)

package-lock.json, web/package-lock.json
- **on root**
```
(.venv) ➜  quay git:(update-sha-js-3.10) ✗ npm list sha.js
```
- **on web**
```
(.venv) ➜  web git:(update-sha-js-3.10) ✗ npm list sha.js
└─┬ webpack@4.46.0
└─┬ crypto-browserify@3.12.0
└── …
```
=> [redhat 3.10] deps: update sha.js to 2.4.12 (PROJQUAY-9344)

package-lock.json, web/package-lock.json
- **on root**
```
(.venv) ➜  quay git:(update-sha-js-3.9) ✗ npm list sha.js
```
- **on web**
```
(.venv) ➜  web git:(update-sha-js-3.9) ✗ npm list sha.js
└─┬ webpack@4.47.0
└─┬ crypto-browserify@3.12.1
└── …
```
=> [redhat 3.9] deps: update sha.js to 2.4.12 (PROJQUAY-9345)

buildman/builder.py, buildman/test/test_buildman.py, templates/base.html, test/test_exceptionlog_sentry.py, util/saas/exceptionlog.py, workers/test/test_worker.py, workers/worker.py
- Configure Sentry to use minimal integrations when OTEL_TRACING is enabled to prevent instrumentation conflicts that broke exception capture
- There is also an issue where connection pool gets full and sentry receives discarded connection error
```
[27744] [WARNING] [urllib3.connectionpool] Connection pool is full, discarding connection: app.getsentry.com. Connection pool size: 1
```
This PR fixes this issue by increasing connection pool size
=> fix: resolve Sentry/OpenTelemetry integration conflicts (PROJQUAY-9198)

data/database.py
This is a follow up to https://github.com/quay/quay/pull/4193 as the issue is still intermitent. 
Sqlite runs into db lock contention, when run with a single worker count is set to 1. This adds retry logic to resolve lock contention only when quay is using sqlite db. 
Testing: Ran `oc-mirror` and deleted the repo during mirroring and no db lock issue was seen.
=> sqlite: Add retry with exponential backoff for sqlite (PROJQUAY-8758)

workers/quotaregistrysizeworker.py, workers/test/test_quotaregistrysizeworker.py
worker(quotaregistrysize) lacks the check to run calculation if no **superusers** are defined statically but retrieved from **LDAP** instead.
Reproducer:
```
$ grep 'SUPERUSER' conf/stack/config.yaml
FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: false
LDAP_SUPERUSER_FILTER: (|(memberOf=cn=quay-superusers,ou=Groups,dc=example,dc=com)(memberOf=cn=quay-readonly-superuser,ou=Groups,dc=example,dc=com))
FEATURE_SUPERUSERS_FULL_ACCESS: true
```
```
$  python workers/quotaregistrysizeworker.py
Super users disabled or none specified; skipping quotaregistrysizeworker
```
=> workers(quotaregistrysize): added to run quotasizeworker when SUPERUSERS are retrieved from LDAP (PROJQUAY-8086)

workers/quotaregistrysizeworker.py, workers/test/test_quotaregistrysizeworker.py
As documented in `PROJQUAY-9460 [New] : Total Registry Size Calculation return 0 KB and always queued`, the logical condition is not checked correctly and needs to be adjusted as `if any (database or LDAP)` which was wrongly added as `if all (database or LDAP)` which blocks Quota calculation of all none LDAP based deployments.
Unittest have been adjusted and a note has been added as the logic has to be re-implemented in the unittests as the conditions are only evaluated during process start `__name__ == "__main__"`
=> workers(quotaregistrysize): fixed wrong condition to run quotasizeworker from PROJQUAY-8086 (PROJQUAY-9460)

docker-compose.static, endpoints/api/user.py, endpoints/oauth/login.py, local-dev/stack/config.yaml, oauth/base.py, oauth/oidc.py, oauth/pkce.py
- Implement PKCE for OIDC:
- Add oauth/pkce.py (code_verifier + S256 challenge)
- Extend OAuthService.get_auth_url/exchange_code to accept extra auth/token params and support public clients (omit client_secret)
- Wire PKCE in OIDCLoginService; plumb code_verifier on token exchange
- endpoints/api/user.py: generate code_verifier, store in session, include code_challenge(+_method)
- endpoints/oauth/login.py: pass code_verifier only when present to avoid non-OIDC providers breaking
- Security improvements:
- Add PKCE method validation to fail fast on invalid configuration
- Improve defensive session data validation in OAuth callbacks
- Set explicit Content-Type header for form-encoded OAuth requests
- Optimize non-verified JWT decode by avoiding unnecessary key fetching
- Implement …
=> feat(oidc): add PKCE (S256/plain) support with session-verifier flow (PROJQUAY-9281)
